### ISSUE TITLE
Ability to revert changes in user profile

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1026]
**Background**
The admin should have the possibility to revert changes just performed when modifying a user profile.

**Approach**
Behavior should be similar to the "Revert" function at the System Preferences tab.
The button **Revert** shall be added near the **OK** button at the user editing form:
- by default, when the editing form has just opened - the **Revert** button is disabled
- if the admin performs any changes at this form - the **Revert** button becomes enabled
- when the **Revert** button is clicked:
   - all user settings (_Default data storage_, _Roles & Groups_ list, _Attributes_ and _Launch options_) shall be returned to the previous state (as before changing)
   - the **Revert** button becomes disabled
- the **OK** button should stay with the same functionality as now

**Comment by rodichenko** [comment]
@NShaforostov could you verify this issue please? Also, the same behavior is implemented for the Role/Group edit dialog.

**Comment by NShaforostov** [comment]
@rodichenko Verified. Works well

**Comment by NShaforostov** [comment]
Docs were updated via #1184
