### ISSUE TITLE
Add help tip for launch page resources section

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#1027]
**Background**

Currently there is resources section on launch page which shows how many compute resources we are going to start. It even shows an interval of allocating resources for autoscaled clusters. Since #817 will be merged autoscaled cluster worker machine types can vary differently depending on the specified run parameters.

![image](https://user-images.githubusercontent.com/16464586/78144290-18209300-7438-11ea-9ef4-9858614f3f97.png)

**Approach**

It would be nice to have an additional tip ![image](https://user-images.githubusercontent.com/16464586/78145587-bd883680-7439-11ea-9161-c42ba0bce5e1.png) for the launch page resources section which will say something like the following:
> General amount of resources that will be allocated during the run execution. Notice that in some specific configurations such as **hybrid autoscaling clusters** amount of resources can vary beyond the shown interval.

**Comment by rodichenko** [comment]
@sidoruka @tcibinan as we have #1039 implemented now, do we need extra tooltip for the cluster? We already show such tooltip at `Cluster Configuration` window

**Comment by tcibinan** [comment]
From my point of view this is kind of a different tooltip which explains that the allocated resources can go beyond the shown intervals. @sidoruka What do you think?

![image](https://user-images.githubusercontent.com/16464586/78793842-a4443480-79bb-11ea-9226-e6a79769f829.png)

**Comment by rodichenko** [comment]
@NShaforostov could you verify this issue please?

**Comment by NShaforostov** [comment]
@rodichenko Verified
