### ISSUE TITLE
Extend `pipe storage mount` logging

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1030]
**Background**
At the moment, it's almost impossible to trace any issue, that may happen during the `pipe storage mount ...` lifetime.
E.g. If it was working for some time and, eventually, mountpoint becomes unavailable - we don't know how to troubleshoot.

**Approach**
We shall extend logs and (optionally) print any event, that occurs within an application.

**Comment by sidoruka** [comment]
Shall be backported to `release/0.15`

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.15` via db1022ffbc056a71c869ba2690db58481ecade3a.
