### ISSUE TITLE
Admin shall be able to restrict "cross-cloud" storage mounts

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1034]
**Background**
At the moment, Cloud Pipeline will attempt to mount data storages across all the available clouds/regions.
E.g. if a job is launched in the GCP, but the user has access to AWS S3 buckets - they will be mounted to the GCP instance.
In certain cases, this is not the desired behavior.

**Approach**
* Let's introduce a parameter in the Cloud Region's options: `Mount storages across other regions`, which may contain one of the following values:
  * `None` (default)
  * `Same Cloud`
  * `All`
* If the parameter is set to `None`: the Cloud Region's storages shall not be mounted anywhere, except the current region
* If the parameter is set to `Same Cloud`: the Cloud Region's storages shall be mounted only to the instances, which are spawned in different regions of the same Cloud Region. 
* If the parameter is set to `All`: the Cloud Region's storages shall be mounted to all the instances in all the regions (current behavior)

E.g.:
  * 3 regions are configured:
    * AWS us-east-1 (`Same Cloud`)
    * AWS eu-central-1 (`All`)
    * GCP us-east4 (`None`)
  * If a job is launched in us-east-1: storages from `us-east-1` and `eu-central-1` shall be mounted
  * If a job is launched in eu-central-1: same as `us-east-1`
  * If a job is launched in us-east4: storages from `us-east4` and `eu-central-1` shall be mounted

**Comment by sidoruka** [comment]
@rodichenko please take care of the GUI part

**Comment by maryvictol** [comment]
@SilinPavel 
Now  If the parameter is set to **None** the Cloud Region's storages aren't mounted in the current region.
**Expected:** If the parameter is set to **None**: the Cloud Region's storages shall not be mounted anywhere, except the current region.

**Comment by NShaforostov** [comment]
Docs were updated via #1184

**Comment by tcibinan** [comment]
> @SilinPavel Now If the parameter is set to **None** the Cloud Region's storages aren't mounted in the current region. **Expected:** If the parameter is set to **None**: the Cloud Region's storages shall not be mounted anywhere, except the current region.

Confirmed by @sidoruka.

If the parameter is set to **None**, then the region's storages are not mounted to runs including this region's runs.
