### ISSUE TITLE
Interactive endpoints shall be (optionally) available to the anonymous users

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1037]
**Background**
At the moment, Cloud Pipeline allows sharing the interactive and SSH endpoints with the other users/groups. This requires the end-user to be registered in the Cloud Pipeline users database.
For certain use-cases, it is required to allow such type of access for any user, who has successfully passed the IdP authentication but is not registered in the Cloud Pipeline.
We do have a feature to automatically register users (based on the AD groups), but this is not a desired behavior in this case - such `Anonymous` users shall not be registered at all.

**Approach**
* GUI shall allow specifying `Anonymous` user for the interactive and SSH endpoints sharing
* API shall handle such situation:
  * If a user is logging in and the SAML response is valid, but the user is not registered and the auto-registration (of any kind) is not enabled - such user shall be treated as `Anonymous`
  * JWT tokens shall be issued correctly without any groups/roles assigned
  * This behavior shall be enabled/disabled by a certain System Preference
* If the `Anonymous` access to an endpoint is enabled - EDGE shall behave as usual. Redirect to the API and perform the JWT validation

**Comment by sidoruka** [comment]
This shall be backported to `release/0.15`

**Comment by mzueva** [comment]
### Implementation details

1. `SAMLUserDetailsServiceImpl` shall allow access of anonymous users of successfully authenticated/validated users from IDP.  This shall work when `saml.user.auto.create` property is `EXPLICIT_GROUP` and `saml.user.allow.anonymous` (to be added to application properties) is `true`. Anonymous user is not saved to DB and has only one role - `ROLE_ANONYMOUS_USER`, all other attributes (username, groups, etc.) shall be filled from SAML message
2. Configure `SAMLSecurityConfiguration` and `JWTSecurityConfiguration` to require role `USER` or `ADMIN` for all secured resources and role `ANONYMOUS_USER`, `USER` or `ADMIN` for `anonymous` endpoints. `Anonymous` endpoints shall be configured via application properties, default value is `/restapi/route`

**Comment by tcibinan** [comment]
Notice that the current implementation requires the run's owner to share the run with both `ROLE_USER` and `ROLE_ANONYMOUS_USER` to allow run's endpoint to be accessible to any idp user.

**Comment by NShaforostov** [comment]
Verified.
The feature works well for **endpoints**.
Some notes:
- **SSH**-sessions aren't available for described anonymous users regardless of the state of the "Enable SSH connection" checkbox in the sharing popup for the `ROLE_ANONYMOUS_USER`
- **FSBrowser** is available for described anonymous users regardless of the run state (shared/not shared). Perhaps this applies to #1057

**Comment by tcibinan** [comment]
@sidoruka Please say if it is good enough to be cherry-picked to `release/0.15`.

**Comment by NShaforostov** [comment]
Docs were added via #1184
