### ISSUE TITLE
User shall be able to enable "hybrid" cluster in the GUI

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1039]
**Background**
At the moment, Cloud Pipeline allows to run the `hybrid` autoscaled cluster (#298). But this is done by specifying a `System Parameter`.
Most of the users would like to have just a "checkbox" to enable this.

**Approach**
* Add `Enable Hybrid cluster` checkbox to the `Auto-scaled cluster` tab
* Add a help tooltip with the following wording
```
Compute nodes of the cluster will be created according to the jobs' requirements. By default, the same instance family (as the master) is used. But the size of the node will vary
```
* This checkbox shall set `CP_CAP_AUTOSCALE_HYBRID` parameter to `true`

**Comment by rodichenko** [comment]
@NShaforostov could you verify this issue please?

**Comment by NShaforostov** [comment]
@rodichenko Verified. Works well

**Comment by NShaforostov** [comment]
@sidoruka as you think, should we add other parameters for configuring a hybrid cluster (CP_CAP_AUTOSCALE_HYBRID_FAMILY, CP_CAP_AUTOSCALE_HYBRID_MAX_CORE_PER_NODE) into the System Parameters? Currently, users can learn about them only from docs.

**Comment by sidoruka** [comment]
Yes, please add it

**Comment by NShaforostov** [comment]
Turns out, it was done by b9e03483120b0ee4822d37fa8012b86e0a9c9314.

**Comment by NShaforostov** [comment]
Docs were updated via #1184
