### ISSUE TITLE
Bucket deletion by alias fails in pipe-cli

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#104]
`pipe-cli` uses storage path rather then storage name while deleting storage. Therefore storage can be deleted by name only if a storage name equals storage path.

**Comment by sidoruka** [comment]
All bucket operation (including cp/mv/rm/etc) can be performed only by path. Let's consider this as `ok`, at least for now

**Comment by mzueva** [comment]
@sidoruka all primary `pipe storage` operations support storage `name` as well as `path`, e.g. you can address storage like:
```
pipe storage ls cp://analysis
pipe storage ls s3://cp-analysis
```
