### ISSUE TITLE
Folder/File level permissions shall be introduced for the object storages

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1040]
**Background**
At the moment, Cloud Pipeline allows managing permissions for the whole object storage. So that all the users/groups have defined access level to all the object storage's paths.
In certain cases, we need to have a more "atomic" type of access management for the object storages. 
I.e. we shall allow to specify permissions (Owner/Users/Groups + RWX) for any path within data storage (directory/prefix and files/objects)

**Approach**
* Per-path access management shall be respected by all the types of user-access:
  * GUI
  * CLI (pipe storage's batch commands, e.g. cp/mv/ls)
  * CLI (pipe storage's mount command)
* View/manage per-path permissions shall be implemented in the GUI for now
* CLI permissions management and retrieval commands shall be implemented as a next step

**Comment by mzueva** [comment]
Current implementation adds the following features with some limitations:

- User is ables to register a storage with some prefix, e.g.: `s3://bucket/folder`
- Permissions are managed for a single datastorage, thus if a user has different permissions for different paths in one bucket - every path shall be registered as a separate storage
- Paths permissions shall not intersect, e.g. if a user has read permission on a upper level folder `folder/`, you cannot restrict access to a folder under it: `folder/inner`
- GUI, pipe CLI, pipe mount and mounts on running instances shall be fully functional for storages with prefixes
- s3fs mount require some additional operations to allow work with folders - this will be added in the next PR

@NShaforostov could you please verify this feature?

**Comment by NShaforostov** [comment]
I've tried to verify this feature. Some notes below:

### GUI

1. Imagine: admin or user with the corresponding permissions creates the storage `parent` and then the storage with the path `parent/child`. Now, such action automatically creates an extra folder with the name `child` in the second storage:
![image](https://user-images.githubusercontent.com/45459424/80043064-4f4f0500-8509-11ea-8e71-e1cef9a2d073.png)
It may confuse the user, for whom the permissions on the second storage are set. As the number of hierarchy levels increases, the count of "extra" folders increases too (example for the "sub-substorage"): 
![image](https://user-images.githubusercontent.com/45459424/80043504-8d005d80-850a-11ea-9586-15b1fc05ec33.png).
2. If the user, for whom the **WRITE** permission was set on the `parent/child` storage removes that "extra" folder (described in item 1) - the storage is being removed too:
![image](https://user-images.githubusercontent.com/45459424/80044057-09477080-850c-11ea-9251-ebfb48cb6cbf.png)
3. If to delete `parent` storage - all `child` storages will be still visible in the library list but the don't exist in fact:
![image](https://user-images.githubusercontent.com/45459424/80044355-e8334f80-850c-11ea-9ed4-2c4dd3c8fb69.png)
Perhaps, we shall print extra-message when trying to remove `parent` storage? Or shall remove it with all its `childs`?
4. Imagine:
   - Admin creates storages: `parent`, `parent/child/level2_child1` and `parent/child/level2_child2`.
   - Admin set, for example, **READ** permission to the user on the `parent/child/level2_child1` storage
   If that user has the **ROLE_STORAGE_MANAGEMENT** and any folder with the **READ** & **WRITE** permissions in the library - he can create the storage `parent/child` and via it will have **full** access on the content of `child` (including `level2_child1`, `level2_child2`).

### pipe CLI

1. Works well if the user has only **READ** permission on the `parent/child` storage
2. If the user has the **WRITE** permission on the `parent/child` storage - in general, everything works well excluding the `pipe storage mkdir` command:
![image](https://user-images.githubusercontent.com/45459424/80045241-76103a00-850f-11ea-9a2b-efc10f66dde7.png)

### pipe storage mount

1. Works well if the user has only **READ** permission on the `parent/child` storage
2. If the user has the **WRITE** permission on the `parent/child` storage:
   - attempt to write a file into the mount point creates an empty file:
![image](https://user-images.githubusercontent.com/45459424/80045532-5cbbbd80-8510-11ea-9bef-c66f6dba5635.png)
   - `cp`/`mv` commands throw the error like `/bin/cp: failed to close './file.txt': Invalid argument` when the source is the local disk and the destination is mounted bucket. The file in the destination is being created but it's empty. This is only true for regular files. Files created by `fallocate`, `truncate`, `dd` are being copied and moved without problems.
   - `truncate` and `fallocate` commands allocate space and create files inside the mounted bucket. But these commands fail with resizing:
![image](https://user-images.githubusercontent.com/45459424/80046678-f5a00800-8513-11ea-842b-74600a66a271.png)
   - `mkdir` command doesn't work - it fails with the error `mkdir: cannot create directory 'folder': No such file or directory`

"Mounts on running instances" aren't verified yet. I'll send an additional comment after checking it.

**Comment by mzueva** [comment]
@sidoruka One more concern: how should we mount if parent and child storages are allowed for user? E.g. user has access to s3://bucket and s3://bucket/folder - shall we filter such intersections and mount only parent?

**Comment by sidoruka** [comment]
@mzueva if we are talking about the "in-instance" mounts (i.e. s3fs, goofys, pipe storage mount) - then we, probably, shall not care about that.
if there are intersections - the folders will be just "mounted over" each other.

**Comment by NShaforostov** [comment]
I've verified "**Mounts on running instances**".
Some notes below:

#### goofys

For mounted buckets with the **WRITE** permission:
1. `fallocate` operations aren't supported (files are being created with the error `fallocate: fallocate failed: Operation not supported` and empty)
2. `truncate` command is being executed without errors, but all created by the `truncate` command files have the null size
3. When trying to move files from the instance filesystem into the mounted bucket via the `mv` command - they are being moved well, but the error appears: `/bin/mv: preserving permissions for './fi_dd': Permission denied`

The described behavior is true for any mounted storage with the **WRITE** permission.

For mounted buckets with the **READ** permission, everything works well.

#### s3fs

For mounted buckets with the **WRITE** permission:
1. Mounted storage is being displayed as **empty** (no files/folders created in it via the GUI or other ways are displayed)
2. All commands are supported. The user can read/write into the mounted folder. But all changes (created files/folders) aren't displayed in the bucket via the GUI or other ways

For other mounted storages (general) with the **WRITE** permission, everything works well, but the `fallocate` command isn't supported.

For mounted buckets with the **READ** permission:
1. Mounted storage is being displayed as **empty** (no files/folders created in it via the GUI or other ways are displayed)
2. All commands are supported. The user can read/write into the mounted folder. But all changes (created files/folders) aren't displayed in the bucket via the GUI or other ways

For other mounted storages (general) with the **READ** permission, everything works well.

#### pipefuse

Notes are fully identical to described ones in the comment above https://github.com/epam/cloud-pipeline/issues/1040#issuecomment-618112344 (for `pipe storage mount`)

**Comment by mzueva** [comment]
@NShaforostov fixes are provided in build 5162.

- **GUI** p.1 and p.2 are fixed, p.3 and p.4 - will remain as is for now.
- **pipe cli** mkdir command is fixed
- **pipe mount** shall be fixed
- **s3fs mount** shall be fixed but only for newly registered buckets

**Comment by NShaforostov** [comment]
@mzueva, verified:
1. **GUI** p.1 and p.2 are fixed
2. **pipe cli** `mkdir` is fixed
3. **pipe mount**:
   - `truncate`/`fallocate` errors are still here:
   ![image](https://user-images.githubusercontent.com/45459424/80135697-3bf37680-85a9-11ea-964d-e7730db892d4.png)
   - others errors are fixed
4. **s3fs mount** is fixed

**Comment by mzueva** [comment]
@NShaforostov `fallocate` and `truncate` are fixed, could you please, verify?

**Comment by NShaforostov** [comment]
@mzueva verified. Works well!
