### ISSUE TITLE
Instance types don't change according to the Cloud Provider in the Tool settings

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1065]
**Describe the bug**
Currently, after #1035 is implemented, the specific Cloud Region could be specified for the tool/its version. But if specify the Cloud Region that belongs to another Cloud Provider, instances types don't change.

**To Reproduce**
1. Open the tool settings
2. Set the Cloud Region different from the current one
3. View the "Instance types" dropdown list values

**Exp.**: Instance types correspond to the selected Cloud Provider
**Act.**: Instance types don't correspond to the selected Cloud Provider

**Screenshots**
![image](https://user-images.githubusercontent.com/45459424/79595771-1caba380-80e8-11ea-8bf7-ce8c398b4013.png)

So, the general user can't launch a tool, if the Region in another Clouder Provider is enforced for it:
![image](https://user-images.githubusercontent.com/45459424/79596501-5fba4680-80e9-11ea-83b8-1d552923865d.png)

**Environment:**
 - Cloud Provider: N/A
 - Version 0.16.0.5118
 - Browser: N/A

**Comment by rodichenko** [comment]
@NShaforostov fixed, could you please verify this issue?

**Comment by NShaforostov** [comment]
@rodichenko 
Verified
