### ISSUE TITLE
Region is being set incorrectly when trying to rerun pipeline

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1066]
**Describe the bug**
Currently, when tries to rerun any run - in the Cloud Region field the default region is being set. But the selected instance type doesn't change automatically and remains the same as was set before the run.
This may lead to the following incorrect situation, e.g.:
1. Set the AWS region as the default
2. Launch the run in the GCP region
3. Stop run, click the **RERUN** button
4. The launch page is opened
**Exp.**: the region and instance type are the same as were at step 3
**Act.**: the region is default (AWS), instance type is the same as was at step 3 (GCP)

**Screenshots**
![image](https://user-images.githubusercontent.com/45459424/79599416-1ae4de80-80ee-11ea-834c-add6ff2dd38a.png)

**Environment:**
- Cloud Provider: N/A
- Version 0.16.0.5118
- Browser: N/A

**Comment by rodichenko** [comment]
@NShaforostov fixed, could you check please?

**Comment by NShaforostov** [comment]
Verified
