### ISSUE TITLE
Allow to configure whether to show "stopped" child runs 

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1072]
**Background**
At the moment, Cloud Pipeline displays all the child runs for the cluster. This is great for WDL/Nextflow pipelines (when a child run processes a separate task) or the static clusters.
But for the "autoscaled" jobs - this produces hundreds of "stopped" entries, which do not make sense to show.

**Approach**
* Let's introduce a "System parameter", which is interpreted by the API (e.g. `CP_SHOW_ACTIVE_WORKERS_ONLY`)
* If it is set to `true` - API shall return only child runs, which have `RUNNING` status, to the GUI/CLI
* This approach is similar to one we have for `CP_DISABLE_WORKER_ENDPOINTS`

**Comment by sidoruka** [comment]
Please backport to `release/0.15`

**Comment by mzueva** [comment]
@sidoruka Is this related to the `Active/Completed Runs` page or to the `Run` page? We return child runs in two different ways: for a list of runs server returns child runs along with the parent one and for a single run client requests child runs in a separate API call.

**Comment by sidoruka** [comment]
@mzueva  Can we have this for both?

**Comment by rodichenko** [comment]
@sidoruka GUI part implemented, backported to `release/0.15` via 25a55fab3c2548532a1c6442f90ccb6163fd2c81

**Comment by tcibinan** [comment]
Cherry-picked backend to `release/0.15` via 999f44cf1766461930cb0bcb6db6b2a3296fd5e3.
