### ISSUE TITLE
Inner data storages navigation bar fails to navigate

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#1077]
**Describe the bug**

Currently navigation bar for so-called inner data storages produces *You cannot navigate to another storage* in case of any interaction with it.

**To Reproduce**

1. Create data storage with some inner path f.e. *data-storage/inner/path*.
2. Double click the navigation bar and press *Enter*.
3. See error.

**Expected behavior**

Navigation bar should behaves the same way it behaves for regular data storages.

**Environment:**

 - Version 0.16.0.5167.6ada20f37b3a368f96bcde514c15b16d50c76fdf
 - Browser: chrome

**Comment by rodichenko** [comment]
@tcibinan fixed, could you check please?

**Comment by tcibinan** [comment]
Looks fine, thanks!
