### ISSUE TITLE
`pipe set-acl` command fails to set permissions for the object by object name

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#1081]
**Describe the bug**
According to the documentation, `pipe set-acl` command sets permissions for the object by object name or object id. However, the `pipe set-acl` command works just by object id. When we specify the command by object name we get the following error:
`Error: Failed to fetch data from server. Server responded with message: Could not read document: Can not deserialize value of type java.lang.Long from String "test-storage-name": not a valid Long value`

**To Reproduce**
1. Perform the CLI `pipe set-acl` command, e.g.:
`pipe set-acl <test-storage-name> -t data_storage -s <User/Group name> -d rwx` 

**Expected behavior**
Permissions set

**Environment:**
 - Cloud Provider: N/A
 - Version: 0.16.0.5190

**Comment by mzueva** [comment]
@kamyshova fix branch is merged

**Comment by kamyshova** [comment]
Fixed. Thanks!
