### ISSUE TITLE
Allow to run "pipe" commands on behalf of the other user

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1085]
**Background**
Quite often administrators need to perform some operations on behalf of the other user (e.g. check permissions/act as a service account/etc.).
At the moment, the only way to do so - is to generate the JWT key via the `jwt-generator.jar`. This is a quite tedious task.
We need to simplify this a lot.

**Approach**
* Add a common option to all the `pipe` commands (except the `configure`, `help`, `version` and similar): `--user|-u <USER_ID>` (where <USER_ID> is the name of the user account, not an integer)
  * If it is specified - any operation shall be performed using the corresponding user account
  * So we shall:
    * Request the JWT token for that user (a corresponding API method shall be added)
    * Use it for the command execution
    * The token shall not be stored anywhere and used only for the command lifetime
* Add a separate command `pipe token <USER_ID> --duration|-d <DAYS>`. It shall print the JWT token, for a specified user for a specified duration (duration is optional, if not set - we shall use the default value, same is in the GUI)
* Of course, these options shall be available to the `ROLE_ADMIN` users only

**Comment by sidoruka** [comment]
Shall be backported to `release/0.15`

**Comment by NShaforostov** [comment]
Docs were updated via #1184
