### ISSUE TITLE
Launch Command can't run in Windows correctly

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1086]
**Background**
The `Launch Command` generation (introduced by #892), uses single-quotes to wrap the `-cmd` value.
E.g. 
![image](https://user-images.githubusercontent.com/20998291/80798849-07d21400-8bae-11ea-918e-0557db916212.png)

This causes when running the generate commands from the Windows environment. As the Windows CMD shell can't resolve it correctly (the command value is still split by the space).

**Approach**

* We shall add an option to the `Launch Command` generation API method to specify the execution environment (Windows/Linux). 
* For now, this option shall control only the type of the quotes (single/double), used to wrap the strings (command and parameters). Default is "Linux"
* GUI shall expose a corresponding selector to choose the type of the environment (similar to the approach implemented for the CLI install script)

**Comment by sidoruka** [comment]
Please backport to `release/0.15`

**Comment by sidoruka** [comment]
Just realized, that this won't help. As the user may get the launch command from the Windows OS, but use in linux. This will cause issues with the env vars ($VAR) wrapped with the double-quotes.
Do not consider this for implementation for now.

**Comment by rodichenko** [comment]
@sidoruka GUI part implemented, backported to `release/0.15` via ad5329135e01ce8e2650d90d0cdb1be0fddd7f11

**Comment by mzueva** [comment]
@sidoruka Done and backported to `release/0.15`
