### ISSUE TITLE
GUI shall allow to configure the Launch Command format

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1089]
**Background**
At the moment, Cloud Pipeline GUI shows the Launch Command exactly from the API response.
Let's add some customization options

**Approach**
* Add a separate preference `ui.launch.command.template` (`User Interface` section, empty by default)
* It shall be used to display the Launch Command's CLI representation
* When displayed - show it "as-is", but replace the `{LAUNCH_COMMAND}` placeholder with the real "Launch Command" from the API
* If it is not set at all (default) - then behave as now (show only the server's response)

**Comment by sidoruka** [comment]
Cherry pick to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka done, backported to `release/0.15` via 01d408727881a8f97ca6caede06dffa9a57ee29e

**Comment by mzueva** [comment]
@sidoruka SystemPreference was added to `develop` and `release/0.15` branches
