### ISSUE TITLE
Launch Command does not wrap the parameter values with the quotes

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1090]
**Describe the bug**
At the moment, if a user specifies the values of the parameters with "spaces" (e.g. selection of the input parameter value from the GUI bucket browser) - this brakes the command format.

**To Reproduce**
1. Run a job with the input parameter `input1` and the following value: `s3://bucket/file1.txt, s3://bucket/file2.txt`
2. Click on 'Launch Command'
3. The resulting command will contain:
```
--input1 s3://bucket/file1.txt, s3://bucket/file2.txt
```

**Expected behavior**
The resulting command shall contain a value, wrapped into quotes:
```
--input1 's3://bucket/file1.txt, s3://bucket/file2.txt'
```

**Additional context**
Keep in mind that a type of quotes shall be controlled by #1086

**Comment by mzueva** [comment]
@sidoruka Done and backported to `release/0.15`
