### ISSUE TITLE
pipectl location

### ISSUE THREAD

**Issue by sergeyistominepam** [epam/cloud-pipeline#1107]
Hi there,

I'm trying to install cloud-pipeline, but cannot locate pipectl. I was directed to find the link here: https://travis-ci.org/github/epam/cloud-pipeline/jobs/686543890 Job #5319.6.
But there is no link to pipectl itself, but only to the cloudpipeline webapp.

**Comment by sidoruka** [comment]
Hi @sergeyistominepam, all the `pipectl` installer scripts, as well as the source binaries, are published to the `s3://cloud-pipeline-oss-builds/builds` S3 location. This location is publicly available.
The `/build` prefix contains a number of folders, two of them might be interesting for you:
* `/build/develop/` - contains latest versions, built from `develop` branch
* `/build/release/` - contains LTS versions, built from the respective `release/*` branches (only `release/0.15` for now)

So you can do the following to get the latest possible build:
```
# List all available items
$ aws s3 ls s3://cloud-pipeline-oss-builds/builds/develop/ --no-sign-request
...
2020-05-12 14:20:39     956093 pipectl.0.16.0.5306.e279186a7e6480707d4524550a7539866a38615b
2020-05-12 16:23:14     933390 pipectl.0.16.0.5313.e1df2d20133caff76e9f8ca8e07763f627b1443d
2020-05-12 20:52:20     942946 pipectl.0.16.0.5314.c5fa3817fc0628250f0ded4f96f2b8aa577fc63e
2020-05-13 13:12:45     939003 pipectl.0.16.0.5319.7502360d35087ec3f34205273fde9d74ee44dc72

# Get the latest pipectl to a current directory
$ aws s3 cp s3://cloud-pipeline-oss-builds/builds/develop/pipectl.0.16.0.5319.7502360d35087ec3f34205273fde9d74ee44dc72 ./ --no-sign-request
download: s3://cloud-pipeline-oss-builds/builds/develop/pipectl.0.16.0.5319.7502360d35087ec3f34205273fde9d74ee44dc72 to ./pipectl.0.16.0.5319.7502360d350
87ec3f34205273fde9d74ee44dc72
```

Please let me know if you are facing any issue with the access/permissions.

**Comment by sergeyistominepam** [comment]
Thanks a lot. It worked!
