### ISSUE TITLE
WDL graph: incorrect work with inputs for workflow

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#111]
__PART-1__
1. Create pipeline from WDL template
2. Open pipeline, select version
3. Click on GRAPH tab
4. Click on workflow
5. Click "PROPERTIES" button
6. At "Properties" panel add new record with all filled fields into "Inputs" section
7. Click "Save" button
8. Enter commit message, set "Update configuration" checkbox, click "Commit"
9. Click on workflow
10. Click "PROPERTIES" button
11. Click on "Inputs" collapsed header

__*exp.*__: record added at step 6 is displayed in "Inputs" section
__*act.*__: "Inputs" section is empty

__PART-2__
1. Perform PART-1
2. At "Properties" panel add new record with all filled fields into "Inputs" section
3. Click "Save" button
4. Enter commit message, set "Update configuration" checkbox, click "Commit"
5. Click on "CODE" tab, click on *.wdl file
6. Check that there are 2 parameters (from step 6 of PART-1 and from step 2 of PART-2), close window
7. Click on config.json
8. Close window, click on "CONFIGURATION" tab

__*exp*__: after steps 7, 8 there are 2 parameters are displayed (in code and "parameters" section)
__*act*__: only parameter from PART-2 is displayed

**Comment by rodichenko** [comment]
@NShaforostov all workflow's input variables with default values set are treated as `optional` declarations, which **cromwell-wrapper** *doesn't include* in `inputs.json` (file with all input parameters for wdl workflow). At the same time such variables are still possible to override using env vars, and if you do so, **cromwell-wrapper** *will include* those values in 'inputs.json'.
Our `WDL visualization` component and standard `Launch` form meets this scenario, i.e.:
* We do not include `optional` workflow's parameters in `config.json`;
* You're still able to override them by adding parameters in `Launch` form.

**Comment by NShaforostov** [comment]
Checked
