### ISSUE TITLE
WDL graph: scatterItem value doesn't appear after saving

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#112]
1. Create pipeline from WDL template
2. Open pipeline, select version
3. Click on GRAPH tab
4. Click "PROPERTIES" button
5. Click "+ ADD SCATTER"
6. Click on appeared scatter object
7. Click on "Inputs" collapsed header
8. Enter a valid value into "Value" field
9. Click "Save" button
10. Enter commit message, click "Commit"
11. Click on scatter object
12. Click "PROPERTIES" button
13. Click on "Inputs" collapsed header

__*exp.*__: in "Value" field there is a value specified at step 8
__*act.*__: "Value" field is empty

**Comment by rodichenko** [comment]
@NShaforostov , modifying Scatter's input (except for renaming it) is forbidden for now. Each scatter *must* have only 1 input of type 'ScatterItem' without any value

**Comment by NShaforostov** [comment]
Checked
