### ISSUE TITLE
Allow to "symlink" the tools between the tools groups

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1122]
**Background**
At the moment, the majority of the tools are managed by the administrators and are available via the `library` tool group.
But some of the users would like to have separate tool groups, which are going to contain a mix of the custom tools (managed by the users) and the `library` tools (managed by the admins).
The latter ones shall be "symlinked" to the users' tool groups. The following behavior is expected:
* "Symlink" creation operation shall be available to the users which:
  * Have read access to the source tool
  * Have write access to the destination tool group
* It shall not be possible to create two levels of "symlinks"
* Users shall be able to run "symlinks" as usual, the following permissions shall be checked to run or view the "symlink":
  * "Symlink" permissions
  * Source image permissions
* It shall not be possible to "push" into the "symlinked" tool. Two options can be considered:
  * Just deny any push operation
  * Behave as real symlinks and push into the source tool
* "Symlinks" shall display all the same description, icon, settings as the source image
* It shall not be possible to make any changes to the "symlink" data (description, icon, settings), even for the admins
* OWNERs shall be still able to manage the permissions for the symlinks

**Approach**
A new field `linkTo` shall be added to `Tool` object to indicate that such a tool is only a link to a real `Tool`.
* Add a new API methods to create a new `symlink` tool from `original` tool
* When a `Tool` is loaded from DB some fields `[description, labels, endpoints, default_command, instance_type, short_description, icon_id]` shall be loaded from `original` tool
* All API methods  to update `symlink` tool shall be forbidden
* All API methods to read versions/attributes/settings/scan/vulnerabilities for `symlink` tool shall load data for `original` tool
* All API methods to update/delete versions/attributes/settings/scan/vulnerabilities for `symlink` tool shall be forbidden
* All push and pull events shall be rejected for `symlink` tools in `/dockerRegistry/oauth` endpoint
* `symlink` tools shall be skipped during scheduled security scanning
* When a run is started with `symlink` tool as docker image it shall be replaced with `original` image for k8s pod spec, but stored as is for DB
* For now permissions shall be handled separately for `symlink` and `original` tool

**Comment by NShaforostov** [comment]
I've tried to verify the feature.
In general, it works nicely.

The following issues were encountered during the verifying:

1. Imagine the case:
- admin create tool group (no matters - personal or not)
- admin give all permissions (R/W/X) to that group for the user (not admin, but with the `ROLE_TOOL_GROUP_MANAGER` role)
- the user creates a "symlink"-tool in that group
- the user tries to open the just-created "symlink"-tool, but it's unavailable:  
![image](https://user-images.githubusercontent.com/45459424/84257212-ab073900-ab1d-11ea-8c09-eafa302b81ba.png)
- if the user opens the tool group - the "symlink"-tool is displayed in the list, but with the broken icon:  
![image](https://user-images.githubusercontent.com/45459424/84257641-51533e80-ab1e-11ea-84e5-c0570a1ef8e8.png)

2. When trying to create a "symlink"-tool in the tool group, where the tool with the same name exists - the error message appears twice:
![image](https://user-images.githubusercontent.com/45459424/84259222-d3dcfd80-ab20-11ea-9796-9c83bbfbe417.png)

**Comment by rodichenko** [comment]
>2. When trying to create a "symlink"-tool in the tool group, where the tool with the same name exists - the error message appears twice:

@NShaforostov fixed by c56ffa5eb9298617c96f2794295374b21d39e2d8

**Comment by NShaforostov** [comment]
@rodichenko verified

**Comment by mzueva** [comment]
> 1. Imagine the case:

@NShaforostov This case is fixed

**Comment by NShaforostov** [comment]
@mzueva Verified

**Comment by NShaforostov** [comment]
Docs were updated via #1184
