### ISSUE TITLE
The additional worker instance isn't scaled down at case typo in submit job command.

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1123]
**Describe the bug**
The additional worker instance isn't scaled down at case typo in submit job command.

**To Reproduce**
1. Open any tool/pipeline.
2. Select the Custom settings near the Run button
3. Click the Configure cluster control in the "Exec environment" section
4. In the appeared popup click the Auto-scaled cluster: Set the "Auto-scaled up to" value('2'); tick the "Enable Hybrid cluster" checkbox
5. Click the Launch button. Set ON-DEMAND price type and launch the run.
6. Open launched run. Click SSH button.
7. In the opened terminal submit a 8-core job to SGE queue using the following command with a typo ('.' at the end) 'qsub -pe local 8 -b y sleep 10m.'
8. Check that after about 10 minutes an additional worker instance will be scaled down

**Actual behavior**
The additional worker instance isn't scaled down.

**Expected behavior**
Autoscaller should scale down additional worker instance immediately

**Environment:**
 - Cloud Provider: AWS
 - Version: 0.16.0.5435.a9bc273034effe5dd1120242602f07ea1e57abb6

**Comment by tcibinan** [comment]
Should be fixed now. Could you please verify it @maryvictol?

**Comment by maryvictol** [comment]
Verified and closed

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.15` via c7b8fd667ff19d1daf829f2fdde05f62110112ce.
