### ISSUE TITLE
`pipe run` custom parameters parsing issue

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1126]
**Describe the bug**
For some reason, `pipe` can't execute a `run` command if it uses a custom parameter with a `-q main.q` value. If I change this to `-q my.q` (or whatever name) - it works.

**To Reproduce**
1. Execute 
```
pipe run -n 11111 \
    CUSTOM_PARAM '-q main.q' \
    -y -id 100 \
    -it m5.xlarge \
    -di library/centos \
    -cmd 'python $SCRIPTS_DIR/src/[main_file]'
```
2. Observed
```
Failed to fetch data from server. Server responded with message: Pipeline with requested id: '.q' was not found.
```

**Expected behavior**
Command shall fail with:
```
Failed to fetch data from server. Server responded with message: Pipeline with requested id: '11111' was not found.
```

**Comment by mzueva** [comment]
Seems to be related to https://github.com/pallets/click/issues/249

**Comment by mzueva** [comment]
@ekazachkova We need to change the generation of `pipe run` command on the server-side: pipeline run parameters shall be attached at the end of the command and shall be preceded by **"--"** chars.

It also would be great add a new line sign (**"\\"** for Linux and **"^"** for Windows) to each chunk of generated command.

**Comment by mzueva** [comment]
cherry-pick to release/0.15 beb66d138c02a30284aaa93781629eaa275448c6
