### ISSUE TITLE
WDL graph: scatter inputs don't display

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#113]
1. Create pipeline from WDL template
2. Open pipeline, select version
3. Click on GRAPH tab
4. Click "PROPERTIES" button
5. Click "+ ADD SCATTER"
6. Click on appeared scatter object
7. Click on "Inputs" collapsed header
8. Click "ADD" button
9. Enter for a new record: name, type (NOT ScatterItem, e.g. String), value (necessarily)
10. Click "Save" button
11. Enter commit message, click "Commit"
12. Click on scatter object
13. Click "PROPERTIES" button
14. Click on "Inputs" collapsed header

__*exp.*__: record added at step 9 is displayed at "Inputs" section
__*act.*__: record added at step 9 isn't displayed at "Inputs" section

**Comment by rodichenko** [comment]
@NShaforostov modifying scatter's input is forbidden, this case was fixed in #112 as well

**Comment by NShaforostov** [comment]
Checked
