### ISSUE TITLE
WDL graph: only one input with ScatterItem type is displayed after saving

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#114]
1. Create pipeline from WDL template
2. Open pipeline, select version
3. Click on GRAPH tab
4. Click "PROPERTIES" button
5. Click "+ ADD SCATTER"
6. Click on appeared scatter object
7. Click on "Inputs" collapsed header
8. Click "ADD" button
9. Enter for a new record: name, type (necessarily ScatterItem), value
10. Click "Save" button
11. Enter commit message, click "Commit"
12. Click on scatter object
13. Click "PROPERTIES" button
14. Click on "Inputs" collapsed header

__*exp.*__: 2 records are displayed at "Inputs" section and on graph
__*act.*__: only record added at step 9 is displayed at "Inputs" section and on graph

**Comment by rodichenko** [comment]
@NShaforostov this is correct behavior: scatters can and must have only 1 input of type 'ScatterItem'. Now you cannot change its type, or remove it, or add new inputs (fixed in #112 )

**Comment by NShaforostov** [comment]
Checked
