### ISSUE TITLE
Billing GUI issues

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1149]
**1.** User grid shall be sorted on Billing General page.
**To reproduce:**
1. Open Billing 
2. Select any Billing centre and check summary table for Users
**Actual result:** Users aren't sorted by any column
**Expected result:** Users are sorted by 'Spendings' column

**2.** Filter by All Users/Groups issue 
**To reproduce:**
1. Open Billing 
2. Type any symbol to 'All Users/Groups' filter field
3. Click outside filter field
4. Click to  'All Users/Groups' filter field again
**Actual result:** Field is empty but the list is filtered by previous value.
**Expected result:** Entered value is shown in the field or the list isn't filtered by previous value.

**Comment by rodichenko** [comment]
@maryvictol fixed (259f21858b9738767f578c8182572b3a3a54436f), could you please verify this issue?

**Comment by maryvictol** [comment]
**3**. Control 'All users/groups', period selector and calendar control aren't updated at returning back to the previous page.
**To reproduce:**
1) Open Billing
2) Select any User (or Billing center)/change period for the report
3) Click 'Page go back' button
**Actual result:** Info/charts are reverted back. Control 'All users/groups', period selector and calendar control aren't reverted to their previous values (so info/charts aren't corresponding controls).
**Expected result:** Control 'All users/groups', period selector and calendar control shall be reverted to their previous values.

**Comment by maryvictol** [comment]
The same behaviour (point 3) occurs for the Report type menu.

**Comment by rodichenko** [comment]
@maryvictol fixed by 32b9673651d8d47d8097f848d727263601458f3c, could you please verify this?

**Comment by maryvictol** [comment]
Verified and closed
