### ISSUE TITLE
Allow to add a description to the pipeline parameters

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1154]
**Background**
Once any "pipeline" matures - it gets a lot of configuration parameters. And it becomes quite hard to remember the purpose of each.
While it's possible to build a good set of docs, but switching between documentation page to the pipeline run form - takes time.
We'd need to add "in-place" help snippets to simplify the job run setup.

**Approach**
* Allow specifying a `description` field (optional) for each of the pipeline parameters in the `config.json`
* It shall not be processed anyhow by the backend (except accepting/storing/sending back)
* GUI shall display a "question" icon next to the parameters (in the `Configuration` and `Launch` forms), which have a `description` field defined

**Comment by sidoruka** [comment]
Shall be backported to `release/0.15`

**Comment by mzueva** [comment]
Done

**Comment by rodichenko** [comment]
@sidoruka done, backported to `release/0.15` (1d64f6467d337410f85d1f935700b501be8d624d)
