### ISSUE TITLE
GCP deployment - init_cloud_config shall handle "gcp" cloud provider

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#116]
1. At the moment `init_cloud_config` will fail if Cloud Pipeline is being deployed to the GCP environment
https://github.com/epam/cloud-pipeline/blob/0a61a159b0921955e4fa2f078bffe0be1e07490d/deploy/contents/install/app/install-utils.sh#L104
GCP's instance metadata retrieval and install environment configuration shall be added

2. Another thing to add is the resulting config validation in the `validate_cloud_config` function. Currently it will throw error when GCP is in use.
https://github.com/epam/cloud-pipeline/blob/0a61a159b0921955e4fa2f078bffe0be1e07490d/deploy/contents/install/app/install-utils.sh#L245
Add any relevant validation (in the same manner as `Azure` and `AWS`), some post-configuration staff can be also added there

**Comment by mzueva** [comment]
Done
