### ISSUE TITLE
AWS: Auto-scaled cluster child nodes are not started

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#1161]
**Describe the bug**

When the auto-scaled cluster was launched auto-scaled cluster child nodes are not started. **GrigEngineAutoscaling** run task hangs with the following message:

`Scaling step has failed due to Command 'pipe run --yes --quiet --instance-disk 20 --instance-type m5.large --docker-image [docker-registry]/library/centos:7 --cmd-template "sleep infinity" --parent-id 32233 --price-type spot --region-id 1 cluster_role worker cluster_role_type additional CP_CAP_SGE false CP_CAP_AUTOSCALE false CP_CAP_AUTOSCALE_WORKERS 0CP_DISABLE_RUN_ENDPOINTS true' execution has failed. Out: Err: Failed to fetch data from server. Server responded with message: Price type 'spot' is not allowed...`

**To Reproduce**
1. Open library
2. Create pipeline (from SHELL template)
3. Open created pipeline
4. Click "RUN" button
5. In an appeared page click on "Advanced"
6. Input valid values into the fields "Node type", "Disk (Gb)"
7. Set as "Cmd template" next command:

`qsub -b y -e /common/workdir/err -o /common/workdir/out -t 1:10 sleep 1d && sleep infinity`

8. Click on "Configure cluster"
9. Click on "Auto-scaled cluster"
10. Specify "1" into "Auto-scaled up to:" field
11. Click OK
12. Click "Launch" button
13. In an appeared pop-up window click "Launch" button

**Expected behavior**
In a few minutes, one child node is started. On "ACTIVE RUNS" tab in front of the previously-started run name "+" button appears. Child pipeline is being displayed by click on "+" button, this child pipeline has the number in "Parent run" field that is equal to the parent-run ID

**Screenshots**

![image](https://user-images.githubusercontent.com/23356251/84127297-c0aa2f00-aa47-11ea-83c8-d814408647f4.png)

**Environment:**
 - Cloud Provider: **AWS**
 - Version:  **0.16.0.5597.b30c1a864dd37718df87320381b43393f0636560**
 - Browser: **chrome**

**Comment by tcibinan** [comment]
@kamyshova My bad. I did enforce `centos` tool to use only on-demand instances and forgot to turn it off. Could you please check that now it works fine in aws dev environment.

Errored configuration looked like the following.

![image](https://user-images.githubusercontent.com/16464586/84128782-b9842080-aa49-11ea-96cf-e9a916bab0f6.png)

**Comment by kamyshova** [comment]
@tcibinan Fixed. Thank you!
