### ISSUE TITLE
GCP deployment - add GCP-specific configuration files

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#118]
For `Azure` and `AWS` specific configuration files exist. They define options, that are applicable only for those specific providers.
Located at: https://github.com/epam/cloud-pipeline/tree/develop/deploy/contents/install/cloud-configs

For GCP - another configuration directory shall be added (named by `$CP_GOOGLE` value).
Take a look at `Azure` and `AWS` configurations to get an idea what options shall be overriden for `GCP`.

At least the following files shall be present:
* `deploy/contents/install/cloud-configs/gcp/cloud-config` - which defines default FS types, VM sizes and others
* `deploy/contents/install/cloud-configs/gcp/cluster.networks.config.json` - defines template for the cloud network configuration

**Comment by mzueva** [comment]
Done
