### ISSUE TITLE
Selection destination folder modal for cloned pipeline is closed at attempt navigate to preview folder via header

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1182]
**Describe the bug**

**To Reproduce**
1. Create new or use existing pipeline located in any inner folder
2. Click gear icon and select Clone option
3. In the selection destination folder modal click on any preview folders hierarchy level in the header

**Actual behavior**
Modal for selection destination folder closed.

**Expected behavior**
Folders tree for selected folder should be shown.

**Environment:**
 - Cloud Provider: N/A
 - Version 0.16.0.5758

**Comment by rodichenko** [comment]
@maryvictol should be fixed by 443d49283c11f6d3e875d4ea3c0857f4e15f3a92

**Comment by maryvictol** [comment]
Verified and closed on Version: 0.16.0.5842
