### ISSUE TITLE
GCP deployment - implement region registration for GCP deployment

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#119]
`api_register_region` function will throw error if deployment is being done within GCP
https://github.com/epam/cloud-pipeline/blob/0a61a159b0921955e4fa2f078bffe0be1e07490d/deploy/contents/install/app/configure-utils.sh#L719

Corresponding handler shall be added to generate registration request and prepare any other GCP region-specific parameters

**Comment by mzueva** [comment]
Done
