### ISSUE TITLE
Allow to use the "original" ENTRYPOINT and CMD

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1191]
**Background**
At the moment, Cloud Pipeline allows running a tool using a command, which is specified explicitly. 
In certain cases, users would like to reuse the default command, which specified in the Dockerfile (ENTRYPOINT + CMD)

**Approach**
* GUI shall expose an additional checkbox "Use default" - next to "Start idle"
* If it is specified - API shall check the docker image and grab the `ENTRYPOINT + CMD`
* This `ENTRYPOINT + CMD` shall be passed to the container command

**Comment by rodichenko** [comment]
@sidoruka `Use default checkbox` added to Launch Form.

**Comment by rodichenko** [comment]
Hint added to the `use default command` checkbox; backported to `release/0.16` (0701cd53a5db3dcfbcb5f9e713c34181b1ae72fe)
