### ISSUE TITLE
GCP deployment - add corresponding instance type configuration to the demo items

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#120]
1. For all `spec.json` in https://github.com/epam/cloud-pipeline/tree/develop/workflows/pipe-demo/ngs add `"gcp": "<INSTANCE_TYPE>"` if that pipeline shall be supported for GCP

2. Once deployed - double check that:
- Folder templates generate valid storages and prefix in the project attributes (i.e. `gcp://`)
- Pipeline templates generate valid instance type in the `config.json`
- Docker images in the `Tools` section contain valid instance type

**Comment by mzueva** [comment]
done
