### ISSUE TITLE
Attempt to view permissions on a pipeline via the `pipe view-pipes` throws an error

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1216]
**Describe the bug**
When trying to view permissions on a pipeline via the `pipe view-pipes -r` command - the command execution fails.

**To Reproduce**
1. Start any tool
2. Click the SSH button at the "Run logs" page
3. In the appeared web-terminal page perform the command `pipe view-pipes <pipeline_name> -r`
4. See the error in the "Permissions" section:
![image](https://user-images.githubusercontent.com/45459424/87343007-e0f07080-c554-11ea-892a-e702e70f6011.png)

**Environment:**
 - Cloud Provider: AWS
 - Version 0.16.0.6021.92f042bb428c87482d818cafed1c43b3e9125769
 - Browser: N/A

**Comment by mzueva** [comment]
@NShaforostov Shall be fixed, could you please verify?

**Comment by NShaforostov** [comment]
@mzueva thanks! Verified.
