### ISSUE TITLE
GCP deployment - add GCS backend support for the docker registry

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#122]
Docker registry, when deployed to GCP, shall correctly handle pipectl's `-env CP_DOCKER_STORAGE_TYPE=obj` option

At the moment GCP deployment will fallback to the local FS backend:
https://github.com/epam/cloud-pipeline/blob/69f10dbec04a361edd94ae481194fd51d9e07abf/deploy/docker/cp-docker-registry/update_config.sh#L61

GCS support shall be added if the `$CP_CLOUD_PLATFORM` is `gcp` and [GCS driver](https://docs.docker.com/registry/storage-drivers/gcs/) shall be configured in this case

**Comment by mzueva** [comment]
Done
