### ISSUE TITLE
Different characters are used to display quotes for the same tool full description on details page and in search results info

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1236]
**Describe the bug**
Different characters are used to display single or double quotes for the same tool full description on details page and in search results info. It affects autotests.

**To Reproduce**
1. Go to 'Tools'
2. Select any Tool
3.  Add single or double quotes to Full Description
4. Open Search and enter Tool Name.
5. Check single or double quotes characters on details page and in search results info

**Expected behavior**
The same characters are used to display quotes for the same tool full description on details page and in search results info.

**Environment:**
 - Cloud Provider: N/A
 - Browser: chrome

**Comment by rodichenko** [comment]
@maryvictol fixed, could you please verify this issue?

**Comment by maryvictol** [comment]
Verified and closed
