### ISSUE TITLE
'Save' button shouldn't be active at opening Configuration page

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1243]
**Describe the bug**
'Save' button is activated for 1-2 seconds at opening Configuration page.

**To Reproduce**
1. Go to 'Library'
2. Open any Cnfiguration with filled required fields 

**Expected behavior**
'Save' button shouldn't be active at opening Configuration page

**Environment:**
 - Cloud Provider: N/A
 - Version: 0.17.0.6220
 - Browser: chrome

**Comment by rodichenko** [comment]
@maryvictol could you please verify this issue?

**Comment by maryvictol** [comment]
Verified and closed on Version: 0.17.0.7538

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (58f2ce2fdae92bc5ae002150e42deca93ba4acf0)
