### ISSUE TITLE
LONG_RUNNING notification shall respect the "paused" duration

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1244]
**Background**
At the moment, Cloud Pipeline's `LONG_RUNNING` notification is quite simple - it uses a difference between the job's `start` and `end` times.
As it was introduced before the `PAUSE/RESUME` operation - `LONG_RUNNING` notification does not exclude the duration, spent in a `PAUSED` mode.
So the users get lots of the emails event if the job is sitting in `PAUSED` state and does not introduce any extra costs.

**Approach**
* We shall include the same logic, as we have for the `price estimation` for the this notification
* When the notification makes a decision on the notification - it shall exclude the `paused` state duration (using the `runStatuses` field of therun) from the overall duration

**Comment by sidoruka** [comment]
Please backport to `release/0.16`

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.16` via 4465fc6a9a3a4d45e65effbf144251949d6acef6 and 66e4ec405f5b69bd8b53e8a1eb7e294d75db7763.
