### ISSUE TITLE
Billing: special role for viewing the full billing data

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1258]
**Background**
At the moment, only users with the **_ROLE\_ADMIN_** role has access to the Billing section and can view Platform's spendings data.
In some cases, it would be convenient that some non-admin users also have the full access to the billing info.

**Approach**
Let's add a new role to the predefined roles list - e.g. **_ROLE\_BILLING\_MANAGER_**.
If that role is assigned to the user - for him/her the Billing section becomes available. All possible filters/chart types/sorting and etc. shall become available too (as for admins now).

**Comment by sidoruka** [comment]
Please backport to `release/0.16`

**Comment by mzueva** [comment]
@rodichenko ROLE_BILLING_MANAGER was added

**Comment by rodichenko** [comment]
@mzueva thank you!

**Comment by NShaforostov** [comment]
@rodichenko I've tried to verify.
For platform in general/for a specific billing center all forms are displayed correctly.
But I can't select any user in the corresponding search field and view his/her spendings. When I try to search any user (even myself) - nothing is being found. Is it correct behavior?

**Comment by rodichenko** [comment]
@NShaforostov @mzueva @sidoruka we're receiving `Access is denied` response for `GET` `/users` for such user (with **ROLE_BILLING_MANAGER** role assigned). We need either a) allow such users to fetch all users via `GET` `/users` or b) create a separate API method for fetching users list for billing managers

**Comment by sidoruka** [comment]
Let's have two new methods, which provide only general info for users and regions with a bare minimum information available to `ROLE_USER`

**Comment by mzueva** [comment]
@sidoruka @rodichenko We've added two API methods available to all users:
- GET /users/info
- GET /cloud/region/info

These methods return limited number of fields, if client needs some additional fields - let me know.

**Comment by rodichenko** [comment]
@sidoruka @rodichenko @NShaforostov #1326 should fix https://github.com/epam/cloud-pipeline/issues/1258#issuecomment-677938995 and https://github.com/epam/cloud-pipeline/issues/1277#issuecomment-678346769

**Comment by NShaforostov** [comment]
@rodichenko Verified.
Now, all works correctly

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (3e26b88c653eeb3d8783bec66bcca8d5cd0ab5ac)

**Comment by mzueva** [comment]
backported to release/0.16 via b78279ced11882a603f57a1f4de295162482234b d4eb3a09bb6150ef841795d3be8eca193468b441
