### ISSUE TITLE
Billing: base access to the billing info for general users

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1259]
**Background**
At the moment, only users with the **_ROLE\_ADMIN_** role has access to the Billing section and can view Platform's spendings data.
When #1258 will be implemented, non-admin users (_but with special role_) also can view full Platform's billing info.
But for general users, some information - about their own spending - could be useful too.
Any Platform user should be able to view Billing info - in certain limited view.

**Approach**
- if the user has the **_ROLE\_ADMIN_** role - he/she has the full access to the Platform's Billing (currently implemented)
- if the user has the special role - he/she also has the full access to the Platform's Billing (will be implemented, see #1258 for details)
- for other users Billing section shall become also available but with the following restrictions:
   - all showing charts shall display only spendings of the current user (there shouldn't be the ability to view spendings for whole platform/billing center(s)/group(s)/other user(s))
   - button "Configure discounts" shall be disabled

**Comment by sidoruka** [comment]
Please backport to `release/0.16`

**Comment by rodichenko** [comment]
@NShaforostov @sidoruka GUI part implemented (#1302), this also covers #1258

**Comment by NShaforostov** [comment]
@rodichenko 
I've tried to verify. Works well.
A minor note: could you hide the "Billing centers (TOP 10)" chart from the General billing page? This chart will be always empty for non-admin/non-billing manager users.

**Comment by rodichenko** [comment]
@NShaforostov https://github.com/epam/cloud-pipeline/issues/1259#issuecomment-677924201 implemented (#1315)

**Comment by NShaforostov** [comment]
Verified.
Now, all works nice

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (3e26b88c653eeb3d8783bec66bcca8d5cd0ab5ac)

**Comment by mzueva** [comment]
backported to release/0.16 via 827e11bc8c1d9afa463a4c12543735df9eafb68c
