### ISSUE TITLE
Shared endpoint for `anonymous` users is being opened from the second time

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1265]
**Describe the bug**
It's refers to #1037 functionality.
When an `anonymous` user opens a new browser window, pastes into the address bar received hyperlink of the shared endpoint and tries to open the page - he/she gets the Platform's "Access denied" page.
Then, if user pastes received hyperlink again into the address bar and tries to open the page in the second time - it's being opened correctly.
From such "second" time the hyperlink is being opened well and correctly (e.g. in a new tab).
But this case repeats if the user will close and reopen the browser.

**Environment:**
 - Cloud Provider: AWS
 - Version 0.17.0.6339

**Comment by sidoruka** [comment]
Fix shall be backported to `release/0.16`

**Comment by sidoruka** [comment]
Fixed via e3fb461b74612dd884bfd2137e8705015ac46c03 16375976861841bfedebf5b8b550aa9edef39e1f 0a0d75c583b833db8dc4b2c2ba5fbd359e7066f6
