### ISSUE TITLE
Switch docker storage driver from overlay2 to btrfs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1275]
**Background**
At the moment, Cloud Pipeline uses the following filesystems:
* Host OS - `btrfs` (to support FS autoscaling)
* Host Docker - `overlay2`
* DIND - `overlay2`

The `overlay2 over btfs` causes performance issues for the recursive FS operations. E.g.

```
# Generate sampleset (with multi-level directory hierarchy - things get much worse)
mkdir /opt/test
for i in $(seq 1 100000); do
  echo $i > /opt/test/$i.txt
done

# Execute chmod for the generated files
time chmod 777 /opt/test -R

# Results overlay2 over btrfs 
0m5.585s

# Results btrfs only
0m0.554s
```

**Approach**
* We need to switch the `Host docker` and `DIND` to `btrfs`
* This might cause certain issues with the resource monitoring: CAdvisor can't provide container-level disk utilization for the `btrfs`, so we shall switch that to the node-level metrics, which work fine:
  * Resource monitoring
  * Commit/Pause
  * `Whatever else` might be affected by this change

**Comment by sidoruka** [comment]
Shall be cherry-picked to `release/0.16`

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.16` via 07ff601511df17088fcced982eba0aa597b1cc74.
