### ISSUE TITLE
Add "Export to CSV" to all the Billing sections

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1281]
**Background**
At the moment, Cloud Pipeline allows to export the billing data into the CSV via the `General` section only.
We'll need to add this export feature to the "Storage" and "Compute" sections.

The exported tables shall be of the same structure as used for the GUI reports

**Comment by sidoruka** [comment]
Please backport to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.16` (7ec9c0082718ef2638b1ff9262c9dc69bf59b97a)

**Comment by NShaforostov** [comment]
Verified

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov `Volume`, ` Billing Center` and `Type` columns (#1278) are also exported (21f78de4170f1aae0cc94149694cad872d45d16b) - backported to `release/0.16` (1a9444c412a3c5fdabbc71cb9fb077d1253405eb)
