### ISSUE TITLE
Allow to force the cluster master to a specific price type

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1283]
**Background**
At the moment, Cloud Pipeline allows the user to choose if the cluster master node can be a `spot`/`pvm` or `on-demand` instance.
While spots are ok for the worker nodes, as they can be recreated (e.g. #1155) - master node failure will terminate the whole cluster.
To make things easy for the end-users, let's introduce an optional restriction on the `spots`/`pvms` usage for the master nodes.

**Approach**
* API: Add `cluster.allowed.price.types.master` string preference (default: "spot,on_demand", visible: true)
* This parameter shall work as other `cluster.allowed.price.types*` preferences: GUI and API shall allow only one of those to be used to run a cluster master
* GUI shall display only that `price type(s)` in the drop-down, when the cluster run is being configured
* This parameter shall be global, no need to propagate this to the group/user level

**Comment by sidoruka** [comment]
Backport this to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka GUI part implemented #1317

**Comment by sidoruka** [comment]
@NShaforostov please verify (once API is merged by @mzueva )

**Comment by NShaforostov** [comment]
Verified. Works well

**Comment by rodichenko** [comment]
@NShaforostov @sidoruka backported to `release/0.16` (8ddc0ffa3249439c8497799e4eb654bf7b7578c3)

**Comment by mzueva** [comment]
backported to release/0.16 via 9242b8c36cd29a1717deba0f0fa772850a0e0172
