### ISSUE TITLE
Codec error using the pipe tool

### ISSUE THREAD

**Issue by Fred-Fleche** [epam/cloud-pipeline#1292]
I have an issue using pipe from a Linux VM instance located in GCP. Indeed, using “storage ls” I was able to see the content of my folder located within AWS embedded in Cloud Pipeline but now I have an error message that seems related to python script that may be pipe is build with.

frederic_fleche@frederic-fleche-notebook:~$ pipe storage ls -l s3://ngstraining
Error: 'ascii' codec can't decode byte 0xc2 in position 24: ordinal not in range(128) 

Do you have any suggestion about the origin of this error message which is not self explicit ?

**Comment by sidoruka** [comment]
Hi @Fredon78, sorry to hear that.
We'll review and let you know why this thing might happen.

@SilinPavel, please take a look

**Comment by sidoruka** [comment]
At the moment, "pipe" CLI for Linux uses Python2, which has `ascii` default encoding.
This causes different issues with the users locales, like this one:
```
Error: 'ascii' codec can't decode byte 0xc2 in position 24: ordinal not in range(128)
```

@mzueva, let's try the following options:
* If it is feasible - let's introduce another `configure` option to override the `ascii` with `utf-8` (e.g. `--codec ascii/utf-8/etc.`). The default value shall be kept as `ascii`
* If this does not work or produces side-effects - let's use `Python3` to build the Linux distribution, same done for Windows already

**Comment by sidoruka** [comment]
Fixed and confirmed
