### ISSUE TITLE
UI build: enable caching

### ISSUE THREAD

**Issue by rodichenko** [epam/cloud-pipeline#131]
Webpack is now configured to generate separate output files (*.js, *.css) for *vendors* code and for *cloud-pipeline* code. These files are generated with *content-hash* in names, e.g. *main.eff5aed366afd7148bb7.chunk.js*, *vendors.b2991432dc35a8d6edd2.chunk.js*.

Such configuration helps us to reduce user's traffic and speed up UI application loading. Also, if some vendor's library changes (version change, for instance), only *vendors*-related js file will be changed, and if cloud-pipeline client code changes corresponding js file will be changed too.

To reduce user's traffic we should enable caching. 
**Please configure Tomcat to use caching for source files (*.js, *.css)**.

**Comment by sidoruka** [comment]
@rodichenko , please put some expected numbers here for a current GUI version, so will be able to verify.
E.g.:
- Vendor JS: XXX Kb
- GUI JS: XXX Kb
- Other JS: XXX Kb

**Comment by rodichenko** [comment]
@sidoruka at the moment, we have the following measurements (after **gzip**):

**JavaScript**:
* `Vendor JS`: ~1.7 MB
* `GUI JS`: ~ 320 KB
* `Runtime JS`: ~700B (used to bundle `gui` and `vendor` together)
**Total: ~2 MB**

**Styles**:
* `Vendor styles`: ~80 KB
* `GUI styles`: ~17 KB
**Total: ~100 KB**

**Comment by sidoruka** [comment]
@rodichenko take a look at two builds which didn't change anything with the JS part:
* https://travis-ci.org/epam/cloud-pipeline/jobs/520877454#L273
* https://travis-ci.org/epam/cloud-pipeline/jobs/520875413#L273

`build/static/js/vendors.*.chunk.js` has different hash value and results into extra 1.7Mb download, but nothing shall be changed there.

**Comment by sidoruka** [comment]
> @rodichenko take a look at two builds which didn't change anything with the JS part:
> 
> * https://travis-ci.org/epam/cloud-pipeline/jobs/520877454#L273
> * https://travis-ci.org/epam/cloud-pipeline/jobs/520875413#L273
> 
> `build/static/js/vendors.*.chunk.js` has different hash value and results into extra 1.7Mb download, but nothing shall be changed there.

Fixed in 7aad7149adda811041e8a7c6a53cfa2e8bc60e4c

**Comment by sidoruka** [comment]
@mzueva I've noticed that current cache duration is set to 24 hours.
Could you please:
- Introduce a corresponding setting to the `application.properties`
- If not set in the config file - use one month as a default

**Comment by mzueva** [comment]
@sidoruka `static.resources.cache.sec.period` property added
