### ISSUE TITLE
Unable to list more than 1000 files in the S3 bucket

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1312]
**Describe the bug**
* The bucket contains 2k+ files
* User can list **all** the files in the GUI
* User can list **only 1000** files via the `pipe storage ls -l --all` command
* User can list **only 1000** files via the `pipe storage ls -l --page 2000` command
* User can list **only 1000** files via the `pipe storage mount -b && ls -l` command

**Environment:**
 - Cloud Provider: [e.g. AWS]
 - Version: 0.16.0.6523

**Comment by sidoruka** [comment]
Please backport the fix to `release/0.16`

**Comment by mzueva** [comment]
@sidoruka cherry-pick 7168b8fb49e53ef853104880493de853899843bb
