### ISSUE TITLE
`pipe storage ls` paging doesn't work correctly with folders

### ISSUE THREAD

**Issue by ekazachkova** [epam/cloud-pipeline#1339]
**Describe the bug**
The `pipe CLI` storage listing works incorrectly with `--page` option with S3 provider.

**To Reproduce**
1. Create test storage `s3://test-data-storage` and upload several items (e.g. 2 files and 3 folders):
```
file1
file2
folder1/
folder2/
folder3/
``` 
2. run `pipe storage ls s3://test-data-storage/ --page 2`

**Actual behavior**
`file1           file2           folder1/           folder2/`

**Expected behavior**
`file1           folder1/`

**Environment:**
 - Cloud Provider: AWS
 - Version 0.17.0.6626.df38180d3491381a86e5e4a967cafbaa3a81336c

**Additional context**
This bug also affected listing with versions

**Comment by mzueva** [comment]
cherry-picked to `release/0.16` 59b7723d9785b18ba9c07a8f39ab3f8d991a27c0

**Comment by NShaforostov** [comment]
Verified. Works well.
Were tested:
- pagination for files/folders in the storage
- pagination for file versions

**Comment by NShaforostov** [comment]
**Test cases** were created by cf7a0e602857ea5df8b7b78363eb0ab8c16aa9d1 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Data_storages/1339_pipe_storage_ls_paging).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1605.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.DataStoragesCLITest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
**Docs** were updated via #1855.
