### ISSUE TITLE
Azure: Failure on creating a folder with a name of an existing file

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#135]
Version: `0.15.0.450.137a0f04bcbe6427eefb3a576bb9438e2ec98bf8`.

Suppose the bucket has a file with `file.txt` name. If user try to create a folder with `file` or `file.txt` name then one of the following errors are shown `Error: azure item 'file' already exists.` or `Error: azure item 'file.txt' already exists.`.

**Comment by mzueva** [comment]
@tcibinan Please, check overall approach to testing file/folder existence in Azure Blob Storage.
