### ISSUE TITLE
Unable to view pipeline sources for previous draft versions

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#1353]
**Describe the bug**
Pipeline "Documents" and "Code" tabs always show content of the last "draft" version of pipeline, even if one of previous versions is specified in the url.

**Environment:**
 - Cloud Provider: AWS
 - Version 0.17.0.6653.90702086719ae72997860f3537634902bb0cb134
 - Browser: Chrome

**Comment by mzueva** [comment]
cherry-pick to `release/0.16` 417138f7f26f6bab26cb309f8967fd9f75ac015e

**Comment by NShaforostov** [comment]
Verified. Works correctly

**Comment by NShaforostov** [comment]
Test case was created by 882543f8703af7d789be7f3620f64b71aa64e282 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Pipeline_library/Pipeline_details/1353.md).

**Comment by NShaforostov** [comment]
**Docs** were updated via #1855.

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1884.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.PipelineLibraryTest.html) (for `AWS`).
