### ISSUE TITLE
Add support for the Kubernetes cluster setup

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1361]
**Background**
At the moment, Cloud Pipeline offers a number of cluster schedulers to be configured:
* SGE
* Slurm
* SPARK

But now we have a number of use cases, that required a Kubernetes cluster to launch the processing jobs. It shall added in the same manner as the existing schedulers.

**Approach**
* Add the Kubernetes static cluster setup if the `CP_CAP_KUBE` system parameter is set to `true`
* Add the `Enable Kubernetes` option to the list of the available schedulers in the GUI:
![image](https://user-images.githubusercontent.com/20998291/91996768-0a9e6a80-ed42-11ea-8518-a3714128e368.png)

**Comment by sidoruka** [comment]
@rodichenko , please implement the (2) action item

**Comment by rodichenko** [comment]
@sidoruka GUI part implemented (#1362)

**Comment by sidoruka** [comment]
@rodichenko please add the following logic as well:
If the "Kubernetes" cluster is selected, the following system parameters shall be added as well:
* `CP_CAP_DIND_CONTAINER`
* `CP_CAP_SYSTEMD_CONTAINER`

And backport to `release/0.16`

**Comment by rodichenko** [comment]
> @rodichenko please add the following logic as well:
> If the "Kubernetes" cluster is selected, the following system parameters shall be added as well:
> 
> * `CP_CAP_DIND_CONTAINER`
> * `CP_CAP_SYSTEMD_CONTAINER`
> 
> And backport to `release/0.16`

@sidoruka done (29fc5359698d353c835220bb48ddd772f1fd02d2), backported to `release/0.16` (294d8b6da2230ee51bfef50aa8516850336b91fc)
