### ISSUE TITLE
Tool settings save button is always active

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#137]
Version:  `0.15.0.450.137a0f04bcbe6427eefb3a576bb9438e2ec98bf8`.

Some tool's settings `SAVE` button is always in `enabled` state even if settings wasn't changed.

**Comment by rodichenko** [comment]
@tcibinan fixed, re-check please

**Comment by tcibinan** [comment]
Looks like it helped. Thanks!
