### ISSUE TITLE
Azure: Pipeline from WDL template fails

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#141]
Pipeline created from WDL template stucks on `WaitForNode` and fails in the end with the following error.

![image](https://user-images.githubusercontent.com/16464586/56148452-fd4cd880-5fb2-11e9-80eb-e459b3e4f4d7.png)

**Comment by sidoruka** [comment]
Works now. Dev environment configuration issue, it contained old cromwell image.
Now docker images are updated if they were changed via 71bceeb4146a75194a02bcc75ed1580bcdce5579
![image](https://user-images.githubusercontent.com/20998291/56224015-8a596580-6077-11e9-8996-862db6a5e727.png)
