### ISSUE TITLE
Tool group cannot be deleted until all child tools are removed

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#144]
Observed using the latest `
Version: 0.15.0.457.17d8d8e095c3ae0db97c99a5a4d3994254b76a99`

If there is a tool group in the registry, which is not empty (i.e. contains 1+ tools) - an attempt to delete it throws `SQL error`.
It works fine if the child tools are dropped beforehand.

An expected bahvior is that tools are removed automatically and then a whole group is deleted as well.

**Comment by mzueva** [comment]
@sidoruka we shall always drop all tools when a tool group is deleted or introduce a `force` flag?

**Comment by sidoruka** [comment]
Sure, let's add:
- `force` option to the API
- @rodichenko will add a `Delete child tools` confirmation checkbox to the group deletion dialog, in the same manner as used for the folder deletion
![image](https://user-images.githubusercontent.com/20998291/56358404-2a81cc80-61e7-11e9-846b-87eeefa778f5.png)
