### ISSUE TITLE
Display the CP_CAP_LIMIT_MOUNTS in a user-friendly manner

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1447]
**Background**
At the moment, Cloud Pipeline displays the run-enabled data storages as a list of IDs of the `CP_CAP_LIMIT_MOUNTS`.
The users request to make this more "friendly":
* Show the data storage name instead of the ID
* Name shall be shown a hyperlink, pointing to the data storage in the Cloud Pipeline GUI
* If a storage is "sensitive" - it shall be highlighted appropriately

**Comment by sidoruka** [comment]
Shall be backported to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka `CP_CAP_LIMIT_MOUNTS` is displaying in a user-friendly manner now (#1456)

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.16` (b9e2e8dfd9650910faa88b1bc014ac6e9701ef2b)

**Comment by NShaforostov** [comment]
Verified

**Comment by NShaforostov** [comment]
**Docs** were updated via #1516

**Comment by NShaforostov** [comment]
**Test case** was created by 826f75cd2d8021362181ea4bb20d9dffaec655b5 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Run_tools_in_sandbox/Limit_mounts/1447.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1566.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.LaunchLimitMountsTest.html) (for `AWS`).
