### ISSUE TITLE
Allow to transfer objects between AWS regions using pipe cp/mv commands

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#1469]
**Background**
At the moment `pipe cp/mv` commands allow to transfer objects only within one AWS region. It would be useful to allow object transfer between regions since AWS provides such functionality.

**Comment by mzueva** [comment]
@sidoruka backported to `release/0.16`

**Comment by ekazachkova** [comment]
@sidoruka  There are some benchmarks for this feature. The tests were performed with file 1.06 GB.

| case  | aws s3 cp | pipe storage cp |
| ------------- | ------------- | ------------- |
| one region (`eu-central-1`)  | 4 sec  | 7 sec |
| between regions (`eu-central-1` to `us-east-1`)  | 57 sec  | 58 sec |

**Comment by NShaforostov** [comment]
Verified. Works well

**Comment by NShaforostov** [comment]
**Docs** were updated via #1516

**Comment by NShaforostov** [comment]
**Test case** was created by af3dc801a3a64a2b152308975e1c3f2e8f3dac1a and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Data_storages/1469.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1574.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.DataStoragesCLITest.html) (for `AWS`).
