### ISSUE TITLE
At saving Tool Settings after uncheck 'Allow sensitive storages' option 'Save' button becames disabled after 2nd click only.

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#1476]
**Describe the bug**
At saving Tool Settings after uncheck 'Allow sensitive storages' option 'Save' button becames disabled after its second click only.

**To Reproduce**
1. Open any Tool with checked 'Allow sensitive storages' checkbox
2. Open 'Settings' tab
3. Uncheck 'Allow sensitive storages'
4. Click 'Save' button
5. See that 'Save' button becames disabled and again active after that

**Expected behavior**
'Save' button should remain disabled.

**Environment:**
 - Cloud Provider: [AWS]
 - Version [ 0.17.0.7453]

**Comment by rodichenko** [comment]
@maryvictol should be fixed by 10c534380b262d373e55f0d3910ea9d2e8dfa050

**Comment by maryvictol** [comment]
Verified and closed on Version: 0.17.0.7538

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (15d3d138a4652515dbf01eb7b9c9250ac8156b1f)
