### ISSUE TITLE
Warn the user, if there is a risk of OOM due to the number of the object storage mounts

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1480]
**Background**
At the moment, if the user has 100+ object storages available - they are mounted to the jobs, by default. When using rather small nodes - this leads to the OOM errors, as the 100+ `mount` processes may oversubscribe the memory.

Even if we greately optmize the memory consumption - the user may still face such issues, if the number of object storages grow. So we need a sort of hard-limit to warn the user if there is risk of OOM.

**Approach**
* Introduce a preference `storage.mounts.per.gb.ratio` (int, nullable)
* Perform calculation of the "safe" `storages per Gb RAM` ration (e.g. 5 storage per Gb) and make it a default value for the `storage.mounts.per.gb.ratio` preference
* When launching a job - we shall check if the user's available **object storages** and the selected instance type do not exceed the `storage.mounts.per.gb.ratio`
* If it's exceeded - the user shall be warned with the following wording and asked to reduce a number of mounts via the `Limit mounts` feature
* If the `storage.mounts.per.gb.ratio` is not set - no checks shall be performed (current behavior)

**Comment by rodichenko** [comment]
@sidoruka @mzueva I think we can implement OOM check without extra API methods:
* GUI fetches `storage.mounts.per.gb.ratio` preference;
* If it is presented, GUI checks if `instance's RAM` * `storage.mounts.per.gb.ratio` <= number of object storages associated with the run;
* If it is **true**, GUI displays a warning.

**Comment by SilinPavel** [comment]
@sidoruka regarding `storage.mounts.per.gb.ratio` it is actually can be empty now only for the first time, if this preference value will be changed after that it couldn't be updated with empty value. This is because of type validator of such preferences, for now for all `IntPreference` we checked that it is numeric this obviously means not null, we could change this logic to allow null value for Numeric Preferences on Type level, but check that it is not null where it is needed with specific preference validator.

**Comment by NShaforostov** [comment]
Verified. Works well

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (74342232696a308ee2caec7c4127d8e92723b65c)

**Comment by SilinPavel** [comment]
@sidoruka backported to `release/0.16` (1f75d1e3c181919b37249874e8e12c6fe78bdc9a)

**Comment by NShaforostov** [comment]
**Docs** were updated via #1516

**Comment by NShaforostov** [comment]
**Test case** was created by fc2e15f87e64202177198a7a5e61476285204eb5 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Run_tools_in_sandbox/Limit_mounts/1480.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1566.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.LaunchLimitMountsTest.html) (for `AWS`).
