### ISSUE TITLE
Incorrect behavior of the groups deletion in the settings

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#1491]
**Describe the bug**
Currently, the deletion of groups in settings works incorrectly. The confirmation of the deletion popup is overlapped by the edit popup.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'USER MANAGEMENT' tab
3. Click on 'Groups' tab
4. Click on a delete button opposite a group
5. See an error

**Expected behavior**
The confirmation of the deletion popup is visible and available.

**Environment:**
 - Cloud Provider: **AWS**
 - Version **0.17.0.7555**
 - Browser: **chrome**

**Comment by kamyshova** [comment]
Fixed

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (acf1bcaa4854af021e6cd9e939c7281e028a19e4)
