### ISSUE TITLE
Instances of Metadata entity aren't being correctly sorted

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#150]
1. Select "Metadata" object at the library tree
2. Click on metadata entity, open table with instances of the entity
3. Click on "ID" column header
4. Click on "ID" column header

__*Exp.*__: after step 3 instances are sorted by ascending order, after step 4 instances are sorted by descending order
__*Act.*__: in both cases, instances aren't sorted correctly

**Comment by rodichenko** [comment]
@NShaforostov @sidoruka we're using server-side sorting due to metadata' pagination

**Comment by mzueva** [comment]
@rodichenko 
It seems that sorting is implemented correctly on the sever side, problem is with `orderBy.field` value that is passed in metadata query. Server supports two types of sorting:
1. Predefined fields `["ID", "NAME", "EXTERNALID", "PARENT.ID", "CLASSENTITY.ID", "CLASSENTITY.NAME"]` corresponding to a fixed fields of any MetadataEntities
2. Custom `data` fields that are returned in a `data` field for entity

Note that GUI shows `EXTERNALID` as `ID` in th metadata table.
Currently I observe that when I try to sort by `ID` field on UI, that corresponds to actual `EXTERNALID` field, client sets `orderBy` clause as `"orderBy": [
    {
      "field": "ID",
      "desc": false
    }
  ]` which corresponds to sorting by `ID` not `EXTERNALID`. This the reason why sorting seems broken on the GUI.

**Comment by NShaforostov** [comment]
@rodichenko When we click on the header the first time - down-arrow appears and descending order is expected, but the column is being ordered by ascending mode. When we click on the header the second time - up-arrow appears and ascending order is expected, but the column is being ordered by descending mode. Need to change: down-arrow=descending mode, up-arrow=ascending mode.

**Comment by rodichenko** [comment]
@NShaforostov yes, sorting indicators were wrong. Fixed by 2ef31cf

**Comment by NShaforostov** [comment]
Checked
