### ISSUE TITLE
Bad layout in Groups/Roles membership view

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1504]
**To Reproduce**
1. Load any Group or Role with a 5+ users
2. Scrollbar is shown even if there is a plenty of space below
3. Popup is much smaller than the same one for the user

**Expected behavior**
* No scroll bar, if the list fits the popup height. Or a scrollbar, that is shown if the list overflows the available height
* Popup height/width shall be identical to the user's details popup

**Screenshots**
![image](https://user-images.githubusercontent.com/20998291/96565983-b76e8000-12cd-11eb-849e-e1b0b4e78424.png)

**Comment by sidoruka** [comment]
Backport to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka, @maryvictol  layout fixed (a199d1e97da786da34930305d6b23008eb06fc82)

**Comment by NShaforostov** [comment]
Verified

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (e624da4285a37b9017386302866a7a460986267a)

**Comment by NShaforostov** [comment]
Docs were updated via #1516

**Comment by NShaforostov** [comment]
Test case for **manual** testing was created by 24db3074ac5101e098262511752fce4990aec01a and located [here](https://github.com/epam/cloud-pipeline/blob/test_cases_updates/docs/testcases/UI/Layouts/1504.md).
