### ISSUE TITLE
Bad layout in the Billing Reports - discounts links

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1505]
If the whole header menu does not fit the screen width - the links overflow the regions selector
![image](https://user-images.githubusercontent.com/20998291/96566207-f3a1e080-12cd-11eb-9e5e-5af04ee17790.png)

**Comment by sidoruka** [comment]
Backport to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka layout fixed (ae6eff35047f0846167e4bc11bf85d2fc08c227e), backported to `release/0.16` (c3c9ec05d2cce3a0dbeec52b67a3ce4af5ea4ebe)

**Comment by NShaforostov** [comment]
Verified

**Comment by NShaforostov** [comment]
Docs were updated via #1516

**Comment by NShaforostov** [comment]
Test case for **manual** testing was created by fb621a5390d0d06c9dcc1c3a2666a25c5315843e and located [here](https://github.com/epam/cloud-pipeline/blob/test_cases_updates/docs/testcases/UI/Layouts/1505.md).
