### ISSUE TITLE
Repositories for storages and pipelines

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1506]
**Background**
There are several ways for users to find the appropriate storage/pipeline object in the Cloud Pipeline Platform - manually via the Library, using the Search ability or via the corresponding panels of the main Dashboard.

It would be convenient to get all lists of the storages/pipelines accessible to the user in one place with short info about each object and easy access to it (like for tools now).

**Approach**
Create two new "repositories" in the Library - separately for storages and pipelines:
- each "repository" shall display the full list of the corresponding objects accessible by the current user
- for each pipeline in the "repository" shall be shown:
   - pipeline name
   - pipeline description
   - owner
   - the "Run" button if the pipeline is available for execute for the user
   - if the user clicks the pipeline in the list - its page should be opened
- for each storage in the "repository" shall be shown:
   - storage alias
   - storage description
   - owner
   - Cloud Region/Provider icons for multi-deployments
   - if the user clicks the storage in the list - its page should be opened

**Comment by rodichenko** [comment]
@NShaforostov implemented, backported to `release/0.16`

**Comment by NShaforostov** [comment]
Verified, works well

**Comment by NShaforostov** [comment]
Test cases were created by 2758afeaa72a8d5537f97fa9e43a7b0011573446 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Pipeline_library/Folder_navigation/1506_pipelines_and_storages_repositories).

**Comment by NShaforostov** [comment]
Docs were updated by 056601ebfbf090400b8d38439a84860ea4b49a4e.

**Comment by NShaforostov** [comment]
e2e-tests were implemented via #1524 .

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.PipelinesAndStoragesRepositories.html) (for `AWS`).
