### ISSUE TITLE
Pause button is missing for non cluster SGE runs

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#1512]
**Describe the bug**

Currently one cannot pause non cluster run with sge capability being enabled.

**To Reproduce**

1. Launch `ubuntu:latest` with enabled `CP_CAP_SGE` system parameter.
2. Wait for `ssh` link to appear on the run page.
3. See that the `pause` button is missing.

**Expected behavior**

Pause button should not be available for only cluster and autoscaling cluster runs. Single node sge runs should be able to be paused.

**Environment:**
 - Version 0.16.0.7686.916eb7d53a870a50e42b14f4c3a880f29348193a

**Comment by rodichenko** [comment]
@tcibinan @sidoruka @NShaforostov `pause` button is now available for non-cluster runs with enabled `CP_CAP_SGE` parameter (e5a09bb9e997474106554834b92ec22b0c2b85fd)

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (75442f3e638e4f01d964c0ec292690144c714615)

**Comment by NShaforostov** [comment]
**Verified** [Smoke Testing]:
1. Launched `ubuntu` tool with enabled `CP_CAP_SGE` system parameter.
2. Opened the launched run page.
3. Have waited when **SSH** link appeared.
4. Checked that the **PAUSE** button had appeared.
5. Pressed the **PAUSE** button.
6. Have waited for the `PAUSED` status of the run appeared.
