### ISSUE TITLE
Support custom node images for runs

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#1517]
**Background**

Currently Cloud Pipeline allows to run instances using two default node images. One node image for all CPU instance types and other for GPU ones.

Nevertheless there are cases than some of the tools or pipelines require special node images. For example, some tool may require specific nvidia driver version which default GPU node image doesn't have.

**Approach**

To resolve all possible node image incompatibility issues support for custom node images has to be introduced. If custom node image is specified for pipeline, tool or just a single run then cloud instance with the required node image has to be either instantiated or reassigned.

**Comment by NShaforostov** [comment]
Verified. Works well.
Were tested:
- node image redefinition for pipelines at `AWS`, `Azure`, `GCP` stands
- reuse of the nodes that were "redefined"
- usage of the default nodes after disengagement of the nodes that were "redefined"

**Comment by NShaforostov** [comment]
**Test cases** were created by 797d9dfad4e1e479d7b862fc4554adf09f1116ed and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Pipeline_library/Pipeline_configuration/1517_custom_node_images_for_runs).

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.16` via 8a6e003c8d916b987d78873f9a5da872bcd86a64 and bfd3a4601f6ec288ca8bd78a045160c93ef66848.

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1632.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.CustomNodeImagesForRunsTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
**Docs** were added via #1896.
