### ISSUE TITLE
Metadata entities shall support IDs autogeneration

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1569]
**Background**
At the moment format of metadata import **csv** requires that entity unique ID shall be specified in the first column. For some cases it would be helpful to generate ID during import.

**Approach**
- If ID is not provided in the first column of metadata import **csv** it shall be generated using UUID4 format
- If `externalId` is not specified in `POST /metadataEntity/save`  method it shall be generated using UUID4 format

**Comment by mzueva** [comment]
@sidoruka backported to `release/0.16` (47796ba2ebbfa8e39676d8bcab81ba2edf03e582)

**Comment by NShaforostov** [comment]
Verified.
Works well.

Were tested:
- automatic IDs generation for upload Metadata entities from external file
- automatic IDs generation for manual Metadata entities creation via the GUI
- manual ID specifying during Metadata entities creation

**Comment by NShaforostov** [comment]
**Test case** was created by 646d34f311c02added79f7406e0ac006b2ee9ea5 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Sample_Processing_Module/1569.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1759.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.SampleProcessingModuleTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
**Docs** were updated via #1855.
