### ISSUE TITLE
Metadata entities shall display the "Added date" field

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1589]
**Background**
Metadata entities shall fill and store `createdDate` field.

**Approach**
From code prospective `MetadataEntity` already has `createdDate` field but it is not used. It shall be added to DB schema and handled properly.

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to `release/0.16` (17ed55d802baeb70df45da6db3b5e0e41e7056e3)

**Comment by NShaforostov** [comment]
Verified.
Works well.

Were tested:
- automatic displaying of the created date for the uploaded Metadata from the file
- automatic displaying of the created date for the Metadata instances added manually

**Comment by mzueva** [comment]
@sidoruka backported to `release/0.16` (4c05009f4de78a1def7ae8069e5080db4a41c41e)

**Comment by NShaforostov** [comment]
**Test case** was created by 1e2f033178c8f47a535a04a398bfe7ebc191db43 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Sample_Processing_Module/1589.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1759.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.SampleProcessingModuleTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
**Docs** were updated via #1855.
