### ISSUE TITLE
Add proper metadata entity creation error on duplicated external ids

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#1613]
**Describe the bug**

Currently if metadata entity is created with external id which already exists then some SQL error is shown.

**To Reproduce**

1. Create metadata entity with external id using GUI
2. Create another metadata entity with the same external id using GUI
3. See that the error message is not descriptive

**Expected behavior**

Proper error message should be returned.

**Environment:**
 - Version 0.17.0.8227.c716b2a44514bf3d9a26b9f720cdd2595df0b3c6

**Comment by NShaforostov** [comment]
Verified.
Fixed

**Comment by NShaforostov** [comment]
**Test case** was created by f596f79009dab770e5c070c64c96f6d8288d9eb0 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Sample_Processing_Module/1613.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #1759.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.SampleProcessingModuleTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
**Docs** were updated via #1855.

**Comment by NShaforostov** [comment]
**Docs** were updated via #1855.
