### ISSUE TITLE
Node Pools: Instance filtering

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#1637]
**Background**
It would be useful to allow to limit usage of node pool instances with a filter, e.g. allow to use pool instances only for certain users or for runs with some parameters set.

**Approach**
`NodePool` shall allow to specify a list of filters and a logical operator (`OR` and `AND`) to be applied to combine filters. Filters themselves shall support value and one of operators: `EQUAL`, `NOT_EQUAL`, `EMPTY`, `NOT_EMPTY`.
Supported filters:
- run owner [string]
- run owner group [string]
- pipeline id [long]
- run parameter [Map<String, String>]
- run configuration id [long]
- docker image [String]

**Examples of node pools with filters**

- use node pool instances only for user `pipe_admin` and tool runs (without `pipeline id`)
```
{
    "id": 1,
    "name": "m5.xlarge workdays",
    ...
    "filter": {
        "operator": "AND",
         "filters": [
            {
                "type": "RUN_OWNER",
                "value": "pipe_admin",
                "operator": "EQUAL"
            },
            {
                "type": "PIPELINE_ID",
                "operator": "EMPTY"
            },
        ] 
    }
}
```

- use node pool instances for users belonging to group `POOL_USERS` or pipeline runs with parameter `USE_POOL=true`
```
{
    "id": 1,
    "name": "m5.xlarge workdays",
    ...
    "filter": {
        "operator": "OR",
        "filters": [
            {
                "type": "RUN_OWNER_GROUP",
                "value": "pipe_admin",
                "operator": "EQUAL"
            },
            {
                "type": "RUN_PARAMETER",
                "value": { "USE_POOL": "true" }
                "operator": "EQUAL"
            },
        ] 
    }
}
```

**Comment by rodichenko** [comment]
@sidoruka @mzueva @NShaforostov #1689 implements GUI part for instance filters

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov GUI backported to `release/0.16` (5ee4160612e052b8610050d38e96c8d7fcb64a09)

**Comment by NShaforostov** [comment]
Verified.
Works well.

Was tested usage of hot node pool with:
- applying different filters (`run owner`, `run owner group`, `pipeline`, `run parameter`, `configuration`, `docker image`)
- applying different filter conditions (logical `AND`, `OR`)
- applying different operators for filters: `EQUAL`, `NOT_EQUAL`, `EMPTY`, `NOT_EMPTY`.

**Comment by NShaforostov** [comment]
**Docs** were updated via #1516.

**Comment by NShaforostov** [comment]
**Test case** was added by #1929 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Cluster_nodes/Hot_node_pools/841_persistent_cluster_nodes/841_4_pool_filters.md).
