### ISSUE TITLE
Pre/Post-commit hooks implementation

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#165]
In certain use-cases, extra steps shall be executed before/after running the commit command in the container.

E.g. imagine the following scenario:
1. User launches `RStudio`
2. User installs packages and commits it as a new image
3. User launches the new image
4. The following error will be displayed in the R Console:
```
16 Jan 2019 21:17:15 [rsession-GRODE01] ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:563
```

There is nothing bad about this message and states that previous RSession was terminated in non-graceful manner.
RStudio will work correctly, but it confuses most of the users.

To workaround such issues (RStudio and some others) we shall implement a techinque of pre/post-commit hooks. That will allow to perform some graceful cleanup/restore before/after performing the commit itself.
Those hooks are valid only for the specific images and therefore shall be contained within those images.

Proposal is as follows:
1. Before performing any common cleanup routines in the `commit_run.sh` we can add a step that will execute a command from the `well-known` location within the docker
2. If a command exists in the docker - it will be executed (`$CLEAN_UP` and `$STOP_PIPELINE` shall be passed to that script as parameters), otherwise this step will be skipped
3. Same for the post-commit, once commit is succeeded (do not run for the failed attempts) - another `well-known` command shall executed

This will allow us to perform image-specific operations to cleanup any residues, that cannot be removed by the common routines

**Comment by mzueva** [comment]
Some clarification for this task:
- `pre-commit` hooks shall be executed in a running initial container
- `post-commit` hooks shall be executed after creation of a temporary container but before final commit/push operations

**Comment by mzueva** [comment]
@ekazachkova enable pre/post commit hooks for pause operation as well

**Comment by sidoruka** [comment]
Works fine for me
