### ISSUE TITLE
Introduce mount timeout for EFS and Lustre

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#1750]
**Background**

At the moment, Cloud Pipeline sensitive runs don't have access to the EFS and the FSx for Lustre filesystems. 
Thus the sensitive run hangs at startup initialization if an NFS storage is mounted. 

**Approach**

* Introduce a `mount_timeout` option to NFS mounting.

**Comment by mzueva** [comment]
Timeout approach doesn't work for all cases, so it would be helpful to completely skip mounting of NFS storage to sensitive runs. Let's introduce a new SystemPreference `storage.mounts.nfs.sensitive.policy` with the following supported values:
- `SKIP` -  NFS mounts shall be skipped for sensitive runs
- `TIMEOUT` - NFS mounts shall be mounted with retry & timeo options for sensitive runs
- `NONE` or missing value - handle NFS mount in common way (mount with options provided for storage)

**Comment by rodichenko** [comment]
@sidoruka, @NShaforostov  GUI part implemented, backported to `release/0.16` (66bba6f7bdc2854556fd38f6a3175acd9f82b7fb)
