### ISSUE TITLE
The day of the week can't be set before the time in the hot node pool schedule settings

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#1751]
**Describe the bug**
At the creation of a new hot node pool schedule, if the day of the week is selected before the time is set - the selected day is being dumped.

**To Reproduce**
1. Click the "**+ Create**" button at the **HOT NODE POOLS** tab
2. Click the field near the "**Starts on**" label
3. Select any day in the appeared list, e.g.:
![image](https://user-images.githubusercontent.com/45459424/105955297-1ee35b00-6087-11eb-882c-9150d068129b.png)
4. See that "selected" day is not displayed in the field:
![image](https://user-images.githubusercontent.com/45459424/105955165-e93e7200-6086-11eb-8d9c-a27f58ac5a44.png)
5. The same for the "**Ends on**" field

**Expected behavior**
The selected day is displayed in the field

**Environment:**
 - Cloud Provider: N/A
 - Version: 0.17.0.8488
 - Browser: Chrome

**Additional context**
If the time in the schedule has already been set - the day of the week can be selected without any problems.

**Comment by rodichenko** [comment]
@NShaforostov this was fixed by ca067cbe4ce7748b9f3e6e84b15ccae5e673ac47, backported to `release/0.16` by 9339f3de4bc730bd492e999266e2583e7d9845df

**Comment by NShaforostov** [comment]
Verified. Fixed

**Comment by NShaforostov** [comment]
**Test case** was created by #1929 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Cluster_nodes/Hot_node_pools/841_persistent_cluster_nodes/841_1_pool_creation.md).

**Comment by NShaforostov** [comment]
**Docs** were added by #1516.
