### ISSUE TITLE
Node hangs on reassigning after pause-resume

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#176]
Version: `0.15.0.531.e858b1dc042f5c4f443abeb8341fba3ec6a76e5c`.

The following scenario causes node hanging:
1. Launch an on-demand run.
2. Pause the run.
3. Resume the run.
4. Stop the run.
5. Relaunch the on-demand run.
6. Verify that it was assigned to the same node that the previous run.
7. Run hangs without any logs.

![image](https://user-images.githubusercontent.com/16464586/56430798-33020200-62d0-11e9-8e6e-b7b7cdc3ce49.png)

**Comment by sidoruka** [comment]
Looks like fixed by #bbcbd29
Not the cleanest solution, but probably will work fine for our short-living compute nodes

**Comment by tcibinan** [comment]
It helped, thanks! The described scenario works now.
