### ISSUE TITLE
Adjust node pool size to cluster workload

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#1779]
**Background**
At the moment `NodePool` feature (introduced by #841) allows to create instance pools with static size. It would be helpful to automatically adjust `NodePool` size according to current cluster workload: increase pool size if most of its instances are assigned to active runs and decrease pool size if most of its instances are idle.

**Approach**
The following fields shall be added to `NodePool` entity:
- `autoscaled` [boolean] - indicates that size of this pool shall be autoscaled up and down
- `minSize` [integer] - pool size cannot be decreased below
- `scaleDownThreshold` [double] - if percent of occupied instances of the pool is lower than this value, pool size shall be decreased
- `maxSize` [integer] - pool size cannot be increased above this value
- `scaleUpThreshold` [double] - if percent of occupied instances of the pool is higher than this value, pool size shall be increased
- `scaleStep` [integer] - pool size shall be decreased/increased with this step

During the autoscaling loop server shall current state of each active `NodePool` and adjust its size according to the fields described above.

**Comment by rodichenko** [comment]
@mzueva @sidoruka GUI part implemented (#1787)

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov GUI part backported to `release/0.16` (31d34eb7643cf8db068a8651e3d453fc86ece93b)

**Comment by NShaforostov** [comment]
Verified.
Works well.

**Docs** were updated via #1804.

**Comment by NShaforostov** [comment]
**Test case** was added by #1929 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Cluster_nodes/Hot_node_pools/841_persistent_cluster_nodes/841_6_pool_autoscaled.md).
