### ISSUE TITLE
Hot Node Pools can't start if the "empty" string is provided in the GUI for any field

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1799]
**Describe the bug**
If the administrator start a new pool (#841) and specifies an empty string to any of the fields, which are optional - the nodes can't be created. 

**To Reproduce**
1. Open a new hot node pool creation window
2. Specify mandatory fields
3. Set value `asdf` to the `AMI` field
4. Delete the `AMI` field value
5. Create a pool
6. Nodes are not created as API can't start `nodeup.py` with the empty `--ins_img` parameter

**Expected behavior**
Empty strings are treated as `null`s and nodes are created using the default AMIs.

**Comment by sidoruka** [comment]
Please backport to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov GUI part fixed, backported to `release/0.16` (af43b66240401038662ee3057ab59f87805a81dc)
