### ISSUE TITLE
Add pause/resume operations support to the `pipe`

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1802]
**Background**
At the moment, users may automate the `pause` and `resume` operation only via the API calls. While this is possible, it's not that nice as could be.
It would be great to expose `pipe pause` and `pipe resume` operations to the CLI.

**Approach**
* Add `pipe pause [RUN_ID] --check-size --sync/-s` and `pipe resume [RUN_ID] --sync/-s` commands
* In a `--sync` mode - we shall wait for the operation to complete. If the command is canceled - we shall inform the user, that the pause/resume operations can't be stopped and it will continue to run in the background

**Comment by sidoruka** [comment]
Please backport to `release/0.16`

**Comment by Wedds** [comment]
<h1> E2E test cases description</h1>

<h2>`pipe pause`</h2>

**Requirements:**
1. Active on-demand run:

    1.1. Start new run using UI or CLI 

    1.2. Wait till the run is initialized (has status 'RUNNING')

For the cases description, assume, that the active run has RunID=*1234* and its' image is *centos:latest*.
<hr>
<h3>CLI-PAUSE-TC-1</h3>

Run is paused in the non-sync mode

**Commands to run:**
1. > pipe pause 1234

**Expected result:**

1. CLI output:
    ```
    Pausing RunID 1234 of "centos:latest@None"
    ```
2. Run state is changed to 'PAUSED' in a reasonable time.

<hr>
<h3>CLI-PAUSE-TC-2</h3>

Run is paused in sync mode

**Commands to run:**
1. > pipe pause --sync 1234

**Expected result:**

1. CLI output:
    ```
    Pausing RunID 1234 of "centos:latest@None"
    ```
2. Run state is changed to 'PAUSED' in a reasonable time. 
3. One more string appears in CLI output:
    ```
    Pausing RunID 1234 of "centos:latest@None"
    RunID 1234 of "centos:latest@None" is paused
    ```
<hr>
<h3>CLI-PAUSE-TC-3</h3>

Run is paused in sync mode, execution is aborted before the operation starts at the server

**Commands to run:**
1. > pipe pause --sync 1234
2. Cancel execution using keyboard interruption (press Ctrl+C) before pausing called at the server-side ('Pausing RunID ...' message didn't appear in CLI output)


**Expected result:**
1. CLI output contains interruption character
    ```
    ^C
    ```
2. Run state didn't change from 'RUNNING'

<hr>
<h3>CLI-PAUSE-TC-4</h3>

Run is paused in sync mode, execution is aborted after operation starts at server

**Commands to run:**
1. > pipe pause --sync 1234
2. Cancel execution using keyboard interruption (press Ctrl+C) after pausing called at the server-side ('Pausing RunID ...' message appeared in CLI output)


**Expected result:**
1. CLI output
    ```
    Pausing RunID 1234 of "centos:latest@None"
    ^C
    Operation abortion... Note: the `pause` operation can't be stopped and it will continue running in the background.
    ```
2. Run state is changed to 'PAUSED' in a reasonable time. 

<hr>
<h3>CLI-PAUSE-TC-5</h3>

Pause command called in the sync mode, but an error, that prevented the pause script from successful execution, occurred

**Commands to run:**
1. Get run's node name
    > pipe view-runs -nd 1234
    
    `nodeName` value of the `Node details` section (assume is `i-012345')

2. Start the pausing process
    > pipe pause --sync 1234
3. Terminate node after pausing called at the server-side ('Pausing RunID ...' message didn't appear in CLI output)
    > pipe terminate-node -y i-012345

**Expected result:**
1. CLI output
    ```
    Pausing RunID 1234 of "centos:latest@None"
    ```
2. Run state changed to 'STOPPED' (node termination) or 'FAILURE' (another unexpected error)
3. One more string appears in CLI output:
    ```
    Pausing RunID 1234 of "centos:latest@None"
    Failed pausing RunID 1234 of "centos:latest@None"
    ```
<hr>
<h3>CLI-PAUSE-TC-6</h3>
Call the `pause` on the run, that is not in the 'RUNNING' state

**Commands to run:**
1. Stop/pause the active run
    > pipe pause 1234
   
    > pipe stop 1234

2. Call `pause` one more time 
    > pipe pause 1234

**Expected result:**
1. CLI output
    ```
    Error: Failed to fetch data from server. Server responded with message: Pipeline run with id: '1234' already finished.
    ```
2. Run state didn't change

<hr>
<h3>CLI-PAUSE-TC-7</h3>

Pause command is called with `--check-size` flag, but run's disk doesn't have enough space to save the state 

**Commands to run:**
1.  > pipe pause --check-size 1234


**Expected result:**
1. CLI output
    ```
    Error: Failed to fetch data from server. Server responded with message: Not enough instance disk to save docker images.
    ```
2. Run state didn't change

_NOTE: it is expected for cases CLI-PAUSE-TC-1..5 to have the same result if `--check-size` is specified and run's disk has enough space. In case of the lack of disk space, their result is the same as for CLI-PAUSE-TC-7_


<br>
<br>
<br>
<h2>`pipe resume`</h2>

**Requirements:**
1. Paused on-demand run:

    1.1. Start new run using UI or CLI 

    1.2. Wait till the run is initialized (has status 'RUNNING')

    1.3. Pause the run

    1.4. Wait till the run is paused (has status 'PAUSED')

For the case description, assume, that the paused run has RunID=*1234* and its' image is *centos:latest*.

<hr>
<h3>CLI-RESUME-TC-1</h3>

Run is resumed in the non-sync mode

**Commands to run:**
1. > pipe resume 1234

**Expected result:**

1. CLI output:
    ```
    Resuming RunID 1234 of "centos:latest@None"
    ```
2. Run state is changed to 'RUNNING' in a reasonable time.

<hr>
<h3>CLI-RESUME-TC-2</h3>

Run is resumed in sync mode

**Commands to run:**
1. > pipe resume --sync 1234

**Expected result:**

1. CLI output:
    ```
    Resuming RunID 1234 of "centos:latest@None"
    ```
2. Run state is changed to 'RUNNING' in a reasonable time. 
3. One more string appears in CLI output:
    ```
    Resuming RunID 1234 of "centos:latest@None"
    RunID 1234 of "centos:latest@None" is resumed
    ```
<hr>
<h3>CLI-RESUME-TC-3</h3>

Run is resumed in sync mode, execution is aborted before the operation starts at server

**Commands to run:**
1. > pipe resume --sync 1234
2. Cancel execution using keyboard interruption (press Ctrl+C) before resuming called at the server-side ('Resuming RunID ...' message didn't appear in CLI output)


**Expected result:**
1. CLI output contains interruption character
    ```
    ^C
    ```
2. Run state didn't change from 'PAUSED'

<hr>
<h3>CLI-RESUME-TC-4</h3>

Run is resumed in sync mode, execution is aborted after operation starts at server

**Commands to run:**
1. > pipe resume --sync 1234
2. Cancel execution using keyboard interruption (press Ctrl+C) after resuming called at the server-side ('Resuming RunID ...' message appeared in CLI output)

**Expected result:**
1. CLI output
    ```
    Resuming RunID 1234 of "centos:latest@None"
    ^C
    Operation abortion... Note: the `resume` operation can't be stopped and it will continue running in the background.
    ```
2. Run state is changed to 'RUNNING' in a reasonable time. 

<hr>
<h3>CLI-RESUME-TC-5</h3>

Resume command called in the sync mode, but an error, that prevented launch script from successful execution, occurred

**Commands to run:**
1. Start resuming the process
    > pipe pause --sync 1234
2. An error occurred during resuming after the process called at the server-side ('Resuming RunID ...' message didn't appear in CLI output)
    > pipe terminate-node -y i-012345

**Expected result:**
1. CLI output
    ```
    Resuming RunID 1234 of "centos:latest@None"
    ```
2. Run state changed to 'STOPPED' or 'FAILURE'
3. One more string appears in CLI output:
    ```
    Resuming RunID 1234 of "centos:latest@None"
    Failed resuming RunID 1234 of "centos:latest@None"
   ```
<hr>
<h3>CLI-RESUME-TC-6</h3>
Call the `resume` on the run, that is not in the 'PAUSED' state

**Commands to run:**
1. Resume a paused run
    > pipe resume 1234
2. Call `resume` one more time 
    > pipe resume 1234

**Expected result:**
1. CLI output
    ```
    Error: Failed to fetch data from the server. Server responded with the message: Pipeline run with id: '1234' not stopped.
    ```
2. Run state didn't change

**Comment by NShaforostov** [comment]
Docs were added via #1972 and located here - [pause command](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/14_CLI/14.5._Manage_pipeline_executions_via_CLI.md#pause-a-pipeline-execution) and [resume command](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/14_CLI/14.5._Manage_pipeline_executions_via_CLI.md#resume-paused-pipeline-execution).
