### ISSUE TITLE
Expand GUI options to terminate nodes

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#1809]
**Background**
At the moment GUI allows to terminate nodes one by one on the `CLUSTER` tab. It would be helpful to expand GUI options to terminate nodes.

**Approach**
- Add `terminate` button to `Node` tab
- Add batch `terminate` to  `CLUSTER` tab to allow deleting of multiple nodes at once

**Comment by rodichenko** [comment]
@sidoruka @mzueva @NShaforostov implemented, backported to `release/0.16` (232983750886902ebf2a38966a36feb684957659)
