### ISSUE TITLE
Improve Tool tab performance

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#1811]
**Background**
At the moment all Tool related data is loaded in one request `/tool/id/attributes` which returns image dependencies and security scan results for all existing tool versions. This requests takes up to several seconds for large images with lots of layers and it significantly affects performance of `Tool` tab. It would be nice to improve performance of this request.

**Approach**
-  introduce a new method instead of `/tool/id/attributes` which will return list of tool versions along with:
     - `attributes` (size, digest, etc.)
     - `scanResult` with count of vulnerabilities by severity, e.g. `{ "Medium": 100, "Critical": "2" }` and without `dependencies` info
- introduce a new method to get full attributes for specific version of a tool
- use new methods for GUI

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov @mzueva backported to `release/0.16` (73ee55de0f6a20382699e158a314d6dac1b80d91)
