### ISSUE TITLE
Allow to run "hosted" applications

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1825]
**Background**
At the moment, Cloud Pipeline allows launching "long-running" applications. But the general approach, initially implemented for the compute jobs, suffers from a number of issues:
* If a run fails (for whatever reason) it's not restarted automatically
* For the internal access (e.g. if a database is hosted) - the IP and name (which match the pod) change during the restarts

**Approach**
* Implement an option to assign an internal DNS name to the runs
  * This can be accomplished by creating a kube service together with the pod and deleting it after the pod is terminated
  * Name of the service and a list of ports can be supplied by the user in the GUI (this can be implemented as a separate API call, like it's already done for the `prettyUrl`)
  * FQDN of the service shall be shown in the GUI (`Launch` form and `Run Details` form)
* Implement an option (specified via the GUI) to force the restart, if a job has failed (NOT `STOPPED`)
  * We shall not rely on kube's native option (like #293 suggests), as this introduces a huge complexity on managing pods, created by the deployment
  * Instead, let's implement custom logic, somewhere in the autoscaling machinery 
  * GUI shall highlight such jobs in the GUI (lists and details form)

**Further work**
* Consider adding a corresponding record into `cp-dnsmasq-hosts` ConfigMap for "nice" DNS names, instead of `cluster.local`

**Comment by sidoruka** [comment]
@rodichenko do not implement GUI, until the API is in place

**Comment by mzueva** [comment]
@rodichenko method GET/POST /run/{runId}/kube/services & `kubeServiceEnabled` flag of `PipelineRun` object

**Comment by maryvictol** [comment]
@rodichenko 
"Save" button on 'Configure Internal DNS' pop-up should be disabled when pop-up is opened.
![image](https://user-images.githubusercontent.com/47791878/112462877-a3461780-8d72-11eb-9ff1-13c81e8a9df3.png)

**Comment by rodichenko** [comment]
@sidoruka @mzueva @NShaforostov GUI *services* part (specifying an internal DNS name, ports) backported to `release/0.16` (245548586b074f940accd2f9973e8dec16ad8da1)

**Comment by rodichenko** [comment]
> @rodichenko
> "Save" button on 'Configure Internal DNS' pop-up should be disabled when pop-up is opened.
> ![image](https://user-images.githubusercontent.com/47791878/112462877-a3461780-8d72-11eb-9ff1-13c81e8a9df3.png)

@maryvictol fixed, backported to `release/0.16` (2fc97327fe96e9f88b8653df1488e2ee93110187)

**Comment by NShaforostov** [comment]
**Test cases** were created by #1876 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Run_tools_in_sandbox/1825_allow_to_run_hosted_applications).

**Comment by NShaforostov** [comment]
**Doc** was added via #1896.
