### ISSUE TITLE
Introduce "faceted filter" capability

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#1829]
**Background**
At the moment, Cloud Pipeline allows searching for the data using a "plain" search string. This works great, but sometimes users have well-structured data, and they want to search by the attributes.
These are attributes is a collection of the dictionaries, with predefined members. 

E.g. we can have a dictionary called `Engineer` with the following members:
* mzueva
* sidoruka
* rodichenko

So the user shall be able to search for any object, which is tagged as `Engineer=mzueva`. And the search query shall allow combining multiple values/dictionaries (similar to the E-Commerce sites). 

**Approach**
* We are going to leverage existing `System Dictionaries` (#1426) functionality to implement this feature
* GUI shall expose a new search form, which allows to:
  * View a list of the "filters", where each filter is a "system dictionary"
  * For each filter - a set of its members shall be displayed
  * Only dictionaries/members with any possible search output shall be displayed. I.e. if the system does not contain any object tagged with `Engineer=sidoruka`, then `sidoruka` member shall not be shown (or disabled - whatever looks better in the GUI) in the `Engineer` filter.
  * Each member shall contain a number of possible search results next to its name. I.e. a number of search result, which will be shown if this filter is enabled
  * At least one filter shall be selected to start querying the server for the search results
* API shall expose all the relevant methods, which are required GUI functionality from the above (@mzueva please fulfil the list of methods here)

**Use cases**
@NShaforostov please add use cases specification here

**Comment by mzueva** [comment]
#### Server Implementation Details

1. At the moment metadata for any object is indexed as a set of tags and it is not possible to run facet queries against it. In allow such queries we need to convert metadata attributes into elasticsearch document fields during document indexing process in `elasticsearch-agent` service. ES mapping for the docs shall be also changed to support variable fields (terms and text).
```
# old ES doc
{
   'id": 1, 
  "name": "pipeline", 
  "metadata": ["key1 val1", "key2 val2"]
}
# new ES doc
{ 
  'id": 1, 
  "name": "pipeline", 
  "metadata": ["key1 val1", "key2 val2"],
  "key1": "val1", 
  "key2": "val2" 
} 
```
2.  New API methods shall be implemented:
 - Method to get faceted results for a list of fields along with search results by text query and filters:
```
# query
POST /restapi/search/facet
{
    "facets": ["cellType", "disease"],
    "query": ["text"],
    "filters": {
       "doc_type": ["PIPELINE", "FILE"],
       "species": ["human"]
     },
     "pageSize": 100,
     "offset": 0,
     "highlight": true
}
# response
{
 "facets": 
 [
    "cellType": 
    {
      "blood": 100,
      "brain": 200
    },
   "disease": 
   {
      "diabetis": 5,
      "influenza": 100
    }
  ],
"documents": [...],
"totalHits": 111
}
```

#### Points to consider
- First implementation shall use current tag approach for files in the object storages (tags are stored using cloud providers API). With merge of #1717 code shall be updated for a new approach
- Indexing time - storage files shall be indexed in parallel (number of threads shall be configurable)
- Total time for an object/file to become searchable depends on the time to fully reindex the largest storage and depends on the number of files in this storage. This issue may be addressed later when #1717 is merged, e.g. index at first index files for which tags were set

**Comment by NShaforostov** [comment]
**Docs** were added via #1896.

**Comment by NShaforostov** [comment]
**Test cases** were added by #1943 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Advanced_Search).
