### ISSUE TITLE
WDL graph search

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#183]
For the large WDL graphs - it is quite hard to find a task (or another artifact) of interest.
E.g. having this kind of graph, it is not easy to find some specific item within:
![image](https://user-images.githubusercontent.com/20998291/56498032-b017bc00-6508-11e9-985c-cf9af9caf7a3.png)

We shall implement some sort of search box inside the `WDL GRAPH` viewer/editor, that will search for any task/variable/input/output within the script and focus/zoom to the found element 

This search box may be added to the left `floating` menu and shall support `Prev/Next` entry navigation (if more than one item was found in the WDL)

**Comment by rodichenko** [comment]
I suppose `Autocomplete input` would be more appropriate instead of `Prev/Next` buttons
