### ISSUE TITLE
Faceted Filter Search page (GUI)

### ISSUE THREAD

**Issue by rodichenko** [epam/cloud-pipeline#1836]
**Background**
At the moment, Cloud Pipeline allows to search pipelines/jobs/tools/etc by specifying search criteria (string) and entity type(s). We're going to introduce new **Faceted Filter** feature (#1829) with advanced filters, but keep current search interface as well.

**Approach**

**Layout**:
* Implement a new **search/advanced** (TBD) route for the **Faceted Filter** page. To open faceted filter search page user must click on the *search* icon of the main menu;
* Previous search interface shall be available by **Ctrl+F** (**Cmd+F**) shortcut;
* Faceted filter search page contains the following controls:
  * Text input for search criteria (string) and a search button at the top of the page;
  * Entity types selector
  * Faceted filters (E-Commerce -like) at the left of the page;
  * Search results (paged)
  ![image](https://user-images.githubusercontent.com/45459424/111765386-5915ef80-88b5-11eb-823f-94e3f8885099.png)

**Search input**:
* User may (optionally) provide a search criteria.

**Entity types selector**:
* User may restrict search results selecting the certain entity type (multiple choice should be supported).

**Faceted Filter section**:
* Faceted filters selectors (see details at #1837).

**Search results**:
* Must contain both paged list and previews (on hover, TBD);
* We must re-use current previews for search results (see details at #1838).

**Comment by NShaforostov** [comment]
Additions:
1. Previous search interface shall be available by **Ctrl+F** (**Cmd+F**) shortcut, but the previous search interface shall not be opened by this shortcut if the user is already on the new advanced search page.
2. To the previous search interface, a link to the new advanced search shall be added (e.g. "**Show Advanced Search**").
3. Pagination control of the "Search results" panel should be placed to the right side of the "Entity types selector" panel - to "clear" space for more search results.

**Comment by maryvictol** [comment]
Pagination control of the "Search results" panel should be removed.

**Comment by NShaforostov** [comment]
**Docs** were added via #1896.

**Comment by NShaforostov** [comment]
**Test case** was added by #1943 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Advanced_Search/1836.md).
