### ISSUE TITLE
Faceted Filter controls (GUI)

### ISSUE THREAD

**Issue by rodichenko** [epam/cloud-pipeline#1837]
**Background**
To introduce a new **Faceted Filter** feature (#1829 #1836), we must implement E-Commerce -like faceted filter controls.

**Approach**
* `System dictionaries` (#1426) are going to be used as faceted filters; to configure their order, visibility and other properties, GUI shall consider `faceted.filter.dictionaries` preference (JSON), i.e.:
```json
{
  "dictionaries" : [
    {
       "dictionary": "dictionary-name-1",
       "order": "1",
       "defaultDictEntriesToDisplay": "all"
    },
    {
       "dictionary": "dictionary-name-2",
       "order": "2"
    }
   ],
  "defaultDictEntriesToDisplay": 5
}
```
* Only dictionary entries with associated objects must be available (i.e. `Dictionary` has `Value1` and `Value2` entries; `Value1` entry is not assigned to any object, so it shouldn't be visible at faceted filter). Our backend team will provide us with corresponding API method [1] for fetching available dictionary entries and associated objects count;
* Every dictionary entry selection/deselection must trigger both faceted filters refresh (API call [1]) and search (API call [2]); 
* Faceted filter control must contain a title (`Dictionary` name) and the list of available entries with objects count;
* This list must be limited to 5 entries max (configurable, see `defaultDictEntriesToDisplay ` property of the `faceted.filter.dictionaries` preference), but can be expanded to display all available entries;
* Also, each `dictionary` config of `faceted.filter.dictionaries` preference can override `defaultDictEntriesToDisplay` property, i.e. we can specify the count of "limited" entries for specific `dictionary`;
* `defaultDictEntriesToDisplay` is a number or a `"all"` string (case insensitive) meaning that entries must not be limited;
* If the number of available dictionary entries is large (say, more then 10, configurable), Faceted Filter control must have filter capability (e.g., text input for filtering items);
* Faceted filter control itself must be collapsible;
* Faceted filter controls must be sorted by `order` (see `faceted.filter.dictionaries` preference), incremental;
![faceted-filter-control](https://user-images.githubusercontent.com/5070496/109784005-a6d6fa80-7c1b-11eb-82b6-ffc9aa0fa3d0.png)
* In addition to all of the above, Entities Types filter must be implemented (i.e. search over pipelines, tools, runs, configurations, etc.);

**Other options**
@mzueva please take a look at `faceted.filter.dictionaries` preference:
* it shall be visible for all users;
* group: "Faceted Filter".

**Comment by maryvictol** [comment]
Selected faceted filter control shall not be disabled even if it doesn't have related documents after applying other filters. 
![image](https://user-images.githubusercontent.com/47791878/115010462-206a3580-9eb6-11eb-8603-ddaeb1375967.png)

**Comment by maryvictol** [comment]
It would be useful for user to have a button to clear all filters.

**Comment by rodichenko** [comment]
> Selected faceted filter control shall not be disabled even if it doesn't have related documents after applying other filters.
> ![image](https://user-images.githubusercontent.com/47791878/115010462-206a3580-9eb6-11eb-8603-ddaeb1375967.png)

> It would be useful for user to have a button to clear all filters.

@maryvictol fixed with 9191cad2c1e2c17e4269e623b6817a0a04b021b1

**Comment by maryvictol** [comment]
For dictionaries with `defaultDictEntriesToDisplay = "all"` in `faceted.filter.dictionaries` preference all entries should be shown in list. Now this list is limited to 5 entries max.

**Comment by maryvictol** [comment]
If the number of available dictionary entries is more then 10 (configurable?), Faceted Filter control must have text input for filtering items.

**Comment by rodichenko** [comment]
> For dictionaries with `defaultDictEntriesToDisplay = "all"` in `faceted.filter.dictionaries` preference all entries should be shown in list. Now this list is limited to 5 entries max.

@maryvictol fixed with daf59ada

**Comment by maryvictol** [comment]
> > For dictionaries with `defaultDictEntriesToDisplay = "all"` in `faceted.filter.dictionaries` preference all entries should be shown in list. Now this list is limited to 5 entries max.
> 
> @maryvictol fixed with [daf59ad](https://github.com/epam/cloud-pipeline/commit/daf59ada52e2816110d37b1dbb259c480365c289)

Verified

**Comment by maryvictol** [comment]
> > Selected faceted filter control shall not be disabled even if it doesn't have related documents after applying other filters.
> 
> > It would be useful for user to have a button to clear all filters.
> 
> @maryvictol fixed with [9191cad](https://github.com/epam/cloud-pipeline/commit/9191cad2c1e2c17e4269e623b6817a0a04b021b1)

Verified

**Comment by NShaforostov** [comment]
**Docs** were added via #1896.

**Comment by NShaforostov** [comment]
**Test cases** were added by #1943 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Advanced_Search).
