### ISSUE TITLE
Faceted Filter search results (GUI)

### ISSUE THREAD

**Issue by rodichenko** [epam/cloud-pipeline#1838]
**Background**
To introduce a new **Faceted Filter** feature (#1829), we must implement a paged list of search results with previews.

**Approach**
* Each modification of the faceted filter or search criteria must trigger the search (see #1837);
* Search Results list must be paged;
* GUI shall display an object preview on hover; we must re-use and (if necessary) improve current preview controls;
* Item's click must open the one's details page (e.g. pipeline details, tool details etc.); user may also use `Ctrl + click` to open details on the new browser tab.

**Comment by NShaforostov** [comment]
## Clarifications

Search results contain an array of objects (Cloud Pipeline entities - `file`, `storage`, `run`, etc.).

For each object in results, the additional info shall be displayed - according to the entity type.
I suggest to show the following info:

| Entity | Required info | Additional info |
| --- | --- | --- |
| **Folder** | NAME | OWNER |
| **Pipeline** | NAME | OWNER / DESCRIPTION |
| **Configuration** | NAME | OWNER / DESCRIPTION |
| **Run** | RUN_ID | OWNER / DATE_STARTED / DATE_COMPLETED |
| **Storage** | ALIAS_NAME | OWNER / PATH / DESCRIPTION |
| **Tool** | NAME | OWNER / PATH |
| **File** | NAME | OWNER / PATH / TYPE / SIZE / DATE_CHANGED |
| **Issue** | TITLE | OWNER / DESCRIPTION |

These object in results can be shown in two formats:
- line view - each result is presented by the "row" in the list, additional info is placed in line
- table view - all results are presented by the single table, additional info is placed in columns

User shall have the ability to switch between formats.
Also: last selected format should be saved for the current user and used for the next time he(she) will leverage the **Advanced Search**.

Example of the both formats:
![image](https://user-images.githubusercontent.com/45459424/111843667-a6747a00-8912-11eb-9911-312b48b090a6.png)
![image](https://user-images.githubusercontent.com/45459424/111843692-b0967880-8912-11eb-8345-c6b1fbedba8e.png)

**Comment by sidoruka** [comment]
@mzueva @rodichenko let's implement the list of "additional" attributes, as @NShaforostov suggests in the following way:
* **As a step 1**: The "base" attributes (from @NShaforostov comment) shall be always indexed, returned to the client and shown in the GUI
* **As a step 2**: In addition to that, the administrator is able to configure a preference, which specified which `metadata attributes` shall be displayed for certain object types, in addition to the "base" set. E.g. `search.elastic.index.metadata.fields`:
```
{
 "S3_FILE":  [
   "LibraryType",
   "SequencingType"
 ]
}
```
* GUI shall display these attributes, if they are provided by the server
* But we shall think of a way to make this dependant on some other dimension. E.g. "filetypes", as the list of attributes may vary if it's a `vcf` of `tiff` file

**Comment by mzueva** [comment]
The following changes shall be implemented for search index & query requests:
1. Check that all fields mentioned in this [comment](https://github.com/epam/cloud-pipeline/issues/1838#issuecomment-802929437) are put into ES index and stored (`"store": true` in index mapping.json)
2. Set `"store": true`  for all fields added from metadata
3. In search query methods extend `buildStoredFields` with all fields mentioned in this [comment](https://github.com/epam/cloud-pipeline/issues/1838#issuecomment-802929437) and all metadata keys set in preference `search.elastic.index.metadata.fields`
4. Add `owner` field to `SearchDocument` class
5. Add `Map<String,String> attributes` to `SearchDocument` class, containing all fields requested at point 3

**Comment by mzueva** [comment]
As we didn't make a final decision on `search.elastic.index.metadata.fields` format, at the moment server accepts just a plain list for this preference.

**Comment by maryvictol** [comment]
Object preview opened on hover any search results string shall be shown near the selected string. Else it isn't possible to click any link on preview popup.
![image](https://user-images.githubusercontent.com/47791878/115009000-78a03800-9eb4-11eb-9306-1ea85a67c85c.png)

**Comment by maryvictol** [comment]
Search by all values gives different reults for **Pipelines** entity types selector for Global and Faceted search. In Global Search  pipelines and their configurations are shown for that option. In Faceted Search files from pipelinesa are returned additionally for that option. Expected that this option shall work the same in both cases.
![image](https://user-images.githubusercontent.com/47791878/115213621-60295b00-a10a-11eb-9d3c-2a0add35fce3.png)

**Comment by maryvictol** [comment]
New browser tab with **incorrect entity URL** is opened at case of openning entity details from search result using Ctrl + item's click.

**Comment by rodichenko** [comment]
> New browser tab with **incorrect entity URL** is opened at case of openning entity details from search result using Ctrl + item's click.

@maryvictol this should be fixed with 933195c840f330b4880c00fa07b8f152bc8d7a38

**Comment by rodichenko** [comment]
> Search by all values gives different reults for **Pipelines** entity types selector for Global and Faceted search. In Global Search pipelines and their configurations are shown for that option. In Faceted Search files from pipelinesa are returned additionally for that option. Expected that this option shall work the same in both cases.
> ![image](https://user-images.githubusercontent.com/47791878/115213621-60295b00-a10a-11eb-9d3c-2a0add35fce3.png)

@maryvictol should be fixed by 1241950323faea6b9b1764fa07961c47bb2c6f7e

**Comment by maryvictol** [comment]
In the Line view of Search results long values should be truncated with ellipsis to separate from the entity Owner info.

**Comment by maryvictol** [comment]
Last selected format (Line or Table view) should be saved for the current user and used for the next time he(she) will leverage the Advanced Search. Now, Line view is always selected at opening Advanced Search.

**Comment by maryvictol** [comment]
> > Search by all values gives different reults for **Pipelines** entity types selector for Global and Faceted search...
> 
> @maryvictol should be fixed by [1241950](https://github.com/epam/cloud-pipeline/commit/1241950323faea6b9b1764fa07961c47bb2c6f7e)

Verified

**Comment by maryvictol** [comment]
> > New browser tab with **incorrect entity URL** is opened at case of openning entity details from search result using Ctrl + item's click.
> 
> @maryvictol this should be fixed with [933195c](https://github.com/epam/cloud-pipeline/commit/933195c840f330b4880c00fa07b8f152bc8d7a38)

Verified

**Comment by rodichenko** [comment]
@maryvictol 4e5ed0bbecd0f8853258eb7f4a029ea8a38219ca  has some fixes:
- preview styles have been changed: document preview now triggered by click on <img width="25" alt="info" src="https://user-images.githubusercontent.com/5070496/116504137-5947d880-a8c0-11eb-8fbd-b50640a2332e.png"> button of the document list item / row;
- for *List view* mode: we're trimming long text lines with ellipsis now.

**Comment by maryvictol** [comment]
> @maryvictol [4e5ed0b](https://github.com/epam/cloud-pipeline/commit/4e5ed0bbecd0f8853258eb7f4a029ea8a38219ca) has some fixes:
> 
> * preview styles have been changed: document preview now triggered by click on <img alt="info" width="25" src="https://user-images.githubusercontent.com/5070496/116504137-5947d880-a8c0-11eb-8fbd-b50640a2332e.png"> button of the document list item / row;
> * for _List view_ mode: we're trimming long text lines with ellipsis now.

Verified. Works well

**Comment by NShaforostov** [comment]
**Docs** were added via #1896.

**Comment by NShaforostov** [comment]
**Test cases** were added by #1943 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Advanced_Search).
