### ISSUE TITLE
SGE master setup fails on ubuntu 18.04 cluster run

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#184]
Version: `0.15.0.574.131f787d54ece5e1ec2a6eaa0cca6da86223651c`

Ubuntu cluster run with enabled `CP_CAP_SGE` parameter fails on `SGEMasterSetup` with the following error messages.

![image](https://user-images.githubusercontent.com/16464586/56498451-69c35c80-650a-11e9-80a5-f4245c5d18cb.png)

How to reproduce:
Launch `library/ubuntu:18.04` cluster run with a single worker and `CP_CAP_SGE=true`.

**Comment by tcibinan** [comment]
The issue is `ubuntu:18.04` specific. SGE cluster run for `ubuntu:16.04` works fine.

**Comment by sidoruka** [comment]
@tcibinan could you please recheck for all three major distros:
- `ubuntu 16`
- `ubuntu 18`
- `centos 7`

**Comment by tcibinan** [comment]
Works for `ubuntu:16.04`, `ubuntu:18.04` and `centos:7` now.
