### ISSUE TITLE
Unable to modify file with .txt extension into pipeline git repository

### ISSUE THREAD

**Issue by ekazachkova** [epam/cloud-pipeline#1872]
**Describe the bug**
Unable to modify file with `.txt` extension to pipeline git repository

**To Reproduce**
1. Go to any pipeline
2. Create file with `.txt` extension
3. Click to file and click `EDIT`
4. Try to save changes

**Expected behavior**
File shall be committed

**Environment:**
 - Cloud Provider: AWS
 - Version: 0.17.0.9003.3c09691cca864e9491433c91d69056919a9a65ae

**Comment by tcibinan** [comment]
Relates to https://gitlab.com/gitlab-org/gitlab-foss/-/issues/34963.
