### ISSUE TITLE
Allow to terminate paused runs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#188]
**BACKGROUND**

At the moment, when a run is paused - the user cannot terminate/stop it before resuming. This is the expected behavior. But in certain "bad" cases - it is not possible to resume a run:
1. An underlying instance is terminated outside of the Cloud Pipeline
2. Docker image was removed from the registry
3. And other cases that are not yet uncovered

This introduces a number of stale runs, that just sit there in the PAUSED state and nobody can remove them.

**TODOs**

1. For the PAUSED runs we shall allow OWNER or the run and the ADMIN users to terminate it
2. Termination of the PAUSED run - shall drop the underlying cloud instance and mark the run as STOPPED
3. From the GUI perspective - we shall not hide the STOP button, but replace it with TERMINATE, when a run is PAUSED (it shall not be available for the interim phases, e.g. PAUSING/RESUMING)

**Comment by mzueva** [comment]
@tcibinan Add method `run/${id}/terminate` that will terminate underlying cloud instance and change run status to `STOPPED`. Method shall be available only for runs in status `PAUSED`.

**Comment by mzueva** [comment]
@rodichenko API method `POST /run/{runId}/terminate` implemented and deployed on dev

**Comment by sidoruka** [comment]
@rodichenko, paused run termination is a relatively long running operation (~10 seconds).
While it is in progress - please disable the `Cancel`/`Terminate` controls, as this will confuse users.

E.g. I can click `Cancel` while run is being terminated
![image](https://user-images.githubusercontent.com/20998291/57798362-3b295200-7755-11e9-85c8-77b63cd2f7d7.png)

**Comment by rodichenko** [comment]
@sidoruka `Cancel` and `Terminate` buttons are disabled now while termination in progress (via 863ae252f4fc94e123dae9858250f4c7fad62b76)
