### ISSUE TITLE
Set data storage object tags explicitly if signed url is used in GUI

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#1880]
**Background**

Relates to #1717.

As long as #1717 backend changes are merged then data storage tags should be set manually for files uploaded using singed urls in GUI.

**Approach**

Once file is uploaded using a signed url the following API method `POST /datastorage/{id}/tags` should be used to set the corresponding data storage object tags.

**Comment by rodichenko** [comment]
@tcibinan after file uploaded `CP_OWNER` tag is set using API (62169500fa7a271308612a5044cb7977bdccae51)
