### ISSUE TITLE
Implement kubernetes dns custom hosts management

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#1900]
**Background**

Currently pods can access other pods using fully qualified domain names or FQDN thanks to #1885. Unfortunately some tools such as openmpi have strict requirement for host name resolving. In order for openmpi to work dns should resolve the same host names which Cloud Pipeline runs use f.e. `pipeline-12345` rather than `pipeline-12345.pods.default.svc.cluster.local`.

**Approach**

In order to support proper host name resolving kubernetes dns can be configured to manage an additional hosts file. Additional pod's container will update the hosts file to add or remove pods and trigger dns reloading.

**Comment by maryvictol** [comment]
**Test cases** were created by #3552  and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Run_tools_in_sandbox/Launch_parameters/1900).
