### ISSUE TITLE
pipe storage should fail if set-object-tag/get-object-tag launched on not existing file

### ISSUE THREAD

**Issue by ekazachkova** [epam/cloud-pipeline#1908]
**Describe the bug**
Current version `pipe storage set-object-tag/get-object-tag` does't fail if operation performed on file that doesn't exist.

**To Reproduce**
1. run `pipe storage set-object-tag cp://test-bucket/not-exists.txt tag-key=tag-value` or `pipe storage get-object-tag cp://test-bucket/not-exists.txt` 
2. no error

**Expected behavior**
Appropriate error message occurred with not `0` exit code 

**Environment:**
 - Cloud Provider: AWS
 - Version 0.17.0.9167

**Comment by tcibinan** [comment]
Should be fixed by 6b7f6505ed2bc980df2a9c695d906b7c54287657. @ekazachkova Could you please verify?

**Comment by ekazachkova** [comment]
@tcibinan Verified, works well. Thanks!
