### ISSUE TITLE
GCP: GCPRegion form update

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#194]
`GCPRegion` now fully supports CORS rules, IAM policy and versioning. 
Corresponding fields (same as for AWS) shall be added  to the `GCPRegion` GUI form:
- `corsRules` - json string
- `policy` - json string
- `backupDuration` - positive integer
-  `versioningEnabled` - boolean

**Comment by rodichenko** [comment]
@mzueva done by 220bfc6c6661befb507c40605c8cdb87764cb657 (`gcp-integration` branch)

**Comment by mzueva** [comment]
done
