### ISSUE TITLE
Incorrect CPU metrics received from elastic

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#195]
Autopause mechanism uses CPU metrics retrieved from the elastic search to filter idle runs. Sometimes, retrieved CPU metrics contains unexpected `Infinity` load values both for idle and not idle runs.

Such metrics lead to a postponing of idle runs autopausing. Example of a `ResourceMonitoringManager` log is shown below.

```
[DEBUG] Checking cpu stats for pipelines: pipeline-1254, pipeline-1256, pipeline-1255
[DEBUG] CPU Metrics received: pipeline-1254:Infinity, pipeline-1256:25.0, pipeline-1255:Infinity
[DEBUG] Checking cpu stats for pipelines: pipeline-1254, pipeline-1256, pipeline-1255
[DEBUG] CPU Metrics received: pipeline-1254:308.0, pipeline-1256:0.0, pipeline-1255:13.0
```

**Comment by mzueva** [comment]
This issue appears when no actual CPU metrics are presents for a run, e.g. when cpu metrics were not collected yet. In this case we should treat a run as non-idle (same as no run info is present at all). @tcibinan Please add corresponding changes to `ResourceMonitoringManage.processRuns`.

**Comment by mzueva** [comment]
will be fixed when PR #215 is merged

**Comment by sidoruka** [comment]
#215 is merged. Can we consider this as fixed?

**Comment by tcibinan** [comment]
It can be seen that `ResourceMonitoringManager` sometimes produces logs with `null` or empty values that can be a sign that something works incorrect. 

@SilinPavel As long as you've recently changed `ResourceMonitoringManager` could you please recheck if everything works as intended?

```
[DEBUG] CPU Metrics received: pipeline-2446:0.0, pipeline-2447:null
...
[DEBUG] memory and disk metrics received: memory: { pipeline-2442:Infinity, pipeline-2440:Infinity, pipeline-2443:Infinity, pipeline-2444:Infinity }; filesystem: { pipeline-2442:0.03351980927836966, pipeline-2440:1.3241710657807644, pipeline-2443:0.15946180665012263, pipeline-2444:0.005406198455686661 }
[DEBUG] High resource consuming notifications for pipelines: null will be sent!
...
[DEBUG] memory and disk metrics received: memory: { pipeline-2450:Infinity }; filesystem: { pipeline-2450:0.01627021091618601 }
[DEBUG] High resource consuming notifications for pipelines:  will be sent!
```

**Comment by sidoruka** [comment]
Can we consider this as fixed?

**Comment by tcibinan** [comment]
Log looks reasonable for version `0.15.0.944.582d8809f22026a80b7d9546bf927093b049ac9d`.

**Comment by sidoruka** [comment]
@mzueva please take a look

Observed again today in the Azure Dev environment (`0.16.0.3059.b9dbe692746b52c70aba83e0b46c3a9d543638fe`)

```
[DEBUG] 2019-10-17 18:17:34.556 [taskScheduler-3] ResourceMonitoringManager - Checking cpu stats for pipelines: pipeline-10229, pipeline-10281, pipeline-10280
[DEBUG] 2019-10-17 18:17:34.566 [taskScheduler-3] ResourceMonitoringManager - CPU Metrics received: pipeline-10229:110.0, pipeline-10281:Infinity, pipeline-10280:Infinity
```

**Comment by tcibinan** [comment]
Closing because no new similar issues seem to appear.
