### ISSUE TITLE
Web GUI shall display a QUEUED state of the run

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#198]
**BACKGROUND**

This issue is related to #192. At the moment - user cannot distinguish runs that are waiting in the queue, and the runs that are being initialized (both report the same state using the same icons).

We shall provide users with a more clear understanding of the run's state. And therefore allow users to make a decision - whether to wait in a queue or stop and resubmit.

**TODOs**

1. Implement a server-side computed property for a `run` object (e.g. `Queued=true/false`). In the same manner as the `Initialized` property
2. This property shall be set to true if:
- Node IP and Node name are not yet assigned to the run
- `InitializeNode` is not present in the list of the run's tasks
3. GUI shall display a `queued` icon (e.g. `hourglass`) if a run has `Queued=true`

**Comment by mzueva** [comment]
@rodichenko check PR #200 - server is ready

**Comment by rodichenko** [comment]
@mzueva thanks. @sidoruka this PR (#200) contains UI changes as well
