### ISSUE TITLE
Azure: addition of a string with spaces as key to file attributes fails

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#206]
- Cloud environment: AZURE
- Version: 0.15.0.649.25d6a46d621406597552b1ea6dce75da09e6f9ad
 
Adding a file attributes key containing string with spaces causes an error `a header name cannot contain the following prohibited characters: =,;: \t\r\n\v\f:`

![image](https://user-images.githubusercontent.com/23356251/56657458-b9d42780-66a0-11e9-811d-46d46304912c.png)

**Comment by mzueva** [comment]
@kamyshova @NShaforostov According to the [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/Setting-and-Retrieving-Properties-and-Metadata-for-Blob-Resources?redirectedfrom=MSDN) : 
```
 metadata names must adhere to the naming rules for C# identifiers.
```
So spaces and some special symbols are not allowed for Azure Blobs metadata name. I'd suggest to disable this test for Azure.
