### ISSUE TITLE
File editing fails using Pluma text editor in mounted object storage

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#2070]
**Describe the bug**
When a file is edited using Pluma text editor in mounted object storage, the content of the modified file disappears.

**To Reproduce**
1. Mount the Magellan object storage to a Linux workstation: 
`pipe storage mount -b bucket_name /mount/point`
2. Create a new file with content using command-line-based text editor: `vi/nano/etc`
3. Open the created file using Pluma text editor: 
`pluma <created_file>`
4. Change the file content (e.g. adding some more text)
5. Save the modified file
6. Open the created file with any text editor
4. See error - opened file is completely empty

**Expected behavior**
The file contains modified content.

**Environment:**
 - pipe version:  `0.16.0.10016.709ac54bd711d122883ab95b45723a3716fa7243`

**Comment by tcibinan** [comment]
@kamyshova The issue should be resolved by #2076.

**Comment by kamyshova** [comment]
Fixed
