### ISSUE TITLE
Historical resources utilisation is shown for active nodes only

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#2093]
**Describe the bug**

Relates to #857.

Currently historical resources utilisation can be viewed for active nodes only. In case node is already offline then empty monitoring page is shown.

**To Reproduce**

1. Go to finished run's page.
2. Open `Instance` tab.
3. Click to run's node name.
4. See that the opened monitoring page is empty.

**Expected behavior**

Historical monitoring data shall be shown for both active and non active nodes.

**Environment:**
 - Version 0.17.0.10250.dfa4ce13f67dd13d0e2f482028149fdac38b0b6d

**Comment by rodichenko** [comment]
@tcibinan @sidoruka @mzueva TBD: for *offline* nodes we don't have OS info (windows/linux), so we cannot hide **Monitor** page for offline windows nodes (as described here #1832)

**Comment by tcibinan** [comment]
Closing since it seems to be working for linux runs now.
