### ISSUE TITLE
All links and buttons are disabled on the Tools page after select any option from Settings menu

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#2102]
**Describe the bug**
After the user select any option from Settings menu on the Tools page all links and buttons on the page (exclude Settings button and _magnifier_ icon) become disabled.

**To Reproduce**
1. Open Tools page
2. Click on Settings button
3. Select any option and click cancel on the appearing pop up
4. Try to input any text to Search field or click any buttom in main menu.

**Expected behavior**
All links and buttons on the page are available.

**Environment:**
 - Cloud Provider: AWS
 - Version  0.17.0.10295

**Comment by rodichenko** [comment]
@maryvictol 1deb3124f5aeb25fa9f92c9c24d0265bacdc6e44 should fix that

**Comment by maryvictol** [comment]
Verified as fixed
