### ISSUE TITLE
Allow to store `pipe` CLI config in the installation directory

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2115]
**Background**
In certain cases, users need to have several `pipe` versions installed into the same workstation.
But this cases issues with the configuration setup. At the moment, `pipe` stores configuration in `~/.pipe/config.json`, so each `pipe` installation - rewrites this file.
We need a way to distinguish configuration between the versions.

**Approach**
Let's introduce `--config-store|-cs` with the following values: `home-dir` (default) and `install-dir`.
* If `home-dir` is specified - current behavior is used. `config.json` is stored into `~/.pipe/` directory
* If `install-dir` is used - `config.json` is written into the directory, where the `pipe` binary is located (note, that this directory may vary, based on the distribution type: `single-file` of `single-directory`)
* This option is NOT available for the `source` distribution type

We shall also change the way `pipe` searches for the `config.json`:
* `pipe` shall search in the `installation directory` first
* `home directory` shall go second

Environment variables shall still have the highest priority and go before the `config.json`.

**Comment by maryvictol** [comment]
Test cases were created by #2151 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Pipe_CLI/2115_store_cli_config_in_install_dir).

**Comment by maryvictol** [comment]
**e2e-test** was implemented via https://github.com/epam/cloud-pipeline/pull/2148.

**Comment by maryvictol** [comment]
**Daily e2e-tests** results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.PipeCLITest.html) (for `AWS`).
