### ISSUE TITLE
Resolve E2E GUI test issues from 25.04.19

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#212]
There are several problems with E2E GUI tests revealed on 25 of April:

**AWS** stand:

- `ObjectMetadataFileTest` fails because the sequence of test steps was changed in accordance with the Azure cloud stand. Thus, the test didn't anticipate the appearance of a new state.
- `RunPipelineTest` fails because run tasks with the name of the pipeline in the left column run page didn't appear after run completion.
- `AutopauseTest` fails because spot run ended earlier than on-demand run, although it's checked at the same time. Besides it needs to change the order checking of runs in EPMCMBIBPC-2634.

**Comment by mzueva** [comment]
@kamyshova Regarding `AutopauseTest` why does the order of run's end affects our tests? This order is undetermined and test should just check that both actions were applied.

**Comment by kamyshova** [comment]
@mzueva You're right. I've added checks for both runs in #214
