### ISSUE TITLE
Chosen user/role should be fully into line with entered group or role after press 'enter' key

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#2123]
**Describe the bug**
Currently the first value is chosen in a drop-down list if a user specifies group/role and presses the' enter' key in "Not shared (click to configure)" -> "Add group" popup.

**To Reproduce**

1. Launch any tool
2. Click the launched run
3. Click the "Not shared (click to configure)" link
4. Click the "Add group" or "Add user" icon in appeared pop-up
5. Specify user or role, which contains its name in another name, so that at least two values appear in the drop-down list
6. Press the "ENTER" key

**Expected behavior**
The input field contains a value that fully corresponds to the entered one.

**Environment:**
 - Cloud Provider: **AWS**
 - Version: **0.17.0.10384**
 - Browser: **chrome**

**Comment by rodichenko** [comment]
@kamyshova d5ebdfe7b9e24cce0a18d77235566f710b1e9254 should fix this issue

**Comment by kamyshova** [comment]
Fixed
