### ISSUE TITLE
The 'SAVE' button is always active on the settings tool page without changing the settings

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#2124]
**Describe the bug**
Currently, the 'SAVE' button is always enabled on the settings tool page without changing the settings.

**To Reproduce**
1. Open the 'Tools' page
2. Select any tool
3. Click the 'SETTINGS' tab
4. See: 'SAVE' button is enabled
5. Click the 'SAVE' button
6. 'SAVE' button is still enabled

**Expected behavior**
The 'SAVE' button should be disabled before making any changes

**Environment:**
 - Cloud Provider: **AWS**
 - Version: **0.17.0.10384**
 - Browser: **chrome**

**Comment by rodichenko** [comment]
@kamyshova #2133 should fix this issue, can you re-check this please?

**Comment by kamyshova** [comment]
Fixed
