### ISSUE TITLE
Trim the spaces in a entered user/group in the 'Share with users and groups' input

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#2130]
**Describe the bug**
If the entered user or group contains trailing or leading whitespace it will be saved as-is - the non-existent user/group.

**To Reproduce**
1. Launch any tool with endpoint
2. Click the launched run
3. Click the "Not shared (click to configure)" link
4. Click the "Add group" or "Add user" icon in appeared pop-up
5. Specify any existent user/role and add space before or after name
6. Save the endpoint link
7. Logout
8. Login as specified shared user (or as who has specified shared role)
9. Open a saved endpoint link at step 6
10. See `401 Authorization Required` error message

**Expected behavior**
The tool application appears 

**Environment:**
 - Cloud Provider: **AWS**
 - Version: **0.17.0.10424**
 - Browser: **chrome**

**Comment by rodichenko** [comment]
@kamyshova d5ebdfe7b9e24cce0a18d77235566f710b1e9254 should fix this

**Comment by kamyshova** [comment]
Fixed
