### ISSUE TITLE
Allow to "impersonate" administrator as a "General" user

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2144]
**Background**
While administering Cloud Pipeline deployment it is common to reproduce users' issues on their behalf. As some of the errors are not reproduced from the `ROLE_ADMIN` users.
It would be beneficial to have an "impersonate" option available for the admins.

**Approach/Use case**
* Administrator loads list of the users
* Administrator loads a user's profile popup
* There is an `impersonate` button
* Administrator clicks this button
* `Cloud Pipeline` page reloads and administrator acts as a selected user
* While in this mode - a separate button `stop impersonation` shall be shown in the left menu
* This button shall revert back to the administrator's "real" account

**Comment by maryvictol** [comment]
**Test case** was created by #2153 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Role_Based_Access_Control/2144_impersonate_admin_as_general_user.md).

**Comment by maryvictol** [comment]
e2e-tests were implemented via #2168.

**Comment by maryvictol** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.RoleBasedAccessControlTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
Docs were added via #3217 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/12_Manage_Settings/12.4._Edit_delete_a_user.md#gui-impersonation).
