### ISSUE TITLE
"Hot nodes" cannot be created as the "instance platform" is null

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2162]
**Describe the bug**
"Hot nodes" cannot be created as the "instance platform" is passed as "null" (literally) from Java to Python.

**To Reproduce**
1. Create any new hot node pool
2. Review the `pipeline.log`
3. `nodup.py` is called with `--ins_platform null`
4. Nodes are not created

**Environment:**
 - Cloud Provider: AWS
 - Version: 0.17.0.10572.359a1cbaf04678bfe6e8fd718a000849f2a1fd0f

**Comment by mzueva** [comment]
fixed
