### ISSUE TITLE
FS quotas management

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2182]
- [x] Introduce email notifications:
  - Shall have only following attrbutes: `Enabled`, `Subject`, `Body`
  - Default `Body` value shall be set during a deployment procedure:
  - Admin shall be able to use any quota or datastorage field in the `Body` template
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        table,
        td {
            border: 1px solid black;
            border-collapse: collapse;
            padding: 5px;
        }
    </style>
</head>

<body>
    <p>Dear user,</p>
    <p>*** This is a system generated email, do not reply to this email ***</p>
    <p>Please be informed, that a data storage <a href="https://$CP_API_SRV_EXTERNAL_HOST:$CP_API_SRV_EXTERNAL_PORT/pipeline/#/storage/${CP_DOLLAR}templateParameters.get("DATASTORAGE_ID")">${CP_DOLLAR}templateParameters.get("DATASTORAGE_NAME")</a> has reached a ${CP_DOLLAR}templateParameters.get("QUOTA_THRESHOLD") volume consumption threshold.</p>
    <p>Data storage state is <b>${CP_DOLLAR}templateParameters.get("DATASTORAGE_MOUNT_STATE")</b></p>
    <br />
    <p>Best regards,</p>
    <p>$CP_PREF_UI_PIPELINE_DEPLOYMENT_NAME Platform</p>
</body>

</html>
```

- [x] Add `mountStatus` to the GUI (info/highlight):
  - `ACTIVE`
  - `MOUNT_DISABLED`
  - `READ_ONLY`
- [x] Show FS size in the GUI
- [x] Change the `MOUNT_DISABLED` state behaviour:
  - This state shall still mount the data storage, but in a readonly state
  - GUI shall be available according to the permissions
  - `READ_ONLY` state shall have a higher priority
  - Please keep the full disablement of the storage logic, as we'll revert to it later. Just need to change the trigger
- [x] Add FS changes events handling, happened from the API. I.e. when the user uploads files from the GUI - those events shall be published to the FS observer's bucket as well

**Comment by sidoruka** [comment]
Shall be cherry-picked to `release/0.16`

**Comment by sidoruka** [comment]
@rodichenko please take care of (2) and (3)
@Wedds (1) and (4) are on your plate. Please implement (4) first and then proceed with the emails

**Comment by maryvictol** [comment]
@rodichenko 
1. ***Disable mount*** and ***Make read-only*** options should not be inserted into the one *Action* field on the *Configure FS mount notifications* pop-up at the same time.
2. Field *Action* should be requered for added notification

**Comment by rodichenko** [comment]
> @rodichenko
> 
> 1. _**Disable mount**_ and _**Make read-only**_ options should not be inserted into the one _Action_ field on the _Configure FS mount notifications_ pop-up at the same time.
> 2. Field _Action_ should be requered for added notification

@maryvictol should be fixed with 67b86c89e1525bba7e2a432e7adad1785cfbf312

**Comment by sidoruka** [comment]
@Wedds, there is another item (p.5) added to the initial issue. Please take care of that.

**Comment by NShaforostov** [comment]
**Test cases** were added by #2208 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Data_storages/2182_2398).

**Comment by rodichenko** [comment]
@mzueva could you please add `ui.storage.refresh.request` preference for the default message shown after storage size update requested?

- name: `ui.storage.refresh.request`
- group: **User Interface**
- type: `string`
- visibility: visible
- default value: `Storage size refresh has been requested. Please wait a couple of minutes.`

**Comment by rodichenko** [comment]
@sidoruka storage size update request backported to `release/0.16` (e5fb198f60dccc4e89062589ab90ae6e17e918c0)

**Comment by maryvictol** [comment]
@Wedds 
**Bug:**
If all contents of the Data Storage that has status `MOUNT_DISABLED` or `READ_ONLY`  are deleted at the same time, then the status isn't changed to active for empty Data Storage after reindexing.

**Comment by maryvictol** [comment]
**Daily e2e-tests** results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.NFSQuotasTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
Docs were added via #3228 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/08_Manage_Data_Storage/8.7._Create_shared_file_system.md#fs-quotas).
