### ISSUE TITLE
Incorrect error message at attemption to upload big file to a storage

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#2196]
**Describe the bug**
Incorrect error message is shown at attemption to upload big file (>500Mb) to a storage

**To Reproduce**
1. Go to stoage
2. Click on **Upload** button
3. Select any file with size >500Mb
4. See error `Maximum 500Gb per file`

**Expected behavior**
Error message `Maximum 500Mb per file` should be shown.
![image](https://user-images.githubusercontent.com/47791878/136375544-fb6e9de6-0141-406f-9ae2-8f1d96726c13.png)

**Environment:**
 - Cloud Provider: AWS
 - Version: 0.17.0.10753

**Comment by rodichenko** [comment]
@maryvictol should be fixed with 67b86c89e1525bba7e2a432e7adad1785cfbf312

**Comment by maryvictol** [comment]
Verified as fixed
