### ISSUE TITLE
Incorrect behavior of global search filter

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#221]
When we use a global search over CP and try to find some object that could be in several categories:
_E.g. there are a folder and an issue with the same name (**"name1"**)_

1. Open Search panel
2. Click "ISSUES" button
3. Input into the search query: **name1**
_In search results list, only issue with the inputted name is displayed. "ISSUES" button is enabled and activated, other buttons are disabled_
4. Click on "ISSUES" button

__*exp.*__: In search results list, issue and folder with the inputted name are displayed. "FOLDERS" and "ISSUES" buttons are enabled and non-activated
__*act.*__: In search results list, issue and folder with the inputted name are displayed. Only "ISSUES" buttons is enabled and non-activated. "FOLDERS" button is disabled

**Comment by rodichenko** [comment]
@NShaforostov fixed by #226

**Comment by NShaforostov** [comment]
Checked
