### ISSUE TITLE
"basic" IdP shall be installed as a "deployment" and persist it's state in a managed volume

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2219]
At the moment, Cloud Pipeline's basic IdP (used for the DEV environments) can't survive restarts:
* It is run as a `POD` and does not start back automatically
* Users and Connections configs are stored in a POD's filesystem, so they are erased each reboot

Let's fixed that:
* Change the `POD` to `DEPLOYMENT`
* Mount the configs to the host's filesystem (e.g. `/opt/idp/basic/`)

**Comment by sidoruka** [comment]
@rodichenko please point to the location of the configuration files, used by the "basic" idp

**Comment by rodichenko** [comment]
@sidoruka @madmongoose 

Configuration files default location (can be overridden by CLI commands):

- Profiles database: `./saml-idp-profiles.json` (`--pd` CLI parameter);
- IDP signature public key: `./idp-public-cert.pem` (`--cert` CLI parameter);
- IDP signature private key: `./idp-private-key.pem` (`--key` CLI parameter).

**Comment by madmongoose** [comment]
https://github.com/epam/cloud-pipeline/tree/cp-idp-deployment
