### ISSUE TITLE
Cloud Pipeline shall allow to expose compute node's FS to upload/download files

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#223]
**BACKGROUND**

For the `interactive runs` (e.g. Web GUI/Desktop/SSH) users are processing data in `ad-hoc` manner. Which requires data upload (from the local storage to the cloud) and results download (from the cloud to the local storage).

At the moment `Cloud Pipeline` supports a number of options for the user to perform that data transfers for the `interactive runs`:
- via the Object Storage (using Web GUI or CLI)
- via the File Storage (using Web GUI/CLI/WebDav-mounted-drive)

But those options require an intermediate location (bucket/fs) to be used. This often confuses users, when a small dataset shall be loaded to the specific location within a run's filesystem.

We can simplify this procedure using a direct exposure of the run's filesystem to the users. E.g.:
- User runs a job and it is initialized
-  `Cloud Pipeline` GUI shows a hyperlink `Browse filesystem` (next to the existing `SSH` button in the log form and in the `Active Runs` dashboard)
- Clicking a link - loads a `Storage browser` Web GUI (same as used for the Object and FS storages)
- User is able to view/download/upload/delete files/directories

**Approach**

To implement the direct FS exposure, the following approach is proposed:
* **(FS API)** A separate (python/flask) service shall be implemented. Service shall expose RESTful API, that shall allow to view/download/upload/delete files/directories. API shall be compatible (to a reasonable extent) with the current Object/FS storages API
  * Download operation shall support both files and directories
  * If a directory is requested for download - it shall result in a gzipped tarball
  * Data transfer operations may be quite heavy (e.g. hundreds of GB). As the traffic will flow through the EDGE service, we may experience performance degradation. To workaround this issue - intermediate object storage shall be used for that:
    * A separate object storage shall be used (identified by `CP_CAP_EXPOSE_FS_STORAGE` environment variable)
    * Storage shall have an auto-cleanup policy (to remove the temp files)
    * If user requests `upload` operation: API shall provide URL for the upload (pointing to the object storage), client will use that URL to upload the data and notify API that the upload is complete. As a result - API will move the file(s) from the object storage to the compute node
    * If user requests `download` operation: API shall copy the requested file to the object storage and provide URL to the client. Client shall download that file from the object storage
* **(Exposure)** Service shall be installed to the runs being initialized using the `launch.sh` entrypoint script. A separate environment variable shall control whether to install or not this service (for the backward compatibility reasons), e.g. `CP_CAP_EXPOSE_FS=true`
* **(GUI)** `Browse filesystem` hyperlink shall be available to the users via the `Cloud Pipeline` Web GUI within a run's log form and a dashboard tiles of the running pipelines
* **(Connectivity)** EDGE service shall configure the `FS API` access via HTTP for the valid runs. URL shall no be displayed in the list of `Endpoints`

**Comment by sidoruka** [comment]
@mzueva please proceed with the `FS API` service implemented once you'll have time for that

**Comment by sidoruka** [comment]
Please add some API configurations, that will allow controlling FSBrowser behavior.
Each configuration item (if set) shall be passed to the container's environment variables:

* `storage.fsbrowser.port`:
  * Type: int
  * Default value: 8091
  * Validation: > 1000
  * Visibility: true
  * Env var: `CP_FSBROWSER_PORT`
* `storage.fsbrowser.wd`: 
  * Type: string
  * Default value: "/"
  * Validation: can be empty
  * Visibility: true
  * Env var: `CP_FSBROWSER_WD`
* `storage.fsbrowser.transfer`:
  * Type: string
  * Default value: empty
  * Validation: can be empty
  * Visibility: true
  * Env var: `CP_FSBROWSER_STORAGE`

**Comment by sidoruka** [comment]
Works fine for AWS/GCP. #681 shall be considered for the futher development, but this one seems ok to document.

@NShaforostov ping

**Comment by NShaforostov** [comment]
> Works fine for AWS/GCP. #681 shall be considered for the futher development, but this one seems ok to document.
> 
> @NShaforostov ping

Docs updated via #807

**Comment by maryvictol** [comment]
Test case was created by #2151 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Run_tools_in_sandbox/Launch_parameters/223.md).

**Comment by maryvictol** [comment]
**e2e-test** was implemented via https://github.com/epam/cloud-pipeline/pull/2148.

**Comment by maryvictol** [comment]
**Daily e2e-test** results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.PlatformPreferencesTest.html) (for `AWS`).
