### ISSUE TITLE
"Custom" capabilities implementation

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2234]
**Background**
At the moment, Cloud Pipeline allows to set a predefined set of capabilities in the GUI for a job or a tool. Which trigger complex reconfiguration for the job (e.g. DIND).
For some use-cases we need to run some simple scripts per user's request. Such scripts may vary between the environments.
It would be nice to let the admins specify those scripts in the platform settings and allow users to select them in the "capabilities" menu.

**Approach**
* Add a new preference `launch.capabilities` with the following format:
```
{
  "capability1": {
    "description": "Some text goes here",
    "commands": [
      "cmd1",
      "cmd2"
    ]
  },
  "capability2": {
    "description": "Another text goes here",
    "commands": [
      "cmd1"
    ]
  }
}
```
* GUI shall read this preference and append list of capabilities names into the overall list and display the `description` field in the tooltip, when hovering this custom capability
![image](https://user-images.githubusercontent.com/20998291/138256341-afc667a5-c2f0-4733-923e-4fffae8864a4.png)
* If the capability is selected - it shall be set as an environment variable in the following format: `CP_CAP_CUSTOM_{CAPABILITY_NAME}=true`. E.g. `CP_CAP_CUSTOM_capability1=true` for the example above

**Comment by sidoruka** [comment]
Cherry-pick to the `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.16` (42ec7b2c32cb6d4e59bba43abd6532d75c5717b3)

**Comment by NShaforostov** [comment]
**Test case** was created by #2287 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Run_tools_in_sandbox/Launch_parameters/2234.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #2287.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.ToolsParametersTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
Docs were added via #2547 and can be found [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/10_Manage_Tools/10.9._Run_capabilities.md#custom-capabilities).
