### ISSUE TITLE
Azure: Azure Files mount path handling

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#227]
When a new FS mount is registered in the GUI we shall handle path with respect to `FS Mount type`. For NFS mounts  (AWS and GCP) we shall add `:` as separator between mount root and path (now works as intended), e.g.:
- for EFS `fs-123.efs.eu-central-1.amazonaws.com` we build storage path as `fs-123.efs.eu-central-1.amazonaws.com:/mount-folder`
For SMB mounts we shall not add `:` and pass path as:
- for File Share `storageaccount.file.core.windows.net` we storage path as `storageaccount.file.core.windows.net/mount-folder`

**Comment by mzueva** [comment]
@rodichenko Please fix FS mount handling for storages with `SMB` mount type

**Comment by rodichenko** [comment]
@mzueva done (#228)
