### ISSUE TITLE
"Custom" capabilities shall allow to configure job parameters

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2295]
"Custom" capabilities (#2234 ) shall also allow to set run parameters for a job.

I.e. administrator shall be able to add (optionally) `params` field to the capability - list of key/values. Each of those keys and values shall be set as the parameters for a job.
```
{
  "capability1": {
    "description": "Some text goes here",
    "commands": [
      "cmd1",
      "cmd2"
    ],
    "params": {
      "MY_PARAM1": "MY_VALUE1",
      "MY_PARAM2": "MY_VALUE2"
    }
  },
  "capability2": {
    "description": "Another text goes here",
    "commands": [
      "cmd1"
    ]
  }
}
```

**Comment by sidoruka** [comment]
@rodichenko please backport to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka implemented (d3f0d20813ee93c777f6abd701ba26a47132458c), backported to `release/0.16` (3d0841f3be394d3ae1ec5eacfe4b7a7b635b45bd)

**Comment by NShaforostov** [comment]
**Test case** was created by #2287 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Run_tools_in_sandbox/Launch_parameters/2295.md).

**Comment by NShaforostov** [comment]
**e2e-tests** were implemented via #2287.

**Comment by NShaforostov** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.ToolsParametersTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
Docs were added via #2547 and can be found [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/10_Manage_Tools/10.9._Run_capabilities.md#custom-capabilities).
