### ISSUE TITLE
"Capabilities" feature shall be dependant on the docker image OS

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2323]
Any of the existing pre-built capabilities and custom capabilities (#2295) shall support `os` parameter:
* This parameter shall control if the capability is allowed for a current docker image.
* We shall be able to enable whole OS family (`centos`) or stick to a specific version only (`centos 7.1.0`). It shall be a comma-delimited list of masks (wildcard is wnough). E.g.:
```
# Allow all centos and ubuntu images
centos*,ubuntu*

# Allow all centos 7 versions and ubuntu 16.04 only
centos 7*,ubuntu 16.04
```
* If `os` is not set (or is not defined for a tool version) or set to `all` - no restrictions are applied
* For the  existing pre-built capabilities we shall apply the following `os` value:
  * DinD: all
  * Singularity: all
  * SystemD: centos
  * NoMachine: all
  * Module: all
  * Disable Hyper-Threading: all

**Comment by sidoruka** [comment]
Please backport to `release/0.16`

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.16` (9ee80bce18774f64c046d2f5f010b2d27dc7e206, 85f5303cf2bcc8581f1142d1236450e9d040a82d)

**Comment by maryvictol** [comment]
Test cases were created by #2412 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Run_tools_in_sandbox/Launch_parameters/2323).

**Comment by maryvictol** [comment]
e2e-tests were implemented via #2449.

**Comment by maryvictol** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.ToolsParametersTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
Docs were added via #2547 and can be found [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/10_Manage_Tools/10.9._Run_capabilities.md#custom-capabilities).
