### ISSUE TITLE
"Endpoint" hyperlink doesn't disappear when run is paused

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#233]
__NOTE__: Such behavior doesn't appear constantly, "flaky" bug.

1. Open "Tools" page
2. Select tool with endpoint
3. Launch selected tool
4. At "ACTIVE RUNS" tab wait until "PAUSE" button will appear next to the just-launched run
5. Click on "PAUSE" button
6. At "ACTIVE RUNS" tab wait until "RESUME" button will appear next to the run
7. Click on the run
8. Check run logs page

__*Exp.*__: "Endpoint" and "SSH" hyperlinks disappear
__*Act.*__: "SSH" hyperlink disappears, "Endpoint" hyperlink is still displaying

![1](https://user-images.githubusercontent.com/45459424/56980831-13978e80-6b86-11e9-8d49-f2e706447cc3.png)

**Comment by mzueva** [comment]
@kamyshova , could you check, maybe this issue is  similar to one with checking logs for runs in final status? At some point GUI stops to update `Run` page, it is possible that this happens while endpoint is not erased yet.

**Comment by mzueva** [comment]
I've checked the logs and here is the underlying problem: API logic is executed correctly, it cleans endpoints while pausing run, but edge sync script ignores actual run status and sets endpoint again when synchronisation starts in the moment, when pod still exists but pause process has already started. I'd suggest to limit runs that are processed by edge sync only to runs with status `RUNNING`.
@sidoruka @SilinPavel Do you have any objections?

**Comment by SilinPavel** [comment]
@mzueva good solution from my point of view. I believe it would easy to implement. Just need to add check for run status before proceeding with endpoint urls updating in sync script, no additional API calls or another interaction between services are required.
