### ISSUE TITLE
While trying to create new S3 bucket, it is created but doesn't appear at CP 

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#234]
__NOTE__: Such behavior doesn't appear constantly, "flaky" bug.

1. Open "Library" page
2. Hover over "+ Create v" button
3. In an appeared list select "Storages" > "Create new object storage"
4. In an appeared pop-up specify a valid storage path
5. Click "Create" button

__*Exp.*__: pop-up is closed, new bucket appears in the library
__*Act.*__: pop-up is still opened, new bucket doesn't appear in the library, but it's created at AWS

The bug is discovered by e2e-tests, an example of such bucket: https://s3.console.aws.amazon.com/s3/buckets/another-bucket-4598564230926819320/?region=us-east-1&tab=overview

**Comment by mzueva** [comment]
@ekazachkova I've checked the logs and the problem is in the following: when we are creating a S3 bucket we assume that this operation is synchronous and bucket exists after method completion. According to logs this is not correct in a rare case. Let's add a waiter for `createBucket` operation.
