### ISSUE TITLE
Implement VM monitor service

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#241]
## Problem
For various reasons cloud VM instances may "hang" and become invisible to Cloud Pipeline services. E.g. VM was created but some error occurred during joining k8s cluster - in this case Autoscale service will be unable to find such instance and it won't be shut down. This problem leads unmonitored useless  resource consumption and billing.

## Solution
We shall implement VM monitoring service that will track all VM instances in the registered `CloudRegions`, determine whether instances is in "hang" state and notify a configurable set of users about an existing problem. User on receiving such a notification may check the actual state of VM in Cloud Provider console and shut down VM manually.

## Implementation details

- VM monitor shall be implemented as a new standalone service  to be deployed as pod
- VM service shall fetch all registered `CloudRegions` from main API service  and check state of available VMs on a scheduled basis 
- VM shall be considered "hang" in the following cases:
          - VM exists in Cloud provider and it is in `Running` state
          - VM is marked as `worker` tag (configurable)
          - VM is not available as `Node` in Cloud Pipeline OR corresponding node  is missing `RUN_ID` label
- VM service shall notify a set of users about VM "hang" state using main API Service endpoint

**Comment by sidoruka** [comment]
> to be deployed as pod
I'm becoming a fan of the deployments. Let's do it as deployment with a 1 replica

> VM exists in Cloud provider and it is in Running state
Ho do we distinguish the `managed` and `unmanaged` instances?

**Comment by mzueva** [comment]
@sidoruka 
> Ho do we distinguish the managed and unmanaged instances?

I've added comment to the issue description:
> VM is marked as worker tag (configurable)

**Comment by sidoruka** [comment]
Thanks. Please consider adding deployment of this service into `pipectl` as well

**Comment by mzueva** [comment]
Done and deployed
