### ISSUE TITLE
[Platform usage] Show user statuses

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#2433]
**Background**

Currently, admins can monitor Platform usage, for example, by list of **ACTIVE RUNS** or via **CLUSTER STATE** pages.
But for some cases, it can be useful for admins to know which users do utilize the Platform in the current moment.
So, we should add the displaying of user states in the "User management" system tab.

**Approach**

In the "**User management**" system tab, for "**Users**" sub-tab add the displaying of users' states.
Possible states should be:
- _Online_ - for users who are logged in and use the Platform in the moment
- _Offline_ - for users who are not logged in at the moment/do not use the Platform for some time

Details:
- the state should be shown as simple icon near the user name, e.g.:
  ![image](https://user-images.githubusercontent.com/45459424/147242554-1ec33e31-bc42-49d4-a7fd-e6e07e9a90f0.png)
- by hover over the _Offline_ icons - the tooltip shall appear that contains the info when the specific user has utilized the Platform the last time, e.g.:
  ![image](https://user-images.githubusercontent.com/45459424/147243964-c5884c44-11d5-4e23-a245-83971fee866f.png)

Additionally:
- Add two new items to the users dropdown filter:
  - ability to show only users who are _online_ at the moment
  - ability to show only users who are _offline_ at the moment
  ![image](https://user-images.githubusercontent.com/45459424/147244604-a6ff61b0-f2a2-4c98-a868-ec692f4c4c5b.png)

All described functionality shall be accessible and shown only for admins.

**Comment by sidoruka** [comment]
Shall be backported to `release/0.16`

**Comment by maryvictol** [comment]
@rodichenko 
**Bug**: User with `ROLE_USER_READER` role shouldn't see statuses icons for users in the *Users Management* list.

**Comment by maryvictol** [comment]
@rodichenko
**Bug:** *Show online users* and *Show offline users* filters should be hidden (or disabled) for User with `ROLE_USER_READER` role.

**Comment by maryvictol** [comment]
@ekazachkova,
User session in impersonation mode should be displayed in **Last visited:** info as well as normal login.

**Comment by maryvictol** [comment]
> @ekazachkova, User session in impersonation mode should be displayed in **Last visited:** info as well as normal login.

Verified as fixed

**Comment by maryvictol** [comment]
> @rodichenko **Bug:** _Show online users_ and _Show offline users_ filters should be hidden (or disabled) for User with `ROLE_USER_READER` role.

Verified as fixed

**Comment by maryvictol** [comment]
> @rodichenko **Bug**: User with `ROLE_USER_READER` role shouldn't see statuses icons for users in the _Users Management_ list.

Verified as fixed

**Comment by mzueva** [comment]
@sidoruka server backported to `release/0.16` 4812e8d9d50a480e616f6f779fc4f3f8fa64e0da

**Comment by rodichenko** [comment]
@sidoruka GUI backported to `release/0.16` 2bf870d

**Comment by maryvictol** [comment]
**Test case** was created by #2512 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Platform_Usage/2433.md).

**Comment by maryvictol** [comment]
**e2e-test** was implemented via https://github.com/epam/cloud-pipeline/pull/2512.

**Comment by maryvictol** [comment]
**Daily e2e-tests** results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.PlatformUsageTest.html) (for `AWS`).

**Comment by NShaforostov** [comment]
Docs were added #3217 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/md/manual/12_Manage_Settings/12._Manage_Settings.md#users).
