### ISSUE TITLE
Git clone over SSH: keys management

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#245]
**BACKGROUND**

Currently, there are two options to communicate with the embedded gitlab repositories, that host pipelines code:
- From the local (non-cloud) machine: use the `https` protocol and the repository URI, provided by the GUI (i.e. `GIT REPOSITORY` button in the pipeline view)
- From the cloud compute node: git' command line interface, that is preconfigured to authenticate using `https` protocol and the auto-generated credentials

Both options consider that `https` is used. It works fine for 99% of the use cases. But for some of the applications - we need to use `ssh` protocol.
This is the only way to achieve a `passwordless` authentication against the gitlab instance

**Approach**
To address this issue, we'll need to introduce `ssh`-based communication with the gitlab from the compute nodes.
For the external connections, we can keep `https`-only approach.
First of all, we'll need to implement SSH keys management. This will allow us to get the key to the compute node and clone the repo. 
Further on SSH keys can be used for other purposes.

**Implementation**
- Users' ssh keys shall be generated by the [Git Sync](https://github.com/epam/cloud-pipeline/tree/develop/scripts/git-role-management) scripts
- If a new user is being created in the GitLab - SSH key-pair shall be created. Public key shall be added to the GitLab config. Private/Public keys shall be added to the Cloud Pipeline user's attributes (i.e. `ssh_pub` and `ssh_prv` fields)
- If a user already exists in both GitLab and Cloud Pipeline - we shall check if all parties have the SSH keys configuration set:
  - If a user has `ssh_pub` and `ssh_prv` configured in the Cloud Pipeline, but not public keu in the GitLab - update GitLab config with the `ssh_pub` value
  - If a user has no `ssh_pub` and/or `ssh_prv` configured in the Cloud Pipeline - key-pair shall be regenerated and stored in the Cloud Pipeline and `ssh_pub` shall be updated in the GitLab

**Further work**
- Once the SSH keys management will be implemented, we'll need to extend current API/GUI routines that expose GIT repository URI. I.e. add an option to clone via SSH.
- Once a new run is started - `launch.sh` shall add corresponding `ssh_prv` to the `root`'s and `$OWNER`'s users `.ssh` directories (We shall be careful with this, as it may conflict with the `ssh` configuration, that we are doing for cluster configuration)

**Comment by mzueva** [comment]
@tcibinan Please, proceed with implementation of ssh-keys management in git sync module.
