### ISSUE TITLE
LDAP urls parameter should be configurable via system preferences

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#2458]
**Describe the bug**
At the moment, LDAP URLs parameter is configured in **application properties** as `spring.ldap.urls`.
It would be convenient to make the parameter configurable via **system preferences** for test usage.

**Comment by tcibinan** [comment]
Relates to #910.

**Comment by tcibinan** [comment]
Should be working once #2459 is merged. Please check #1004 to find all LDAP server configuration system preferences.

**Comment by kamyshova** [comment]
Verified
