### ISSUE TITLE
Backward compatibility for AWS node labels

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#267]
### Issue
In the versions prior to 0.15 AWS nodes were labeled in Kubernetes as `aws_region`. In version 0.15 we changed this label to `cloud_region`. Current autoscaling scripts will ignore nodes labeled with old label and some functionality won't work.

### Solution

- AWS related autoscaling scripts shall use `aws_region` label if `cloud_region` label is missing
- `NodesManager` java class shall also support `aws_region` labels for getting node description

**Comment by sidoruka** [comment]
Resolved via #271
