### ISSUE TITLE
Summary billing report doesn't display data for custom period

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#2675]
**Describe the bug**
Summary billing report show `No data to display` when custom specific period is selected, where:
- year of the **FROM** date is different from the selected year of the **TO** date 
- day of the **FROM** date is not the first day of the selected month
<img width="500" alt="Screen Shot 2022-06-21 at 1 11 58 PM" src="https://user-images.githubusercontent.com/23356251/174776344-c7d95693-aa33-4fd7-88e8-a200fbd49416.png">

**To Reproduce**
1. Open the `Billing` menu item
2. Click the `Custom` period button
3. Click the dates field and set the dates, where FROM year is previous of the current and day is not first day of the month
4. See error `No data to display`

**Environment:**
 - Cloud Provider: **AWS**
 - Version: **0.16.0.12694**
 - Browser: **chrome**

**Comment by rodichenko** [comment]
Backported to `release/0.16` (90193a320478b95f24a18ceac3377b8edad4af57) and `stage/0.16/20220314` (c2661348691f87e3aa05eccd8d884bdffd210d31)

**Comment by kamyshova** [comment]
Fixed
