### ISSUE TITLE
Pipeline pulls incorrect docker image

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#269]
Pipeline pulls the previous docker image after commit

1. Open "Tools" page.
2. Select tool.
3. Launch selected tool
4. Click on the just-launched at "ACTIVE RUNS" tab
5. Check run logs page
6. Wait for ssh link appearing
7. Click to ssh link
8. Perform `cd / && echo 'This is a test file {random int number}' > test_file.txt` in ssh session
9. Close "SSH" tab and navigate to the tab opened at step 1
10. Click on "COMMIT" hyperlink
11. Input a name for docker image that is equal to the tool name selected for launch
12. Click "COMMIT" button
13. Click "OK" button
14. Stop run after commit process is finished
15. Repeat 1-7 steps for the same tool
16. Perform `cd / && head test_file.txt` in ssh session

**Exp**.: The output of 16 step is string consists the text specified at step 8
**Act**.: The output of 16 step is string consists the text specified in file before commit if file exists or error "No such file or directory" if doesn't.

**Comment by NShaforostov** [comment]
Occurred again while performing daily e2e-tests:

Data | CloudPipeline version
---|---
20.05.2019 | 0.15.0.1040.af20e5b63aa7fa5ca1339f74bc4f2d0a41a68e4a
27.05.2019 | 0.15.0.1160.4a4150ee02061e5a243b8c63c1097282276790b0
