### ISSUE TITLE
E2E GUI tests problems from 13.05.19

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#270]
There are several problems with E2E GUI tests revealed on 13 of May:

**AZURE** stand:

- `DockerCommitTest` fails because pipeline pulls incorrect docker image (the bug is described in #269)
- `PauseResumeTest` fails because the ssh link doesn't appear after 42 min of waiting (the bug is described in #262)
In addition, another test method fails because pause button didn't appear after 40 min of waiting (the bug is described in #262)
- `ToolsParametersTest` fails because endpoint link didn't appear after 20 min of waiting (the bug is described in #262)
- `ToolsTest` fails because the run ssh link doesn't appear after 42 min of waiting and "InitializationEnvironment", "MountDataStorages", "InputData" tasks were not executed (the bug is described in #262)

**Comment by NShaforostov** [comment]
Separate issues on actual bugs/errors, described above, were created.
This issue will be closed.
