### ISSUE TITLE
In the Chromium It's impossible input value into the "Allowed instance max count" field on the "Edit User" form

### ISSUE THREAD

**Issue by maryvictol** [epam/cloud-pipeline#2723]
**Describe the bug**
It's impossible input value into the "Allowed instance max count" field on the "Edit User" form via keyboard in the *Chromium* browser. It blocks running tests.

**To Reproduce**
1. Go to the Settings page
2. Open "User management" tab
3. Click on any User in the Users list
4. Input any correct value into the "Allowed instance max count" field
5. Click into the any other field

**Actual behavior:**
Entered at step 4 value disappears from the "Allowed instance max count" field

**Expected behavior**
Entered at step 4 value shall remain in the "Allowed instance max count" field.

**Screenshots**
![image](https://user-images.githubusercontent.com/47791878/177975220-601bb960-856d-4fb7-adba-ce4471e53e5b.png)

**Environment:**
 - Browser: Chromium Version 68.0.3440.106 (Developer Build)

**Comment by rodichenko** [comment]
@maryvictol should be fixed by #2728

**Comment by maryvictol** [comment]
Verified as fixed
