### ISSUE TITLE
Forcible terminate instances if the job is stuck in `umont`

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#2736]
**Background**
It may happen (quite rare!) that a job is stuck when the `init` command is already finished. This can be reproduced in the environments using LustreFS as a cluster scratch filesystem.
It can't be unmounted and hangs in `uninterruptible sleep` state. While this is being fixed in the LustreFS space, we shall be able to handle such situations. 

**Approach**
* Once `init` command is done and a run has finished the `OutputData` step - we need to crate a process which monitors current node state
* If a run is not stopped (state != RUNNING) after a certain period of time (defined by `CP_TERMINATE_RUN_ON_CLEANUP_TIMEOUT_MIN` parameter) - the underlying node is terminated
* If `CP_TERMINATE_RUN_ON_CLEANUP_TIMEOUT_MIN` is not set - nothing happens, everything shall work as previously

**Comment by maryvictol** [comment]
**Test case** was created by #2741 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Run_tools_in_sandbox/Launch_parameters/2736.md).

**Comment by maryvictol** [comment]
**e2e-test** was implemented via https://github.com/epam/cloud-pipeline/pull/2741.

**Comment by maryvictol** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.LaunchParametersTest.html) (for `AWS`).
