### ISSUE TITLE
Add the latest Commit date/time

### ISSUE THREAD

**Issue by malperovich** [epam/cloud-pipeline#274]
It would be great to see the Date/Time of the latest commit of a tool:
![image](https://user-images.githubusercontent.com/17769194/57642862-585bf600-7586-11e9-9e26-df633ca5a765.png)

Thanks!

**Comment by sidoruka** [comment]
@rodichenko, please take a look - do we have enough information from the API already to show the last commit's date/time? Or you'll need API extension?

**Comment by rodichenko** [comment]
@sidoruka we have all required information for displaying latest commit's time. Implemented via #294

**Comment by sidoruka** [comment]
Latest commit data/time is now added to the run's details form
![image](https://user-images.githubusercontent.com/20998291/62771868-d9079100-baa6-11e9-8f98-6f4ac2def1e9.png)

This feature is available in `0.16` and up
