### ISSUE TITLE
E2E GUI tests problems from 14.05.19

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#277]
There are several problems with E2E GUI tests revealed on 14 of May:

**AZURE** stand:

- `DockerCommitTest` fails because pipeline pulls incorrect docker image (the bug is described in #269)
- `PipelineDockerCommitTest` presumably fails because the commit operation has been aborted:

`ExceptionHandlerAdvice - 
This operation has been aborted: uri=/pipeline/restapi/run/1216/commit;client="";session="";user="".  java.lang.NullPointerException: null 
at com.epam.pipeline.manager.cluster.KubernetesManager.getContainerIdFromKubernetesPod(KubernetesManager.java:126) ~[classes!/:0.15.0.874.0161935f08f5d0c067da30f7407efadc9a943b1b] at com.epam.pipeline.manager.docker.DockerContainerOperationManager.commitContainer(DockerContainerOperationManager.java:125)`

- `RoleModelTest` fails because the test click() on runs menu was performed but switch-over
to the runs page didn't happen
- `ToolsScanTest` fails because the the test click() on "OK" button was performed after saving preference in settings popup but it didn't work

**Comment by NShaforostov** [comment]
`PipelineDockerCommitTest` very likely failed because of the bug described at #262. "InitializationEnvironment", "MountDataStorages", "InputData" tasks weren't be executed before commit trying.
Separate issues on other actual bugs/errors, mentioned above, were created.
This issue will be closed.
