### ISSUE TITLE
Introduce extended attributes support in pipe fuse

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#2847]
**Background**

Currently extended attributes support in pipe fuse is disabled. Nevertheless it can be helpful to have extended attributes for automated processing on Linux.

**Approach**

Limited extended attributes support shall be introduced. At this point extended attributes management shall be based upon cloud storage object native tags.

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.16` via 92bf238451edbf993ba92883f47038e43209d452.

**Comment by maryvictol** [comment]
**Test case** was created by #3394 and located [here](https://github.com/epam/cloud-pipeline/blob/develop/docs/testcases/UI/Pipe_CLI/2847_introduce%20extended%20attributes%20support.md).

**Comment by maryvictol** [comment]
**e2e-test** was implemented via https://github.com/epam/cloud-pipeline/pull/3394.

**Comment by maryvictol** [comment]
Daily e2e-tests results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.DataStoragesCLITest.html) (for `AWS`).
