### ISSUE TITLE
Introduce node metrics api

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#2870]
**Background**

Currently only OOM events are being reports on cluster nodes. At the same time there are a lot of helpful metrics which can be collected within cluster nodes.

Specifically the following metrics are of interest atm:
- number of open files per process/per node
- open files limits per process/per node

**Approach**

Existing _oom-reporter_ daemonset shall be updated to include node metrics API which reports metrics listed above for all cluster nodes.

**Comment by tcibinan** [comment]
The following commit includes related changes 5f5315230a9a6f4d727557a2ae4a3ef28b86481b.

**Comment by maryvictol** [comment]
**Test cases** were created by #3398 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Test_Environment).
