### ISSUE TITLE
SAML claims based access

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#290]
Currently, there are two options for users to be generally authenticated, i.e pass SAML validation:
1. `Auto-register` - any valid SAML authentication will automatically register user and grant `ROLE_USER` access
2. `Explicit-register` - after a valid SAML authentication, it will be checked whether is already registered in the `Cloud Pipeline` catalog, and if no - request will be denied

To automate things a bit more, let's implement a 3rd way to grant `first-time` access to the users: `Expicit-group register`.
If it is set - once a valid SAML authentication is received - we shall check, whether SAML response contain any of the domain groups, that are already granted any access on the datasets/files. If so - proceed as with `1. Auto-register`. E.g. - register user with all domain groups and `ROLE_USER` assigned.

This will allow us to grant access based on domain groups only, without extra work with the manual/scripted users registration.

This shall behave the same as we've implemented previously: https://github.com/epam/NGB/issues/223#issue-391043394

**Comment by sidoruka** [comment]
**Note**: we shall double check `EDGE` service: will it handle SAML groups automatically or it can manage Cloud Pipeline's groups at the moment

**Comment by mzueva** [comment]
tested on dev stand
cherry-picked to 0.15 d0d680c09bfa0e7c0a7165b82c67c4bcbac853bf

**Comment by NShaforostov** [comment]
Docs were updated via #860
