### ISSUE TITLE
Support Nextflow pipelines

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#291]
**BACKGROUND**

At the moment `Cloud Pipeline` support running `WDL` pipeline using `Cromwell` executor:
- `WDL` scripts can be visualized and modified using the [Pipeline Builder](https://epam.github.io/cloud-pipeline/manual/06_Manage_Pipeline/6.1.1_Building_WDL_pipeline_with_graphical_PipelineBuilder/#example-pipeline)
- `WDL` pipelines can be run using `local` (all tasks run in the same container), `docker` (tasks can be run using different docker images) and `Cloud Pipeline` (tasks can be run across different nodes/docker images) backends

**[Nextflow](https://github.com/nextflow-io/nextflow)** is another pipelines building/execution engine, which looks quite similar to `WDL/Cromwell` in terms of concepts.

It would be great to introduce a support for running `Nextflow` pipelines within `Cloud Pipeline` using the same capabilities as for `WDL`

**Action items**

* Research possible integration approaches:
  * Using one of the existing `Nextflow` backends for the integration (like we are doing with `Cromwell`'s local backend). This shall be considered as a priority approach and shall not require much of the development. E.g. [Nextflow SGE executor](https://www.nextflow.io/docs/latest/executor.html#sge) looks promising and may be a good pair for the [Grid Engine autoscaling](https://epam.github.io/cloud-pipeline/release_notes/v.0.14/v.0.14_-_Release_notes/#auto-scaled-cluster). Another option is a [Nextflow Kubernetes executor](https://www.nextflow.io/docs/latest/executor.html#kubernetes), which may be a way to go as well.
  * Implementing own executor backend, that will integrate with `Cloud Pipeline`'s API. This approach shall be considered only if there is no way to implement the integration using existing techiques.
* We shall also research whether it is possible/feasible to introduce [Netflow scripting language](https://www.nextflow.io/docs/latest/script.html) support to the [Pipeline Builder](https://github.com/epam/pipeline-builder) and thus to the `Cloud Pipeline`
* Setup a pipeline template for the `nextflow` execution environment with a dummy script

**Comment by TimSPb89** [comment]
> We shall also research whether it is possible/feasible to introduce Netflow scripting language support to the `Pipeline Builder` and thus to the `Cloud Pipeline`

Whilst `Nextflow` looks quite similar to `WDL` in terms of concepts, it has a lot of differences from it speaking about its syntax and code structure. It seems to me that the `Nextflow`'s support will require the development of new grammar and parser, new model, new generator and updating the visualizer in the `Pipeline Builder`.

**Comment by sidoruka** [comment]
* All the configurations are done
* GUI part will be considered as a development effort in the [epam/pipeline-builder](https://github.com/epam/pipeline-builder) project
* Waiting for the @tcibinan feedback on the benchmark of SGE+DinD configuration and fixes of the issues uncovered

**Comment by sidoruka** [comment]
May be fixed by 7ea6016
@tcibinan @mzueva please check

**Comment by tcibinan** [comment]
Looks like 7ea6016 solved the issue. No unexpected pod failures have been seen since then.
