### ISSUE TITLE
GPU scaling cannot be configured from tool settings page

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#2953]
**Describe the bug**

Relates to #2555.

GPU scaling configuration malfunctions on a tool settings page. The lists of available CPU/GPU instances are not shown. This prevents tool settings configuration modifications if GPU scaling is already enabled.

<img width="948" alt="Снимок экрана 2022-12-07 в 12 32 34" src="https://user-images.githubusercontent.com/16464586/206157571-a27ae540-52e6-4d81-8d12-30b29947c2a3.png">

**To Reproduce**

1. Open some tool settings
2. Open cluster configuration
3. Switch to autoscaling cluster tab
4. Enable GPU scaling
5. Expand lists of available CPU/GPU instances to see that there are no instances 

**Expected behavior**

GPU scaling should be configurable from both launch and tool settings pages.

**Environment:**
 - Version 0.17.0.13732.d85549a63199c0d9d91dbcd56256d6bb02b9cfc8
 - Version 0.16.0.13612.af74b49464af6caaa791c2665dafe1a5edafbd9a
 - Browser: chrome

**Comment by rodichenko** [comment]
@tcibinan should be fixed by f4f27c831721460dd4c0474481f746624b0c2e9b

**Comment by tcibinan** [comment]
Seems to be working now. Thank you @rodichenko.
