### ISSUE TITLE
Error of cloning folder with detach configuration

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#305]
CloudPipeline
Version: 0.15.0.1032.2bd65ca366d9ff2b3b25e69f7b502a5931f426bf

1. Create folder, open it
2. In the folder, create detach configuration
3. Click on "gear" icon
4. In an appeared list click on "Clone" item
5. Specify a new valid name
6. Click "Clone into {folder_name}"

__*Exp.*__: "Select destination folder" pop-up is closed, a cloned folder with configuration is opened
__*Act.*__: "Select destination folder" pop-up isn't closed, error "RangeError: Maximum call stack size exceeded" appears. If manually close the pop-up and refresh the page - cloned folder with configuration will appear in the library-tree

**Comment by mzueva** [comment]
@NShaforostov Fix is deployed to dev, could you please verify, that it is done?

**Comment by NShaforostov** [comment]
Checked
