### ISSUE TITLE
Report run tags timepoint

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#3052]
**Background**
For some cases it would be helpful to report timestamp when a specific tag was assigned to a run.

**Approach**
Let's add a new preference `system.run.tag.date.suffix` with default value `_date`. For monitoring tags (IDLE, High Pressure) API shall add the timestamp as `IDLE_date` and similar.

**Comment by rodichenko** [comment]
GUI implemented by c2cf21d8be73868ec7e6060b2df3ce983fca109d

**Comment by maryvictol** [comment]
Test cases were created by #3078 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Run_tools_in_sandbox/3052_report_run_tags_timepoint).
