### ISSUE TITLE
"Download file" is not available for large files from the Azure BLOB storages

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#31]
1. Large files shall NOT be editable
2. There shall be a message displayed in the `Preview` pane and in the `Edit` dialog
```
File is too large to be shown. Download file to view full contents
```
3. For AWS this works fine
4. For Azure the following can be observed
![image](https://user-images.githubusercontent.com/20998291/55163752-6ba03700-517b-11e9-9015-4883a5dcf8b2.png)

**Comment by rodichenko** [comment]
UI is looking at `truncated` field of `datastorage/{storage id}/content?path={file path}` response to decide whether the file's content is truncated.
For large file from Azure blob storage this field is set to `false` while it's content is actually truncated.

**Comment by mzueva** [comment]
@tcibinan Andrei, take a look at this issue.
