### ISSUE TITLE
Commits pushed to the GitLab shall be made on behalf of the user

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#312]
# Background
At the moment, all the commits pushed to the GitLab (via the `Cloud Pipeline` GUI) are made on behalf of the `service account`.
This may break traceability of the changes. 

# Action items
1. GUI shall display the author of the commit in the Web GUI (for the `draft` and `released` versions)
2. API shall perform the commits on behalf of the `real` user
3. API shall provide information on the `committer` to the GUI

**Comment by mzueva** [comment]
@rodichenko GET `/versions` API now returns `author` field with commiter name

**Comment by rodichenko** [comment]
@sidoruka 00cbd281085e78be9459545aeafa150682aa84eb implements GUI part

**Comment by NShaforostov** [comment]
Verified.
Docs were updated via #860
