### ISSUE TITLE
Azure Low-priority VMs price calculation

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#320]
# Background
API shall support price calculation for low-priority VMs in Azure.

# Implementation
- Implement changes to `AzurePriceListLoader` to load prices for low-priority VMs along with on-demand prices
- Implement method `AzureInstancePriceService.getSpotPrice` to return price for ow-priority VMs as `spot` price

**Comment by SilinPavel** [comment]
changes relates to this issue will be implemented in #311
