### ISSUE TITLE
`pipectl` shall deploy all the services as `Kube Deployments`

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#328]
At the moment, the following services are created as `Kube Pods`, so they are not automatically recreated if deleted/failed:
1. `cp-git-sync`
2. `cp-search-srv`
3. `cp-notifier`

That shall be changed to `Kube Deployment`

**Comment by mzueva** [comment]
Also `vm-monitor`

**Comment by sidoruka** [comment]
Backported to `release/0.15` via cb2e1d5
