### ISSUE TITLE
[GUI] Display warning for tools with/without CUDA toolkit

### ISSUE THREAD

**Issue by rodichenko** [epam/cloud-pipeline#3300]
It would be useful to display warnings if user launches:

- A tool with a CUDA toolkit using a CPU-only node:
"You are going to start a tool *with a CUDA toolkit installed*, but using a *CPU-only node (node type)*. No CUDA/Nvidia environment will be available."

- A tool without a CUDA toolkit using a GPU-enabled node:
"You are going to start a tool *without a CUDA toolkit*, using a *GPU-enabled node (node type)*. No CUDA environment will be available, but the compute cost will be high."

**Comment by maryvictol** [comment]
Verified. Works well.

**Comment by maryvictol** [comment]
Test case was created by #3311 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Run_tools_in_sandbox/Launch_parameters/3300.md).
