### ISSUE TITLE
Allow to specify Lustre FS type and thoughput

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#3404]
Allow to specify Lustre FS type and thoughput using parameters `CP_CAP_SHARE_FS_DEPLOYMENT_TYPE` and `CP_CAP_SHARE_FS_THROUGHPUT`

**Comment by maryvictol** [comment]
**Test case** was created by #3406 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Test_Environment/3404.md).

**Comment by maryvictol** [comment]
**e2e-test** was implemented via https://github.com/epam/cloud-pipeline/pull/3406.

**Comment by maryvictol** [comment]
Daily e2e-test results are located and updated [here](https://github.com/epam/cloud-pipeline/blob/e2e-reports/e2e/reports/AWS/test/classes/com.epam.pipeline.autotests.PlatformPreferencesTest.html) (for `AWS`).
