### ISSUE TITLE
Provisioning FSx Lustre FS with user provisioned IOPS

### ISSUE THREAD

**Issue by SilinPavel** [epam/cloud-pipeline#3676]
Now Lustre FS supports user provisioned IOPS: https://docs.aws.amazon.com/fsx/latest/LustreGuide/performance.html#dne-metadata-performance
So, lets provide opportunity for user to customize IOPS when launch cluster with shared lustre FS:

 - New launch.system.preference `CP_CAP_SHARE_FS_IOPS` - Integer, to specify IOPS level according to AWS documentation

**Comment by maryvictol** [comment]
**Test case** was created by #3755 and located [here](https://github.com/epam/cloud-pipeline/tree/develop/docs/testcases/UI/Test_Environment/3676.md).

**Comment by maryvictol** [comment]
**e2e-test** was implemented via https://github.com/epam/cloud-pipeline/pull/3755.
