### ISSUE TITLE
Incorrect behavior while download files from external resources

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#373]
## 1. Bug with creating folders for path fields

1. Open "Library", create a folder, open it
2. Create storage, open it, create a folder
3. Open folder, created at step 1
4. Upload metadata (e.g. use *.csv file from this archive [sample.zip](https://github.com/epam/cloud-pipeline/files/3248194/sample.zip) )
5. Click "TRANSFER TO THE CLOUD"
6. In an appeared pop-up select storage and folder, created at step 2, as "Destination"
7. Select path fields (any one or both)
8. Set "Create folders for each path field" checkbox
9. Click "Start download"
10. Wait until "downloading" run will be completed, open folder created at step 2

__*Exp.*__: folders are created for each path field selected at step 7, at each folder downloaded files are located
__*Act.*__: no additional folders are created, all downloaded files are located at the folder created at step 2

In case, when before downloading you select name in "Select name field", such trouble doesn't appear

## 2. "Transfer to the cloud" doesn't work for Azure because of the unavailable data-transfer-pipeline

1. Repeat steps 1-5 described above
2. Specify any correct values
3. Click "Start download"

__*Exp.*__: download is started
__*Act.*__: error message "Pipeline with requested id: '2,100' was not found." appears

**Comment by rodichenko** [comment]
@NShaforostov part 1 fixed. As for part 2 - please configure correct pipeline identifier (`storage.transfer.pipeline.id` preference) and version (`storage.transfer.pipeline.version`)

**Comment by NShaforostov** [comment]
Checked
