### ISSUE TITLE
Lack of failed pause process log message

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#382]
When pause process is failed, it would be useful to get message log "what's wrong". Currently it doesn't have any logs.

**Comment by mzueva** [comment]
When an exception occurs during run pause process, API shall add a log to this run with:

- task name - the same as used in pause_run scripts
- status - FAILURE
- text - exception message

**Comment by mzueva** [comment]
@kamyshova  After changes are deployed - test it:
1. Create on-demand run
2. Pause it
3. Delete corresponding instance from cloud provider console
4. Resume run
5. Check that error log is created

**Comment by kamyshova** [comment]
@mzueva Verified
