### ISSUE TITLE
AWS: Data storage listing fails when special symbol in listing marker

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#388]
Version: 0.16.0.1362.54b8cfd087eca9d39c70a8f24f0b

The following listing error appears  when the marker is **`attachments/92f55a1e-82ca-43b1-b5bb-6e5609b66cee-C:\Users\User_Name\Downloads\_.png`**

![image](https://user-images.githubusercontent.com/23356251/59198268-fa79f880-8b9b-11e9-8d05-628f6145b2e6.png)

**Comment by sidoruka** [comment]
@mzueva is it a server-side issue?

**Comment by mzueva** [comment]
@rodichenko we need to encode `nextPageMarker` since it is passed as parameter in url

**Comment by rodichenko** [comment]
@mzueva both `marker` and `path` parameters are encoded now

**Comment by kamyshova** [comment]
Fixed
