### ISSUE TITLE
Azure: SMB mount creating fails

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#409]
Version: 0.16.0.1444.85cc87572f76a15a11e0c36d9f2427f809b244c9

NFS mount creating falls with the following error:

`Could not mount nfs '<some-path-to-nfs-mount-point>' with path: '<some-path-to-nfs-mount-point>'`

**Comment by sidoruka** [comment]
Shall we call it SMB or at least File Storage not to confuse with the AWS and GCP?

**Comment by SilinPavel** [comment]
should be resolved after 99ff40837c5

**Comment by kamyshova** [comment]
Fixed
