### ISSUE TITLE
GCP: incorrect error message of existing folder in bucket

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#417]
**Version**: 0.16.0.1453.3e9b95b124ba269b788f2593c3eb1332013b5215

We expect an `Folder already exists` error, when creating an existing folder in the bucket.  
Instead, we get an `Storage path '{folder_name}/' for bucket '{bucket_name}' already exists.` error

**Comment by sidoruka** [comment]
Let's fix this in 0.16 if this will help with the e2e tests, if not - let's pospone

**Comment by kamyshova** [comment]
Fixed
