### ISSUE TITLE
Adapt CP CLI integration tests to support Google Cloud Storages

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#42]
Google Cloud Storage support for `pipe-cli` was introduced in the related issue #11.

Currently, `pipe-cli` integration tests can be launched for `Aws` and `Azure` cloud storage providers. `Google` storage provider is not supported yet. Therefore integration tests should be adapted for usage with `Google` cloud provider.

**Comment by mzueva** [comment]
Tests are ready for setup
