### ISSUE TITLE
Cosmetic bugs in "node type" and "cloud region" tooltips

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#420]
1. When hovering over the node type field in the "Exec environment" section of the configuration page or over the instance type field in the "EXECUTION ENVIRONMENT" section of the tool SETTINGS page, tooltips appear with extra commas, e.g.:
![tooltip1](https://user-images.githubusercontent.com/45459424/59863742-04ff7380-938e-11e9-888a-6eb2b09699e6.png)

2. When hovering over the cloud region field in the "Exec environment" section of the configuration page or in the "Create/edit object storage" pop-up, a tooltip appears with extra text and commas, e.g.:
![tooltip2](https://user-images.githubusercontent.com/45459424/59863887-57409480-938e-11e9-91eb-3338c34c2b96.png)

**Comment by rodichenko** [comment]
@NShaforostov can you re-check this please?

**Comment by NShaforostov** [comment]
@rodichenko 
The problem is still there for the "node type" tooltip:
- in the "EXECUTION ENVIRONMENT" section of the tool SETTINGS page
- in the "Execution defaults" section of the tool VERSION SETTINGS page

**Comment by rodichenko** [comment]
@NShaforostov fixed with 9021a421b835d1fd1ae9358f26c901db6e5a4ae6

**Comment by NShaforostov** [comment]
Checked
