### ISSUE TITLE
GCP: unable to restore and download deleted storage file

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#421]
**Version**: 0.16.0.1453.3e9b95b124ba269b788f2593c3eb1332013b5215

1. Create a storage
2. Open the created storage
3. Click `Upload` button
4. In an appeared pop-up window select a file, confirm its uploading
5. For this storage to give other user (without an admin role) the READ and WRITE permissions
6. Logout
7. Login as user defined in step 5
8. Delete the uploading file in step 4
9. Logout
10. Login as admin
11. Open the created storage in step 1
12. Set `Show files versions`
13. Click "+" button in front of the file name that was deleted in step 8

**Exp**.: 
- the row, colored by red, with the file name, deleting time and label "latest" is displaying
- the row with the file name and time of the last changing is displaying below. In the same row, in front of the file name "Download" and "Restore" buttons are displaying

_AWS example_:

![image](https://user-images.githubusercontent.com/23356251/59866472-514db200-9394-11e9-95b7-080c3ce19c02.png)

**Act**.: 
- the row, colored by red, with the file name, deleting time and label "latest" is displaying
- the row with the file name and time of the last changing is displaying below. In the same row, in front of the file name "Download" and "Restore" buttons aren't displaying

_GCP example_:

![image](https://user-images.githubusercontent.com/23356251/59866555-822de700-9394-11e9-90c3-6515f14b08a7.png)

**Comment by ekazachkova** [comment]
We have a slightly different providers behavior.
Lets assume the following situations
- create file on bucket and show its versions

| gs  | s3 |
| ------------- | ------------- |
| has only one version gs_1  | has only one version s3_1  |

- remove file from bucket

| gs  | s3 |
| ------------- | ------------- |
| has only one version gs_1  | has two versions s3_1, s3_2 (d)* |

- restore file to bucket

| gs  | s3 |
| ------------- | ------------- |
| has two versions gs_1, gs_2  | has two versions s3_2 (d), s3_3  |

- remove file from bucket

| gs  | s3 |
| ------------- | ------------- |
| has two versions gs_1, gs_2  | has tree versions s3_2  (d), s3_3, s3_4  (d) |

- create file on bucket again

| gs  | s3 |
| ------------- | ------------- |
| has tree versions gs_1, gs_2, gs_3  | has four versions s3_2  (d), s3_3, s3_4  (d), s3_5  |

*where `(d) ` means that this version was found in `DeleteMarkers` section

Also, `GS` has only one version without `deletion marker` - the latest (if not deleted), other versions have deletion time.

**Comment by kamyshova** [comment]
Fixed
