### ISSUE TITLE
Rename price types align to the corresponding Cloud Provider

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#422]
Rename the "Spot" price type align to the corresponding Cloud Provider:
- in the "Instance management" panel for the tools ("Allowed price types" field)
- in the "Launch options" panel at the User management forms ("Allowed price types" field)
- in the "Execution defaults" section at the "SETTINGS" tab of a specific tool version

**Comment by rodichenko** [comment]
@NShaforostov as for `Instance management` and `Launch options` - these are provider-independent settings (available for administrators).
As for the last part - price type names are dependent on `instance type` value; if this value is not set, default names are used.
