### ISSUE TITLE
"Constant" labels shall not contains any terms of the specific Cloud Provider

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#423]
Should remove the mention about "S3 buckets" from the description of the System Parameter:

- **CP_S3_FUSE_TYPE**
- **INPUT_DIR**

 (on the form of adding system parameters and in the help-tooltip if added).

**Comment by rodichenko** [comment]
@NShaforostov all system parameters are fetched from the server, including their descriptions. 
@mzueva can you fix this (`/run/defaultParameters` method) please?

**Comment by mzueva** [comment]
@NShaforostov these values are configured in `SystemPreference` `launch.system.parameters` using Web GUI interface. I've fixed default description of `INPUT_DIR` parameter, `CP_S3_FUSE_TYPE` is related only to S3 storages and this name is valid.

**Comment by NShaforostov** [comment]
Checked
