### ISSUE TITLE
Azure: GPU runs fail on node initialization

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#428]
Version: `0.16.0.1469.9b43c70555274b9d2435bebf182a10d76aa3a79c`

Currently, Azure runs with GPU instances fail with the missing image error.

![gpu_initialization](https://user-images.githubusercontent.com/16464586/59926597-4ef66100-9443-11e9-8ddb-d077617ed98b.PNG)

**Comment by sidoruka** [comment]
Something is wrong with the current Azure GPU VM Image (seems that it does not exist). Maybe we shall rebuild Images and copy across the supported regions

**Comment by SilinPavel** [comment]
Images were created in `westeurope` and `eastus` regions, `cloud-pipeline` stages based on Azure were updated with new image links.

**Comment by tcibinan** [comment]
Thanks! Works in `westeurope` region for centos 7 and ubuntu 16, 18 now.
