### ISSUE TITLE
GCP: transfer to the Cloud from external resources doesn't work

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#433]
1. Open "Library", create a folder, open it
2. Create storage, open it, create a folder
3. Open folder, created at step 1
4. Upload metadata (e.g. use *.csv file from this archive [sample_copy.zip](https://github.com/epam/cloud-pipeline/files/3315510/sample_copy.zip))
5. Click "TRANSFER TO THE CLOUD"
6. Specify correct transfer settings
7. Click "Start download"
8. Wait until "downloading" run will be completed, open folder created at step 2

**_Exp._**: downloaded files are located in the folder created at step 2
**_Act._**: the folder created at step 2 is empty. In the storage, excess additional empty folders are created with the names 'http:' and/or 'ftp:' (according to the address paths of the resources for transferring)

**Comment by rodichenko** [comment]
@NShaforostov #492 fixed this issue, could you recheck please?

**Comment by NShaforostov** [comment]
@rodichenko 
Yes, now the transfer is working. But an issue with creating folders for each path field appeared as it was for AWS (see #373, part 1). Can you fix it?

**Comment by rodichenko** [comment]
@NShaforostov fixed (there was an old version of `data-transfer-pipeline` source code)

**Comment by NShaforostov** [comment]
Works fine
