### ISSUE TITLE
Incorrect behavior of the form “Transfer to the cloud” in the case of a subfolder with metadata

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#434]
When you try to download files from external resources using metadata and in that metadata's folder there is another subfolder with its own metadata - on the "Transfer to the Cloud" form attributes (columns) of both metadata files are displaying.

### Example:

1. Open "Library", create a folder, open it
2. Create a subfolder, open it
3. Upload some metadata to the subfolder (e.g. use _1. samples.csv_ from this archive 
[transfer.zip](https://github.com/epam/cloud-pipeline/files/3315557/transfer.zip))
4. Open the folder created at step 1
5. Upload metadata with external resources list (e.g. use _2. resources.csv_ from this archive 
[transfer.zip](https://github.com/epam/cloud-pipeline/files/3315557/transfer.zip))
6. Click "TRANSFER TO THE CLOUD"
7. Click **"Select path fields\*:"**
__*Exp.*__: dropdown is disabled because in the metadata file uploaded at step 5 only one _Path_ column
__*Act.*__: dropdown is enabled with several items from both metadata files (uploaded at steps 3, 5)
8. Click **"Select name field:"**
__*Exp.*__: dropdown has one item because in the metadata file uploaded at step 5 only one column for _Name_
__*Act.*__: dropdown has several items from both metadata files (uploaded at steps 3, 5)

**Comment by rodichenko** [comment]
@mzueva we're using `metadataEntity/fields?folderId=<folder-id>` to get description of all folder's metadata classes (their fields and types). We get all columns from current folder's metadata and nested ones for the test data provided above (and for the **same metadata class**). Can you check this please?

**Comment by mzueva** [comment]
@NShaforostov  @rodichenko This is expected behaviour, most of the metadata methods work for the whole project (folder) including nested folders.

**Comment by rodichenko** [comment]
@mzueva OK, so we can use `metadataEntity/keys?folderId=<>&metadataClass=<>` method to filter fields as it returns only current folder's keys.

**Comment by rodichenko** [comment]
@NShaforostov fixed (via e1d831005c013d7b0f4b5987354bcc9b3630302d), can you re-check this issue please?

**Comment by NShaforostov** [comment]
Checked
