### ISSUE TITLE
Setting of "storage.object.prefix" parameter doesn't work

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#437]
1. Open _System Settings_ -> _Preferences_ -> _Data storage_
2. Specify some string into `storage.object.prefix` parameter
3. Click the **Save** button, click the **OK** button
4. Open library, start to create a new object storage
5. Specify a valid storage path, click the **Create** button
6. Open the storage created at step 5

**_Exp._**: the data storage path contains string from step 2 plus path from step 5
**_Act._**: the data storage path contains only the path from step 5

**Comment by sidoruka** [comment]
@NShaforostov
1. Is it reproduced for all the cloud providers? Or a specific one?
2. Did you set "visible" option for the `storage.object.prefix` parameter? (i.e. enabled that "eye" checkbox)

**Comment by NShaforostov** [comment]
@sidoruka 
1. Azure and GCP
2. Yes, I've tried both variants (with set and unset "visible" option). Doesn't work in both cases. But string, inputted at step 2, is displaying in front of the path field while "Creating storage" form is opened: 
![obprefix](https://user-images.githubusercontent.com/45459424/60029952-c4179f80-96aa-11e9-865b-d15c00b8d413.png)

**Comment by mzueva** [comment]
@NShaforostov fixed in 07b4552

**Comment by NShaforostov** [comment]
Checked
