### ISSUE TITLE
Pipeline name doesn't display correctly when trying to pause/resume it from the "Active runs" tab

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#440]
1. Launch pipeline with "On-demand" price type
2. Open "Active runs" tab
3. Wait until the **PAUSE** button will appear
4. Click the **PAUSE** button

**_Exp._**: in the confirmation popup, the message with the pipeline name appears
**_Act._**: in the confirmation popup, the message with the `[object Object]` text instead of the pipeline name appears

The same behavior with the **RESUME** button

**Comment by NShaforostov** [comment]
Checked

**Comment by rodichenko** [comment]
@sidoruka @NShaforostov backported to release/0.15 via 05ce136a07664b20012a6a20b126bde0ad78f237 6f6671ba4e58df53915739b65a30773417462d01
