### ISSUE TITLE
GCP: storage pagination doesn't work for file versions

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#444]
**Version**: 0.16.0.1501.07b4552a3d8dd1c5bf169f6b77c2165084589683

Storage pagination doesn't work for file versions when a large number of files have been uploaded and then ones were deleted. 

_Steps to reproduce:_

- Create a storage and upload more than 50 files to it
- Click on "Select page" button
- Click on appeared "Remove all selected" button
- Click OK button in an appeared pop-up window
- Repeat steps 2-4
- Set "Show files versions" checkbox
- Click on appeared "Next page" button

**Exp:** the second page is displaying, "Previous page" navigation button is enabled
**Act:** `Error retrieving data storage items: Invalid Value` error message is displaying

![image](https://user-images.githubusercontent.com/23356251/60095544-7311b500-9757-11e9-8256-6e66e3cb1914.png)

**Comment by mzueva** [comment]
@rodichenko same as #388

**Comment by mzueva** [comment]
Fixed
