### ISSUE TITLE
GCP: incorrect behavior of the file version deletion

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#446]
**Version**: 0.16.0.1501.07b4552a3d8dd1c5bf169f6b77c2165084589683

The deletion of the deleted file version leads to the deletion of an independent file with the same name as the deleted file but another extension.

_Steps to reproduce:_

1. Create new storage, set checkbox "Enable versioning" if it's unset
2. Open created storage, make sure that "Show files versions" checkbox is unchecked
3. Create `file_name` and `file_name.csv` files
4. Click on delete-icon for `file_name` file
5. Click OK button in an appeared pop-up window
6. Set "Show files versions" checkbox
7. Click on delete-icon for `file_name` file that was marked as deleted (colored by red)
8. Click OK button in an appeared pop-up window

**Exp:** `file_name.csv` file still exists
**Act:** `file_name.csv` file doesn't exist

Before step 7:

![image](https://user-images.githubusercontent.com/23356251/60098643-b3286600-975e-11e9-9143-73b626aaf0c1.png)

After step 7:

![image](https://user-images.githubusercontent.com/23356251/60098725-d81cd900-975e-11e9-9184-16934b7afdb6.png)

**Comment by mzueva** [comment]
@kamyshova Please, check current issue status on GCP dev.

**Comment by kamyshova** [comment]
Fixed
