### ISSUE TITLE
GCP: Mount buckets and pipe cli incompatibility

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#449]
Version: ` 0.16.0.1501.07b4552a3d8dd1c5bf169f6b77c2165084589683`

As described in #445 `gcsfuse` uses explicit directories which requires an additional empty object. This object has *synthetic name* with a trailing slash. Notice that file cannot has slash in its name in Linux.

While directory copying pipe cli tries to copy each file from the directory and fails on creating a file with an invalid name with slash in it.

Steps to reproduce the error:
```
mkdir /cloud-data/storage/folder
touch /cloud-data/storage/folder/file
pipe storage ls -la gs://storage/folder/
    Type    Labels      Modified               Size    Name     
    File    REGIONAL    2019-06-25 13:48:20       0    folder/  
    File    REGIONAL    2019-06-25 13:48:54       0    file    
pipe storage cp -r gs://storage/folder folder
    Error: [Errno 21] Is a directory: u'folder/'
```

**Comment by mzueva** [comment]
@tcibinan I'd suggest to handle this in corner case in `pipe storage` commands and skip files with `synthetic name `
