### ISSUE TITLE
Web GUI shall display information on the nested runs within a parent log form

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#451]
If a user is viewing details form of a run, that has a number or children (e.g. a cluster run or any other case with the parent-id specified), it shall be possible to view the list of children in the parent's form.

The list of children shall contain the following information:
* State
* Name
* Pipeline name/docker image
* Run time (only duration)

Click each of the children, user shall be able to navigate to it's details.

Keep in mind that this list may contain hundreds of items, so the list layout shall support that number of the entries.

**Comment by sidoruka** [comment]
@rodichenko how difficult it is to port this feature to release/0.15? If nothing too dangerous - please do so.

**Comment by rodichenko** [comment]
@sidoruka 12cb5afd6b0112c779ff9fdf09c4249b1eac13bf implements this issue for **release/0.15**
