### ISSUE TITLE
Introduce `module` support for the Cloud Pipeline runs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#456]
Cloud Pipeline admin shall be able to configure the `modules` support for the compute jobs, if this is required by any use case.

The following scenario shall be supported:
1. If `CP_CAP_MODULES` system parameter is set - `Environment Modules` shall be installed and made available (all supported linux distributions)
2. While installing, `modules` shall be configured to source `modulefiles` from the `CP_CAP_MODULES_FILES_DIR` system parameter, if it is set. If `CP_CAP_MODULES_FILES_DIR` is not set - default location shall be used

**Comment by sidoruka** [comment]
Backported to release/0.15 via af751cac442169d66348d914d099b7769de280bd 6d5b1c1d1405ebc4a8d868ffe6bbc23bb965dff5 729473b8d5f8eec1ac905405d02c437b8870d646

**Comment by NShaforostov** [comment]
@sidoruka 
Can't find `CP_CAP_MODULES_FILES_DIR` system parameter via GUI. Will it be added?
