### ISSUE TITLE
Getting logs from k8s may cause OutOfMemory error

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#468]
# Background
For some workloads, container logs may become very large: up to several gigabytes. When we try to fetch such logs it is likely to cause OutOfMemory error, since k8s library will try to load it into a single String object. We need to limit log's size to prevent such problems.
# Action items

- Introduce a new `SystemPreference` with pod log size limit in lines
- Method for getting pod logs shall fetch tail log lines with respect to this limit
- If actual pod logs exceeds limit add a prefix to log text to show that log is truncated

**Comment by sidoruka** [comment]
Backport to release/v0.15

**Comment by SilinPavel** [comment]
should be resolved by  88c025d

**Comment by mzueva** [comment]
@sidoruka cherry-picked to release/0.15
