### ISSUE TITLE
CLI: pipe storage cp command not working when copying from http/ftp to gs

### ISSUE THREAD

**Issue by rodichenko** [epam/cloud-pipeline#472]
1. Execute:
```
pipe storage cp "http://some-path-to-file" "gs://some-bucket/some-path-to-file" -f
```
2. List bucket's contents
**Exp.**: the file successfully copied to the requested destination.
**Act.**: the file is missing at the requested destination; `http:` folder is created at bucket's root folder

**Comment by rodichenko** [comment]
This also causes `data-transfer-pipeline` issue #433

**Comment by tcibinan** [comment]
Looks fine. @rodichenko Could you please recheck it now.

**Comment by rodichenko** [comment]
@tcibinan yes, it's fine now.
