### ISSUE TITLE
GUI improperly works with detached configurations in a non-default region

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#476]
# Background
It seems that GUI filters instance type when a saved detached configuration is opened, but it doesn't respect `Cloud Region` setting defined in the configuration. This leads to the following issue: instance type is not shown in the detached configuration if it is not available in the default region. This makes such detached configuration unusable since GUI doesn't allow to run configuration without selected instance type. **_Note:_** server returns saved instance type as expected.

# Steps to reproduce

1. Register two `Cloud Regions`, one in Azure, another one in GCP. Set Azure region as default.
2. Create a detached configuration and select GCP `Cloud Region` and `n1-standard-1` instance type, save this configuration. Close configuration tab.
3. Open configuration from step 2.

**_Exp:_** Configuration has instance type with value `n1-standard-1`
**_Act:_** Configuration has empty instance type

**Comment by rodichenko** [comment]
@mzueva fixed (and for `pipeline configuration` as well)

**Comment by mzueva** [comment]
Verified
