### ISSUE TITLE
Uploaded storage file content is downloaded back to client

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#478]
Version: `0.16.0.1633.d7c73373de6ca3a5345aa1cf6606ac422ea3e883`

GCP and Azure Cloud Pipeline clients use POST API method  `datastorage/{id}/list/upload` to upload local files to cloud storages. The method does upload files to cloud storage but it also returns uploaded file content back to the client. It ends up in a significant upload time increase. 

The following timeline shows timing for uploading `20MB` file to google cloud storage using cloud pipeline client:

![image](https://user-images.githubusercontent.com/16464586/60518416-28a9ae80-9cea-11e9-906e-8458d7cd30ef.png)

**Comment by mzueva** [comment]
Please, check behaviour of this method for AWS as well (it is not currently used on the GUI, but still exists).

**Comment by tcibinan** [comment]
The same errored behavior persists for AWS provider.
