### ISSUE TITLE
Worker nodes shall be created in the same regions as parent run

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#485]
# Background
Currently Cloud Pipeline supports a number of options to run a scalable cluster: autoscaled SGE cluster and WDL pipeline with `Use another compute node` option. When launching a new `child` run in such cluster currently cloud region is not specified directly and it may be created in a region other then parent run region, this operation will fail due to various reasons. It is possible to fix the problem in the scaling/cromwell scripts or in the CP API for all cases. 

# Action items
1. API shall checked for all scheduled runs:
- if region is specified - use it
- if parent is specified - use it's region
- otherwise use default region
2. SGE Autoscaling scripts shall run worker runs with parent region specified
3. WDL pipelines shall run tasks with parent region specified

**Comment by sidoruka** [comment]
@mzueva please backport this to release/v0.15

**Comment by mzueva** [comment]
Verified. Cherry-picked to release/0.15: 04a98e1f1ac72412e2b89b000053eb900eb6ff79 52d2bab18ae45004c5c48421baeb92f6c23d2dc7 6472eeb2b435cdc578644d9145afe7695ad38d0d
