### ISSUE TITLE
States of nested runs don't update

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#497]
#451

1. Launch a run, that has children (e.g. a cluster run)
2. Open the parent-run logs page
3. Observe for the states of nested runs

**_Exp._**: states of nested runs are being updated during the time
**_Act._**: states of nested runs don't update during the time and stay the same as they were at the moment the runs log page was opened:
![3](https://user-images.githubusercontent.com/45459424/60683496-cd6dec80-9ea0-11e9-8993-ba26c0c1a17a.png)

**Comment by NShaforostov** [comment]
@rodichenko 
Works fine for active runs. But if parent-run was stopped, only its state becomes "Stopped", nested runs still have their last "active" states.

**Comment by sidoruka** [comment]
@NShaforostov this behavior can be considered as "fine". As once the current job is finished (Stopped/Failed) - it's state is not updated anymore.
There is a number of other issues related to this, so shall be fixed separately.

If the children states are updated while the current job is running - then we can consider this issue as solved.

**Comment by NShaforostov** [comment]
Yes, children "active" states are updated correctly.
