### ISSUE TITLE
Estimate run's disk size according to the input/common parameters

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#501]
# Background

If a job is run with the disk size, which is not enough to handle the job's inputs - it will fail. (e.g. 10Gb disk is set for a run, which will process data using `STAR` aligner, where the genome index file is 20Gb)

# Approach

As an attempt to handle some of such cases - let's try to estimate the required disk size using the input parameters and warn the user if the requested disk is not enough.

1. When launching a job - try to get the size of all input/common parameters
2. We shall limit the time required to traverse all files, as this may take too much for lots of small files. Default: 3 sec
2. When comparing the data and disk sizes - we shall consider cluster configuration:
- For static cluster - sum of all node's and master disks shall be used for comparison
- For autoscaled cluster - sum of all initial node's and master disks shall be used for comparison (autoscaled nodes shall not be considered)
4. If the resulting size is greater than requested - warn the user (WebGUI and CLI):
```
The requested disk size for this run is N Gb, but the data that is going to be processed exceeds it (estimated volume: M Gb). This may cause run to fail with "Out Of Disk" error.
Do you want to use the suggested disk size K Gb (which also considers interim and resulting datasets)?
```
5. Where `K` is calculated as:
- Sum of input parameters (limited by the files number)
- Multiplied by `3` (to keep in mind the interim and resulting files)
- Shall not exceed 16Tb

6. If calculated `K` exceeds 16Tb we shall show a different warning message:
```
The requested disk size for this run is N Gb, but the data that is going to be processed exceeds 16 Tb (which is a hard limit). Please use the cluster run configuration to scale the disks horizontally or reduce the input data volume.
Do you want to use the maximum disk size 16 Tb anyway?
```

**Comment by mzueva** [comment]
@rodichenko new API method is deployed to dev `POST /datastorage/path/size`

**Comment by rodichenko** [comment]
@sidoruka @mzueva GUI part implemented (via 977e09a6f07d44efb59c390737db156441e9d998)

**Comment by sidoruka** [comment]
@mzueva @rodichenko please backport this feature to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka GUI backported to `release/0.15` via 3853cac1c9c1c7a5bde362028551e4c449585f4e

**Comment by mzueva** [comment]
@sidoruka cherry-picked a5d5751038affd0864a6610d38fc07e2ef8bfc0b

**Comment by NShaforostov** [comment]
Is a user warning implemented via CLI?
