### ISSUE TITLE
DTS recursive symlinks

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#502]
There were a number of cases when DTS was trying to upload data from the on-prem storage, where "recursive" symlinks were present.
This caused DTS to follow symlinks infinitely.

DTS shall try to detect such issues and skip the upload for files/folders, that cause infinite loop over symlinks.

**Comment by mzueva** [comment]
@ekazachkova 

1. Add an option to `pipe storage cp/mv` operations to handle symlinks (for local source) :

- `follow` - default
- `skip` - do not follow symlinks 
- `filter` - follow symlinks but check for cyclic links (keep track of visited symlinks)

2. Add options to `dts` service to set symlink policy for transfer operations

**Comment by NShaforostov** [comment]
Verified.
Works fine
