### ISSUE TITLE
Incorrect behavior of a pipeline configuration form

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#514]
Version: `0.16.0.1780.c5905cde1b7971f5dfc099d8b4492e4b10fac764`

Currently when you try to navigate from configuration tab after saved `Parameters` changes the `You have unsaved changes. Continue?` warn popup appears ().

**Steps to reproduce:**
1. Create a pipeline
2. Choose a configuration tab
3. Change a disk size and add a `String parameter` with name in configuration tab
4. Click on `SAVE` button
5. Navigate to any other pipeline tab or tree item

**Comment by NShaforostov** [comment]
Checked
