### ISSUE TITLE
Configuration parameter values are not available for typing

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#515]
Version: `0.16.0.1780.c5905cde1b7971f5dfc099d8b4492e4b10fac764`

Currently it is not available to put value for parameter name in configuration.

**Steps to reproduce:**

1. Create a pipeline
2. Choose a configuration tab
3. Add a String parameter with name in configuration tab

**Expected**: a value field is available for editing
**Actual**: a value field is not available for editing

![image](https://user-images.githubusercontent.com/23356251/61052920-1b30aa80-a3f5-11e9-9f0a-f985a7260a3e.png)

**Comment by NShaforostov** [comment]
Fixed. Checked
