### ISSUE TITLE
Luigi template pipeline run fails

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#526]
**Version**: `0.16.0.1807.57371976e3a4d502215ed47b89df5c23335fb6e1`

Currently created from Luigi template pipeline run  fails at work with the following error:

`error: unrecognized arguments: --pipeline-version draft-24d5fc30`

![image](https://user-images.githubusercontent.com/23356251/61290255-1ba1ba80-a7d4-11e9-9ee3-1e045ed69ab0.png)

**Comment by sidoruka** [comment]
Please backport this to `release/0.15`

**Comment by mzueva** [comment]
@kamyshova is it working now?

**Comment by kamyshova** [comment]
@mzueva Yes, verified. Thanks

**Comment by mzueva** [comment]
@sidoruka cherry-picked to release 0.15
