### ISSUE TITLE
The save of configuration changes is too long

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#527]
**Version**: `0.16.0.1807.57371976e3a4d502215ed47b89df5c23335fb6e1`

Currently the configuration changes saving occurs with a delay on each of the environments (AWS/Azure/GCP). The following popup is being appeared and we can't do anything while it won't close:

![image](https://user-images.githubusercontent.com/23356251/61291218-910e8a80-a7d6-11e9-8549-be8a676288bb.png)

Could we do something about this?

**Comment by sidoruka** [comment]
@kamyshova please add info on the environment (AWS/Azure/GCP). Does it occur for each of them?

**Comment by kamyshova** [comment]
@sidoruka Yes, it occurs for each of them. I've updated issue.

**Comment by sidoruka** [comment]
This is strange, for me it takes ~2 seconds for all the available deployments.
Anything specific about that pipeline, that you've used?

**Comment by NShaforostov** [comment]
It's normal behavior when "Saving" operation takes up to a few secs. Users wouldn't be confused because an info `Updating ...` message is shown during all operation time execution.
This issue will be closed at least for now.

But another issue found related to that situation - see #537.
