### ISSUE TITLE
Incorrect behavior of a choosing a pipeline in a configuration form

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#543]
**Version**: `0.16.0.1900.4a2c62f1ab205347fdf6ccb13ea5719176c2f43c`

When we created a configuration with pipeline and the pipeline has been deleted later, there is no possibility to select a new pipeline in this configuration.

**Step-by-step:**

1. Create a configuration with pipeline and delete the pipeline then:

![image](https://user-images.githubusercontent.com/23356251/61708205-e574b580-ad54-11e9-9e8f-9406225dfa74.png)

2. Click on pipeline change form:

![image](https://user-images.githubusercontent.com/23356251/61708548-bb6fc300-ad55-11e9-9d2a-527d5eb9d3cd.png)

3. Choose a new pipeline in left panel:

![image](https://user-images.githubusercontent.com/23356251/61709158-3685a900-ad57-11e9-91de-a140ebfa3c77.png)

4. Click `OK` button and confirm warn popup.

**Expected**: the configuration with new choosed pipeline
**Actual**: the configuration with deleted pipeline

**Comment by rodichenko** [comment]
@kamyshova fixed, can you re-check please?

**Comment by sidoruka** [comment]
@kamyshova @rodichenko , so is this issue still there?

**Comment by kamyshova** [comment]
@rodichenko Fixed, thanks.
