### ISSUE TITLE
Incorrect behavior of configuration after launch

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#546]
**Version**: `0.16.0.1900.4a2c62f1ab205347fdf6ccb13ea5719176c2f43c`

When we launch a saved configuration and return on configuration page then, this configuration doesn't saved.

**Step-by-step:**

1. Run the saved configuration:

![image](https://user-images.githubusercontent.com/23356251/61730269-b6286d80-ad81-11e9-866d-98479c7477fc.png)

2. Return on the configuration page:

![image](https://user-images.githubusercontent.com/23356251/61730701-980f3d00-ad82-11e9-9055-472c1e8af41c.png)

**Expected**: the configuration is saved
**Actual**: the configuration is unsaved

**Comment by rodichenko** [comment]
@kamyshova fixed, can you re-check please?

**Comment by kamyshova** [comment]
@rodichenko Verified.
