### ISSUE TITLE
Implement storage usage statistics retrieval via pipe

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#548]
Expose `pipe storage du` command which shall provide "disk usage" information on the supported data storages/path:
* Storage/Path name
* Number of files in the storage/path
* Size of the files in the storage/path

The following use cases shall be supported:

## All storages
```
$ pipe storage du
Storage    Files count    Size(Gb)
bucket1    121            17
bucket2    6227           218
bucket3    1              8
```

## Specific storage
```
$ pipe storage du s3://bucket1
Storage    Files count    Size(Gb)
bucket1    121            17
```

## Storage path
```
$ pipe storage du s3://bucket1/path/to/some/files
Storage                       Files count    Size(Gb)
bucket1/path/to/some/files    102            12
```

## Size formatting (-f|--format G/M/K)
```
$ pipe storage du s3://bucket1 -f M
Storage    Files count    Size(Mb)
bucket1    121            17408
```

## du depth (-d|--depth)
```
$ pipe storage du s3://bucket1 -d 3
Storage                 Files count    Size(Gb)
bucket1/path/to/some    102            12
bucket1/path/to/other   2              1
bucket1/path/to/more    1              2
bucket1/path/to/less    4              1
```

**Comment by NShaforostov** [comment]
I've tried to verify this feature. In general, it works.
But some issues were detected:
1) `pipe storage du` (with or without any options) is being failed for NFS storages with the following error message: `Failed to load usage for datastorage <NFS_storage_name>. Cause: Failed to fetch data from server. Server responded with message: Elasticsearch exception [type=index_not_found_exception, reason=no such index]`
2) Can we implement the output of a warning message when the user specifies a non-existing path with `-p` option?
3) Can we implement the sorting of the command output when it's used with `-d` option? It would be clearer for the user.
4) Imagine the situation: there are two folders in the storage - `folder` and `folder2`. Each folder contains 2 files.
In that case, the output of the command `pipe storage du <datastorage> -p folder` will be:
```
Storage                 Files count      Size (Mb)
<datastorage>/folder    4                ...
```
But for the command `pipe storage du <datastorage> -p folder/` will be:
```
Storage                 Files count      Size (Mb)
<datastorage>/folder/   2                ...
```
Probably, we shouldn't use the inputted path with `-p` option as a "mask" but only as the specific path to the directory?

**Comment by NShaforostov** [comment]
Docs were updated via #991
