### ISSUE TITLE
GCP: Mounting bucket is failed to launched tool

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#549]
**Environment**: `GCP`
**Version**: `0.16.0.1916.46d7e7d065cf7db5eab314572f25e2631d124721`

A bucket with access is not mounted to launched tool and the following error appears in `MountDataStorages` task logs:

![image](https://user-images.githubusercontent.com/23356251/61791123-c55ef800-ae21-11e9-9085-c5966775bc5e.png)

**Comment by sidoruka** [comment]
@kamyshova this shall work fine now, could you please recheck?

**Comment by kamyshova** [comment]
@sidoruka Verified. Fixed, thanks
