### ISSUE TITLE
Cluster runs are paused by "Autopause" but can't be resumed

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#557]
Currently, cluster runs couldn't be paused manually even if price type is "**On-demand**".
But if cluster run was launched with enabled "**Auto pause**" option, parent-run or its child-runs will be paused (when autopause conditions are satisfied, of course). In that case, user couldn't resume such paused runs and go on his work because only "**Terminate**" buttons will be available:
![1](https://user-images.githubusercontent.com/45459424/61949435-9082aa80-afb3-11e9-9cf9-ec12c744330e.png)

**Comment by sidoruka** [comment]
Autopause daemon shall not handle clusters

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by NShaforostov** [comment]
Verified. Fixed.
@SilinPavel, please backport to `release/0.15`

**Comment by SilinPavel** [comment]
@NShaforostov Done.
