### ISSUE TITLE
Incorrect `pipe` CLI version displaying

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#561]
Cloud Pipeline Version: 0.16.0.1985.a4ab75c351804fb93444f08f990887273ca06395

1. Install `pipe` CLI via hints from the System Settings for Linux OS
2. Run in the terminal the `pipe --version` command

**_Exp._**: version is the same as in GUI
**_Act._**: an old version number is displaying:
![11](https://user-images.githubusercontent.com/45459424/62072685-d5bf0a80-b247-11e9-8444-fe8c4844776e.png)

_Found in AWS_

**Comment by sidoruka** [comment]
Shall be backported to `release/0.15`

**Comment by sidoruka** [comment]
Moved to `release/0.15` via fe6106e

**Comment by NShaforostov** [comment]
Verified. Fixed
