### ISSUE TITLE
Adding a second region to Cloud Pipeline leads to broken spot instances 

### ISSUE THREAD

**Issue by SilinPavel** [epam/cloud-pipeline#563]
# Description
It seems that adding a second region to Cloud Pipeline leads to broken spot instances.
I think that some how it is related to update of offered instance types, when new region being created.

**Comment by mzueva** [comment]
@SilinPavel Please verify and close after redeploy

**Comment by SilinPavel** [comment]
verified and closed

**Comment by SilinPavel** [comment]
@sidoruka should it be cherry-picked to 0.15?
