### ISSUE TITLE
Web GUI shall not display "Autopause ON/OFF" for the cluster runs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#564]
Related to #557 

If the cluster is configured (no matter "Static" or "Autoscaled") - we shall not display `Auto pause: Enabled/Disabled` in the **Launch Form** for the `On-Demand` node type

Verify that everything works for all supported Cloud Providers

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.15`
