### ISSUE TITLE
pipe storage cp/mv shall not fail if a source file/dir lacks read permissions

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#571]
Currently, if a `pipe storage cp/mv` are running with a "local" source and a "remote" destination, the following behavior is observed:
- Image that a directory with 100 files is being uploaded to the remote storage
- If the 20th file from the source directory is not readable by the `pipe` process
- Then the whole command fails, other 80 files will not be uploaded

We shall check `read` permission for the "local" source (directories and files) and skip those that are not readable (a corresponding warning message shall be printed)

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by mzueva** [comment]
cherry-picked
