### ISSUE TITLE
Incorrect behavior of a 'Launch' button on pipeline launch page

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#572]
**Version**: `0.16.0.2045.d6057b752c9a27b101561df65f55e3a4b09a2f1a`

When we configure a pipeline with output/input/common path value in parameters and path is new for pipeline parameters `Launch` button on pipeline launch page is not available.

**Step-by-step**:

_The first case:_

1. Create storage
2. Create pipeline (from `SHELL` template)
3. Open created pipeline, select version
4. Click `RUN` button
5. Click on `Add parameters` button
6. In an appeared row into the left field specify parameter name (e.g. "result")
7. In an appeared row into the right field specify parameter value (e.g. 
`{full path to the storage created on step 1}/storage_rules_folder/`
**Expected**:  `Launch` button is available.
**Actual**: `Launch` button is not available.

_The second case:_

1. Create storage
2. Create pipeline (from `SHELL` template)
3. Open created pipeline, select version
4. On the pipeline page select CODE tab and click on `config.json` file and edit it (add next code into the parameters section):
`"result":
{
    "type": "output",
    "value": "{full path to the storage created on step 1 with folder}",
    "required": "true"
}
`
5. Click `RUN` button
**Expected**:  `Launch` button is available.
**Actual**: `Launch` button is not available.

image
![image](https://user-images.githubusercontent.com/23356251/62296093-1a7cb880-b477-11e9-85c9-402dcbb367cc.png)

**Comment by rodichenko** [comment]
@kamyshova fixed, can you re-check please?
@NShaforostov backported to release/0.15

**Comment by kamyshova** [comment]
@rodichenko Yes, fixed. Verified. Thanks.
