### ISSUE TITLE
JWT token shall be updated for the jobs being resumed

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#579]
Currently, we can run into the following issue:
1. A user launches an on-demand job and then pauses it
2. Job is kept "paused" for 2+ months
3. When a user resumes a job - an expired JWT token is set
4. This leads to different problems when any of the initialization routines tries to communicate with the API

We shall update the JWT token (and other variables as well) when a job is being resumed, in the same manner as it is done for the newly launched jobs

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by mzueva** [comment]
@sidoruka It seems that we cannot simply update all the variables in the way we do for a new run. 
Currently we fully rely on the environment variables saved in the container image and restart a run with the only one specified environment variable - `RESUMED_RUN`.

At first glance I see the following problems with restarting a run with a whole set of variables:
1. Git cloning of a pipeline repository will fail
2. `launch.sh` will upload inputs more than once
3. ???

I can suggest two options:
1. Configure a list of environment variables that shall be updated for a resumed run and set only this env variables for the container (API_TOKEN, system urls, credentials)
2. Restart run with a full set of variables but made changes to the `launch.sh` to handle it correctly (at least skip repo cloning and data localization tasks)

Which one do you prefer?

**Comment by mzueva** [comment]
@sidoruka I've tested actual deployment and data localization is executed for each restart in the current version as well, so I'd suggest to implement option 2.

**Comment by mzueva** [comment]
Cherry-picked to release 3d64599f6f7137b8fa0ab86c8fa44473b65d8d57
