### ISSUE TITLE
AWS: Global search doesn't work for new added pipeline items

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#583]
**Version**: `0.16.0.2090.34fed25335b16bdeaf05dfa63b56ddd09cbb08a0`

Global search doesn't index a new added pipeline items to AWS stand for more than 30 min

**Step-by-step:**

1. Create a pipeline item (e.g. folder/pipeline/issue)
2. Wait for indexing
3. Search the added item

**Expected**: there is the item in search list result
**Actual**: there is not the item in search list result

![image](https://user-images.githubusercontent.com/23356251/62546724-aeca8f00-b86c-11e9-8510-603600ff3a41.png)

**Comment by mzueva** [comment]
@kamyshova search sync service was down, not it shall work

**Comment by kamyshova** [comment]
Fixed
