### ISSUE TITLE
If one CORS/Policies cannot be applied - object storage creation shall not fail

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#594]
At the moment, if the Cloud service account/role have permissions to create object storages, but lacks permissions to apply CORS or other policies - object storage is created, but API throws an exception and storage is not registered.
This leads to a "zombie" bucket, which is not available via GUI, but exists in the Cloud.

API shall not fail such requests, instead - storage shall be registered. But if any subsequent error occurs - it shall be added to the API response. E.g. some status flag (boolean or enum), that can be parsed by the client.

**Comment by sidoruka** [comment]
@rodichenko, once API part is done - please handle such situations in the GUI and show the warning to the user (as a popup).
```
The bucket {bucket_name} was created, but certain policies were not applied.
This can be caused by insufficient permissions.
```

**Comment by mzueva** [comment]
@rodichenko Server changes are deployed to dev and described [here](https://github.com/epam/cloud-pipeline/pull/605#issue-307651813)

**Comment by rodichenko** [comment]
@sidoruka GUI backported to release/0.15 (4497da5bf0607a9db4b6ea37d646e1ffdc6cd7a1)
