### ISSUE TITLE
"Search" shall not be available to the users if a corresponding service is not installed

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#595]
If "search.elastic.host" is not set - users shall not be able to perform search:
1. Hide the "Search" button from the left menu
2. Disable keyboard search shortcut

**Comment by rodichenko** [comment]
@sidoruka backported to release/0.15 (2795e04779e05308e844ced9dd888b5779e1e687)

**Comment by sidoruka** [comment]
@rodichenko cherry-pick to `release/0.15`
