### ISSUE TITLE
FS mounts creation shall not be available if no FS mount points are registered

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#597]
FS mounts creation shall not be available if no FS mount points are registered for any Cloud Region:

![image](https://user-images.githubusercontent.com/20998291/62942097-45a0c980-bde0-11e9-8eb6-97be6c41e02f.png)

**Comment by sidoruka** [comment]
@rodichenko and cherry-pick to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka backported to release/0.15 (935c9b4c3a66515d147baeda9822315ff4848c1a)

**Comment by NShaforostov** [comment]
Verified (on GCP and AZURE stands)
