### ISSUE TITLE
Very slow operations on the BLOB Fuse mounted directories

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#61]
* Region: westeurope
* BLOB contents: 1 file
* `ls -l`: ~1min+
* `echo 1 > 1.txt`: ~1min+

**Comment by SilinPavel** [comment]
@sidoruka 
I investigated the problem. So with short conclusion it is most likely related to issue described here: https://github.com/Azure/azure-storage-fuse/issues/256
I also should add that it looks like as periodical problems. Some time we have this issue but here are also periods of time when problem gone.

Here are tests that I performed:
- Try to run clear azure node with azure console - Here is no such problem
- Try to mount blobs from this region on the node which contains pipeline - problem appears
- Try to create container in on the node which contains pipeline and mount blobs - problem appears 

After reading issue https://github.com/Azure/azure-storage-fuse/issues/256, I tried to change nameserver value from /etc/resolv.conf to default one, that has clear azure node by default. Once this was done problem disappear.

**Comment by sidoruka** [comment]
Another piece of information on this topic.
https://github.com/Azure/azure-storage-fuse/wiki/3.-Troubleshoot-FAQ states that:

> DNS issues/timeouts - add the Storage account resolution to /etc/hosts to bypass the DNS lookup

**Comment by mzueva** [comment]
@SilinPavel Let's implement manual ip resolution for azure storage account endpoints. During task `MountStorage` get ip address for domain name `${accountName}.blob.core.windows.net` and add it to `/etc/hosts`.
- check the way to manually resolve domain name with a minimum number of dependencies (for debian/centos based OS)
- add each storage account to `/etc/hosts` only once (remember that during pause/resume operations we relaunch `MountStorage` task
- any failure in ip resolution shall not fail task `MountStorage` and the whole run

**Comment by sidoruka** [comment]
@SilinPavel from what I see - DNS resolution works fine only for centos-based images.
Ubuntu(16/18) and Debian do not contain IP address in /etc/hosts

**Comment by SilinPavel** [comment]
@sidoruka As I investigated, this behavior is in place because in Ubuntu images /bin/sh (that is used as default by python subprocess library) is linked to `dash` program instead of `bash` :

```
ls -la /bin/sh
lrwxrwxrwx. 1 <user> <user> .... /bin/sh -> dash
```  
and for centos:

```
ls -la /bin/sh
lrwxrwxrwx. 1 <user> <user> ....  /bin/sh -> bash
```
and in `dash` we have problem with command syntax: 

```
/bin/sh: 1: Syntax error: redirection unexpected
```

So, I suggest to use bash interpreter in force manner

**Comment by sidoruka** [comment]
Verified using Debian 9-based RStudio. Works fine
