### ISSUE TITLE
`pipe`: the `view-runs` command doesn't correctly work with the `-dt` option

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#616]
The `view-runs` command with the `-dt` option doesn't find any eligible runs.
<img width="505" alt="1" src="https://user-images.githubusercontent.com/45459424/63179267-6a9d7280-c054-11e9-9a9a-3c92a0e35af5.png">
Although with the `-df` option works fine.

**Comment by NShaforostov** [comment]
Figured out.
Option `-dt` allows to output runs **_completed_** before specified datetime.  
Since the `view-runs` command outputs by default information about active runs, then for using that command with the `-dt` option - one of the **_completed statuses_** must be specified.

@ekazachkova, can you add the output of the auxiliary message, e.g. `Run status shall be specified in the request`, for the case when user tries to perform the `view-runs` command with `-dt` option but without `-s` option?

**Comment by NShaforostov** [comment]
Verified

**Comment by sidoruka** [comment]
Cherry-picked to `release/0.15` via 96dafe2
