### ISSUE TITLE
GCP: COMMIT feature doesn't work

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#618]
While trying to commit a pipeline run, the error `Error response from daemon: max depth exceeded` throws during the commit task:
![3](https://user-images.githubusercontent.com/45459424/63268345-a9256e00-c29c-11e9-9e81-8aa03dbe0ccd.png)

Accordingly, on-demand runs can't be paused. In those cases - while trying to pause a run, it throws the same error and stops:
![2](https://user-images.githubusercontent.com/45459424/63266507-b9d3e500-c298-11e9-92f4-feb976b9cedb.png)

**Comment by sidoruka** [comment]
@kamyshova is this issue still exists?

**Comment by kamyshova** [comment]
@sidoruka No, I've fixed it
