### ISSUE TITLE
Invalid layout for global search

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#619]
# Description

Global search page is not rendered correctly:
![search](https://user-images.githubusercontent.com/12640002/63372892-ae171a00-c38f-11e9-98fd-4927d5f5f2b7.PNG)

# Steps to reproduce

1. Login to AWS dev environment
2. `Ctrl + F` to enter search mode
3. Enter `test` query

**Comment by rodichenko** [comment]
@mzueva @sidoruka backported to release/0.15 (cf16cee3f4f97a3807ea6752091efb953eff867e)
