### ISSUE TITLE
Cluster run cannot be launched with a Pretty URL 

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#620]
# Steps to reproduce
1. Select any interactive tool (e.g. `library/rstudio`)
2. Open `Custom run settings`
3. Setup cluster of any size (e.g. 1 static node)
4. Set a pretty URL (any valid value, e.g. `pretty`)
5. Launch a run
6. An error `URL pretty is already used for run {ID}`

# Action items
Pretty URL shall be never set for the child runs

**Comment by sidoruka** [comment]
Please backport to `release/0.15`

**Comment by mzueva** [comment]
done
