### ISSUE TITLE
Allow to schedule automatic pause/restart of the jobs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#625]
For certain use cases (e.g. when Cloud Pipeline is used as a development/research environment) users launch jobs and keep them running all the time, including weekends and holidays.
To reduce costs, it shall be possible to set a "Run schedule", that would allow to automatically pause/resume runs, based on the configuration specified.

The following behavior shall be implemented:
1. User (who have permissions to pause/resume a run) shall be able to set a schedule for an active run or a run being launched
2. Schedule shall be defined as a list of rules (user shall be able to specify any number of them):
* Action: Pause or Resume
* Recurrence:
  * Daily: every N days, time
  * Weekly: every N weeks, weekday, time
3. User shall be able to create/view/modify/delete schedule rules anytime run is active (i.e. running or paused)
4. Cloud Pipeline shall not allow to set conflicting rules. I.e. rules that shall perform some operation in the same time
5. This shall be applied only to the "Pausable" runs (i.e. On-demand/Non-cluster)
6. Such a configuration shall be available via the API and GUI. CLI shall not be implemented for now

**Comment by rodichenko** [comment]
@sidoruka GUI part implemented (4eae3ccded0f16e31b18d1fc0c844bc609225eb0)

**Comment by NShaforostov** [comment]
I've tried to verify this feature. Some issues were found:
1. For example, now is Thursday, 15:00. I launched a run
   - I want to pause my run every day at 15:20. So, I created a new schedule rule - `PAUSE: At 15:20, every 1 day`. Today the run is not paused.
   - I want to pause my run every Thursday at 15:30. So, I created a new schedule rule - `PAUSE: At 15:30, on Thursday`. Today the run is not paused.

   Is this behavior correct? I can suppose, probably, that in the first case the run will be paused starting from tomorrow, in the second case - starting from the next Thursday.
Maybe, we should change the approach and include "today" into scheduled days (in described cases) or allow users to select from which day they want to "begin" schedule performing?
2. The weekdays are displaying incorrectly:
   For example, I want to pause my run every Friday at 13:00. I select the `Weekly` recurrence and `Friday` in the corresponding dropdown lists, specify the time and click the OK button to confirm.
**_Exp._**: in the "Maintenance" list the following record appears - `PAUSE: At 13:00, on Friday`
**_Act._**: in the "Maintenance" list the following record appears - `PAUSE: At 13:00, on Saturday`
![image](https://user-images.githubusercontent.com/45459424/74442668-eef57480-4e82-11ea-813e-973ac91f0081.png)

**Comment by rodichenko** [comment]
@NShaforostov as for second part ('The weekdays are displaying incorrectly') - fixed via a4c2fcdb7d082552bb7404e289b9b73711c5eacd

**Comment by NShaforostov** [comment]
@rodichenko, the second part is verified. Works correctly

**Comment by SilinPavel** [comment]
@NShaforostov Seems to me that we should set auth of the user, who created that schedule, to the job to solve this issue, here is a bug #958 for that behavior. Thanks!

**Comment by NShaforostov** [comment]
Other issues of this feature, I've encountered:

a) at the launch page I can configure several schedule rules and uncheck the **Auto pause** checkbox. In this case when launching the run - the warning message appears: `Run {0} marked as nonPause or is cluster run! Skip.` and all set rules get lost. But the **Maintenance** control stays visible at the **Run logs** page. When trying to configure new rules for such run - the same message specified above appears.
There are two ways to fix the issue:
   - if the **Auto pause** checkbox is unticked before launch - the **Maintenance** control and configured rules shall become unavailable and invisible at the **Launch** and **Run logs** pages
   - setting of the **Auto pause** checkbox shalln't influence to the scheduling functionality of the run's pause/resume

   I suppose the second way should be implemented. @sidoruka, tell what is the correct way?

b) if the autoscaled cluster (without default childs) is launched - the **Maintenance** control is displayed at the **Run logs** page. But no rules could be configured, the warning message appears when trying to save rules: `Run {0} marked as nonPause or is cluster run! Skip.`
Suppose this control should be hidden as for other cluster types.

**Comment by NShaforostov** [comment]
Docs were updated via #991
