### ISSUE TITLE
AWS: Pipeline run InitializeNode task fails 

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#635]
**Version**: `0.16.0.2414.e9bb9588ac71c5dadd3ad76084f16329e75f036a`

When user launches a pipeline with **`spot`** price type run **`InitializeNode`** task fails with `[ERROR] Exceeded retry count (100) for spot instance. Spot instance request status code: capacity-not-available.` error. 

It looks like this:

![image](https://user-images.githubusercontent.com/23356251/64425063-73152600-d0b3-11e9-9251-3f6ffc0f4b80.png)

**Comment by mzueva** [comment]
Fixed this issue: in this case we shall make N attempts to create a spot instance and then switch to on-demand price type.

**Comment by sidoruka** [comment]
Backport to `release/v0.15`

**Comment by sidoruka** [comment]
Cherry-picked to `release/0.15` via ccf3baa

**Comment by sidoruka** [comment]
@kamyshova could you please check the fix?

**Comment by kamyshova** [comment]
@sidoruka Fixed
