### ISSUE TITLE
Broken layouts

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#643]
Some of the page layouts are broken:

![image](https://user-images.githubusercontent.com/20998291/64480402-b49af380-d1cf-11e9-9c7c-8fe3f25a8ea1.png)

#274 
![image](https://user-images.githubusercontent.com/20998291/64480413-c8465a00-d1cf-11e9-9a76-056aa2c199f5.png)

![image](https://user-images.githubusercontent.com/20998291/64480420-06437e00-d1d0-11e9-8246-ddba1eeff3dd.png)

**Comment by sidoruka** [comment]
Backport to `release/0.15` if these issues affect it

**Comment by rodichenko** [comment]
@sidoruka backported to release/0.15 (c7384df277091fbcd363324844d7f1e7e8b6b293)
