### ISSUE TITLE
Incorrect metadata displaying 

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#644]
**Version**: `0.16.0.2440.215fd7abe5a2a5d2586e4ff8b088dfd3608a56e8`

It looks like that metadata layout was broken. 
When clicking a `Sample` object, we go to the page looks like this:

![image](https://user-images.githubusercontent.com/23356251/64531685-bcb27a80-d318-11e9-97c0-271c788b3175.png)

Besides, when I click on `the settings` button, I receive the following result

![image](https://user-images.githubusercontent.com/23356251/64531927-27fc4c80-d319-11e9-8761-bf6b8cdf93b6.png)

instead of this:

![image](https://user-images.githubusercontent.com/23356251/64531981-45311b00-d319-11e9-9952-899f0dff04da.png)

**Comment by rodichenko** [comment]
@kamyshova fixed with **react-table** of version **6.7.6**, can you re-check please?

**Comment by rodichenko** [comment]
@sidoruka backported to release/0.15

**Comment by kamyshova** [comment]
@rodichenko Fixed. Thanks!
