### ISSUE TITLE
Rename GitLab's repository if the name of the Pipeline is changed

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#645]
At the moment, if the `Pipeline` is renamed - the underlying gitlab repository keeps the previous name.

We shall:
* Research is it feasible to rename the gitlab repo (without the side-effects)
* Research if the current mapping of the Cloud Pipeline permissions to the GitLab roles - allows renaming the repositories
* If so - implement this feature: 
  * Rename the GitLab repo if the Cloud Pipeline `pipeline` is renamed
  * GUI shall display a notification, when such operation is performed: `This operation will change the clone/pull/push URL. If this pipeline was used somewhere - make sure to change the remote address`

**Comment by mzueva** [comment]
@Wedds Please, check whether Gitlab CE has API to rename repository/project and if it works correctly on our version.

**Comment by mzueva** [comment]
@Wedds `PipelineManager.update` method shall check if name of pipeline has actually changed and rename underlying gitlab repository as well. Notes:

- Method to rename gitlab repository shall be added to `GitManager` and `GitClient` classes.
- Do not forget to update `Pipeline` fields `repository` and `repositorySsh` fields after renaming of repository
- If process of repository renaming fails, all db changes shall be reverted
- Use `issue_312_gitlab_changes_on_behalf_of_user` as a base branch as it introduces significant changes in gitlab integration code

**Comment by mzueva** [comment]
@sidoruka deployed to dev

**Comment by sidoruka** [comment]
Works great
@NShaforostov please proceed with the docs update

**Comment by NShaforostov** [comment]
Verified.

> Works great
> @NShaforostov please proceed with the docs update

Docs updated via #807
