### ISSUE TITLE
Track the confirmation of the "Blocking" notifications

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#646]
# Background

At the moment, "Blocking" notifications require the user to click the `Confirm` button before proceeding with the GUI operations.

This action is tracked only within the local workstation and is not passed to the API.

In certain cases, it is handy to be able to check which users confirmed the notification.

# Action items

## API

* API shall expose `/notification/confirm` method. This method shall accept (all the attributes are required):
  * notificationId
  * title
  * body
* This information shall be placed into the user's profile (user metadata) as a json object with the `confirmed_notifications` key (the name of the key shall be configurable via `Misc/system.events.confirmation.metadata.key` preference)
* JSON object shall be of the following structure:
```
[
  {   
    "notificationId": "123" ,
    "title": "Confirmed title",
    "body": "Confirmed body",
    "user": "USER_NAME",
    "date": "date/time of the confirmation"
  },
  {   
    "notificationId": "456" ,
    "title": "Confirmed title 2",
    "body": "Confirmed body 2",
    "user": "USER_NAME",
    "date": "date/time of the confirmation"
  }
]
```
* Each `/notification/confirm` shall add a new entry in the JSON array, we shall not overwrite or change the existing entries in any means

## GUI

* In addition to the current behavior, GUI shall call `/notification/confirm` method when the `Confirm` button is clicked and pass the required information to the server
* If the `/notification/confirm` method failed - notification shall closed but treated as UNCONFIRMED (i.e. we shall not set it's status to the `localstorage`) and showed once again (according to the refresh schedule)
* To make the confirmation information easy to view - we shall add the JSON viewer capabilities to the user's profile metadata:
  * When rendering the user's profile metadata - we shall check, if the content is a JSON object
  * If so - calculate number of entries in the object (either a single object or an array of objects) and show the hyperlink `N entries` as a value of the metadata key
![image](https://user-images.githubusercontent.com/20998291/65033394-93fc3780-d94d-11e9-92ad-28dca3073e3a.png)
  * If the hyperlink is clicked - JSON entries shall be displayed as a table (we shall parse only 1st level attributes)
![image](https://user-images.githubusercontent.com/20998291/65033896-9e6b0100-d94e-11e9-9966-f964b0de494d.png)
  * When viewing a table, user shall be able to switch to the `raw` JSON view and edit the contents
![image](https://user-images.githubusercontent.com/20998291/65033909-a3c84b80-d94e-11e9-9316-15cab24022ca.png)

**Comment by sidoruka** [comment]
This feature shall be backported to `release/0.15`

**Comment by sidoruka** [comment]
Moved to `release/0.15` via 354bd89d48830b7340fe487820ec68b7f97b5fb3 e141b71206a8be74cd5c9a28d0296c180f1b403e 6f7f5ea3c44087b00df8c551dc533e3c43664f28

**Comment by sidoruka** [comment]
@NShaforostov please add this feature to the `0.15` release notes and [User attributes info page](https://epam.github.io/cloud-pipeline/manual/12_Manage_Settings/12.4._Edit_delete_a_user/#attributes)

**Comment by NShaforostov** [comment]
Corresponding doc was added by 191d0a606fc955964adbd508ffbb2215d17305bd to #650
