### ISSUE TITLE
`git-sync` shall not fail the whole object synchronization if a single entry errors

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#648]
When the `git-sync` script processes a repository and fails to sync specific user permissions (e.g. git exception is thrown) - the subsequent users are not processed for that repository.

Please make the repository sync routine not to fail if a single user cannot be synced (but keep the logs)

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka backported to release/0.15 (ea50e4b47ec1825e229bbf9bea6580d509c48646)
