### ISSUE TITLE
Incorrect behavior of the "Limit mounts" form

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#667]
### Case 1
1. Open "Select data storages to limit mounts" form (from the Launch page or the Pipeline Configuration page)
2. Click the "Clear selection" button
3. Click the "Select all" button
4. Uncheck some checkboxes
5. Click the "OK" button

**_Exp._**: only checked storages are shown at the "Limit mounts" field
**_Act._**: "All available storages" is shown at the "Limit mounts" field

### Case 2
1. Open "Select data storages to limit mounts" form (from the Launch page or the Pipeline Configuration page)
2. Click the "Clear selection" button
3. Click the "Select all" button
4. Uncheck some checkboxes
5. Click the "Clear selection" button

**_Exp._**: all checkboxes are unchecked
**_Act._**: rows, which checkboxes were unchecked at step 4, disappear

**Comment by rodichenko** [comment]
@NShaforostov @sidoruka fixed, backported to release/0.15 (e02d4938c132803c9446801c7702088acb706713)

**Comment by NShaforostov** [comment]
@rodichenko Described bugs fixed.
But another one appears:
1. Open "Select data storages to limit mounts" form (from the Launch page or the Pipeline Configuration page)
2. Click the "Clear selection" button
3. Try to check any checkbox
_Exp._: clicked checkboxes become "checked"
_Act._: clicked checkboxes are still unchecked
4. Click the "OK" button

**_Exp._**: only checked storages are shown at the "Limit mounts" field
**_Act._**: "Limit mounts" field turned into the line

**Comment by rodichenko** [comment]
@NShaforostov fixed, can you re-check please?

**Comment by NShaforostov** [comment]
Verified
