### ISSUE TITLE
Cannot view contents of the tar.gz downloaded from the FSBrowser

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#671]
Related to #223

If a directory is downloaded via the FSBrowser (as a tar.gz) - it cannot be viewed using Linux or MacOS. 

`Permission denied` is thrown. It seems that `tar.gz` is configured to keep the original permissions. We shall, probably, drop them.

**Comment by ekazachkova** [comment]
Fixed: added permissions `-rwxrwxr--` to files into archive.
This action doesn't affect permissions for original files.
Extracted files have `-rwxrwxr--` permissions and current user as owner.
@sidoruka  could you check this fix?

**Comment by sidoruka** [comment]
looks good
