### ISSUE TITLE
FSBrowser shall (optionally) follow symlinks when packing directory into tar.gz

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#672]
Related to #223

If a directory, containing symlinks, is downloaded - the resulting tar.gz will contain a "broken" symlink (i.e. pointing to the compute node's location).

We shall add an option to the FSBrowser server startup, which allows to follow to skip the symlinks. Default behavior is "follow"

**Comment by ekazachkova** [comment]
Fixed
@sidoruka could you check?

**Comment by sidoruka** [comment]
nice
