### ISSUE TITLE
Git sync script fails when registered user from CP doesn't have email adress

### ISSUE THREAD

**Issue by SilinPavel** [epam/cloud-pipeline#691]
It seems that git sync script fails when it tries to sync gitlab with CP server, that has registered user without email.

Steps to reproduce:
1. Create new user in the CP
2. see logs from git-sych pod

expected: user without email is skipped 
actual: error message 
```
Error:  Traceback (most recent call last):
  File "/opt/api/scripts/git-role-management/internal/synchronization/pipeline_server.py", line 42, in synchronize
    emails = map(lambda x: x.email.lower(), self.__users__)
  File "/opt/api/scripts/git-role-management/internal/synchronization/pipeline_server.py", line 42, in <lambda>
    emails = map(lambda x: x.email.lower(), self.__users__)
AttributeError: 'NoneType' object has no attribute 'lower'

```

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by sidoruka** [comment]
#648 related

**Comment by rodichenko** [comment]
@SilinPavel @sidoruka fixed. Backported to release/0.15 (6205470720ed56286f90f98963a2d4682b045ee4)

**Comment by sidoruka** [comment]
@SilinPavel could you please confirm the fix?

**Comment by SilinPavel** [comment]
@sidoruka @rodichenko works well for now
