### ISSUE TITLE
"pipe" shall consider current API version

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#697]
**Background**
At the moment, Cloud Pipeline CLI does not consider the API server version. It would be nice to show the server's version to the user and consider it when performing the update

Previously, there was no option to get the API server version, but this is going to be introduced by #696

**Approach**
- Before performing the actual download/update of the `pipe cli` version (introduced by #589 #615) - we shall check if the update is required. If a current version is greater or equal to the server's - notify the user and do not perform anything. Version check shall NOT consider the commit hash, only `major/minor/build` parts
- `--version` shall display the server's version (if `pipe cli` is configured, otherwise - skip this step).

**Comment by NShaforostov** [comment]
I've tried to verify this feature.
I got the "old" version 0.16.0.2938.b39e1318156277bf71fa30a84ca98506f20522ce and tried to update to version 0.16.0.3090.6ed66ee576c8fc0496b7b4f3a9c8f36dfb06606d:
- In Windows the `pipe update` command worked well.
- In Linux (WSL Ubuntu 18.04):
  - trying to perform the command `pipe update` (call by the command name) from the `home` directory threw the error `Error: [Errno 21] Is a directory: '/home/<USER_NAME>/pipe'`. **Update didn't perform**
  - trying to perform the command `pipe update` (call by the command name) from any other directory threw the error `Error: [Errno 2] No such file or directory: '<PATH>/pipe'`. **Update didn't perform**
  -  trying to perform the command `pipe update` from the `pipe` directory worked well. Update has performed

Also in both - Windows and Linux (WSL Ubuntu 18.04):
- displaying of the server's version via `--version` works fine
- checking of the update required works fine

**Comment by sidoruka** [comment]
@mzueva @ekazachkova please take care of this, once you'll have time

**Comment by mzueva** [comment]
@NShaforostov fixed via #776

**Comment by NShaforostov** [comment]
Verified. Works fine

**Comment by NShaforostov** [comment]
Added to docs via #807
