### ISSUE TITLE
Get node disk statistics from Elasticsearch

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#707]
**Background**
With merge of #306 API will have an option of retrieving node usage statistics from Elasticsearch rather than from CAdvisor endpoint. But we still use CAdvisor for disk usage check while launching a new run or committing a docker image. It would be great to have an option to get disk usage from Elasticsearch as well.

**Approach**

- Introduce a new method `getDiskAvailableForDocker` to `UsageMonitoringManager` interface and provide its implementation for `ESMonitoringManager` class. 

- Do not forget to implement logic of determine which disk is actually mounted to pod (check `CAdvisorMonitoringManager` implementation)

- Replace two beans `CAdvisorMonitoringManager` and `ESMonitoringManager` with one `UsageMonitoringManager` using `ConditionalOnProperty` annotation.

**Comment by sidoruka** [comment]
@SilinPavel @mzueva if this is implemented - please apply a correct `status` label
