### ISSUE TITLE
AWS: Auto pause doesn't work

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#717]
When user sets auto pause preferences its doesn't work for pipeline runs.

**Steps to reproduce the behavior:**
1. Login as admin
2. Open system "Settings" window
3. Select "Preferences" tab
4. Click on "System" menu item in the left panel
5. Input into "system.max.idle.timeout.minutes" field value "2"
6. Input into "system.idle.action.timeout.minutes" field value "2"
7. Input into "system.idle.cpu.threshold" field value "30"
8. Input into "system.idle.action" field value "PAUSE"
9. Click "Save" button, click "OK" button
10. Navigate to launch page any tool
11. In "Advanced" section click on "Price type" dropdown list and select "On-demand" item
12. Check that "Auto pause" checkbox below "Price type" dropdown list is enabled
13. Click "Launch" button

**Expected behavior**
Run launched at step 13 is paused and has "RESUME" hyperlink opposite its name

**Environment:**
 - Cloud Provider:  **AWS**
 - Version: **0.16.0.2862**
 - Browser: **chrome**

**Comment by SilinPavel** [comment]
@kamyshova Should be fixed with #718

**Comment by kamyshova** [comment]
@SilinPavel Fixed
