### ISSUE TITLE
SSH_PASS is not set for the resumed jobs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#719]
**Describe the bug**
`SSH_PASS` environment variable is empty, when the run is resumed

**To Reproduce**
1. Run a job and verify the `SSH_PASS` variable (e.g. `kubectl describe po pipeline-N`) is set correctly
2. Pause and resume a job
4. `SSH_PASS` is set to an empty value

**Expected behavior**
It is expected, that the `SSH_PASS` value is set to the previous value

**Environment:**
 - Cloud Provider: N/A
 - Version: 0.16.0.2877.ddc9c1e5f7ffec93edd29b1dcfb5bff353340e7f
 - Browser: N/A

**Additional context**
It is also observed, that the API `/run/{run_id}` request returns a correct value of the `sshPass`.

**Comment by sidoruka** [comment]
@mzueva if you prove, that this is a `bug` - please backport the fix to `release/0.15`

**Comment by mzueva** [comment]
@sidoruka fixed and backported to `release/0.15`

**Comment by NShaforostov** [comment]
Verified
