### ISSUE TITLE
The "DATA" section of Global Search results doesn't display

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#721]
**Describe the bug**
An error occurs when trying to view the "DATA" section of Global Search results.

**To Reproduce**
1. Open the Global Search bar
2. Specify into the search bar any existing object storage name
3. Click the "DATA" button of the search menu
4. See the error `Missing index name for type: GS_FILE`

**Expected behavior**
Object storage list appears in the search results

**Screenshots**
![1](https://user-images.githubusercontent.com/45459424/66319236-72c3b100-e925-11e9-9a22-5d91d903c672.png)

**Environment:**
 - Cloud Provider: AWS, Azure
 - Version 0.16.0.2884.36584cc87d77ffe624ccdbc0a72ffefd39c981dc
 - Browser: Chrome

**Comment by mzueva** [comment]
Fixed, it was configuration problem of dev stand.

**Comment by NShaforostov** [comment]
Verified
