### ISSUE TITLE
IDLE/Pressure tags shall not be applied to the paused runs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#728]
**Background**
With the #624 implementation, we can see which jobs are idle or under resource pressure. But there is a confusion with the PAUSED runs. E.g. if a job was used, while idle - the `IDLE` tag will be shown for the user, but this is not true as the node is stopped and cannot be idle or under pressure.

**Approach**
Let's drop the `IDLE` and `PRESSURE` tags when a job is being paused (it seems similar to the endpoints URLs)

**Comment by NShaforostov** [comment]
Verified
