### ISSUE TITLE
Runs tags lowercase

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#729]
**Describe the bug**
Run tags are shown in lower case in the `Instance` properties header, while it is shown uppercase in the other locations

**To Reproduce**
1. Go to the run details form for the IDLE or PRESSURE job
2. Review the tag in the `Instance` properties header
3. Expand the `Instance` properties header
4. Review the tag in the `Instance` properties details

**Expected behavior**
Tag name shall be in uppercase in the `Instance` properties header

**Screenshots**
![image](https://user-images.githubusercontent.com/20998291/66474384-e1298000-ea99-11e9-94c9-c6c31cc2b807.png)
![image](https://user-images.githubusercontent.com/20998291/66474400-e8e92480-ea99-11e9-9854-7daa1e3f7deb.png)

**Environment:**
 - Cloud Provider: NA
 - Version: 0.16.0.2922.82f3ed9ab770d3803ed5bc22eccd5ad9950894d6
 - Browser: chrome

**Additional context**
Introduced by #624

**Comment by NShaforostov** [comment]
Verified. Fixed
