### ISSUE TITLE
Fine tune the resource usage form

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#731]
**Background**
As the #168 is implemented, let's consider a number of cosmetic/ux improvements to the resource monitoring form

**Approach**
1. When the `Live Update` is unticked - remove the `End` period limit, so we'll get all the history
2. Do not update the view the chart is clicked
3. Sort disks by the device name
4. When zooming-in - request left/right regions as well to make the chart look more smooth

**Comment by NShaforostov** [comment]
Verified
