### ISSUE TITLE
EDGE shall allow to limit the number of concurrent SSH sessions

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#734]
**Background**
At the moment, Web SSH performance will degrade if 1000+ SSH sessions are established via EDGE service.
While it is not common, but it's critical as it affects all the users.

**Approach**
Introduce a parameter for the EDGE server (with a default of `25`), that will allow to control a number of simultaneous SSH connections to a single job.

**Comment by sidoruka** [comment]
The limitation can be now controlled via `CP_EDGE_MAX_SSH_CONNECTIONS` pipectl parameter

**Comment by sidoruka** [comment]
Moved to `release/0.15`

**Comment by NShaforostov** [comment]
Verified
