### ISSUE TITLE
Remove python environment requirement from the CLI install instructions

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#735]
**Background**
At the moment, Cloud Pipeline CLI settings dialog tells the user, that `Python 2 or Python 3 environment is required to run CLI` but this is not true for `Windows` and `Linux`.

**Approach**
1. Remove `Python 2 or Python 3 environment is required to run CLI` notification from the web-form
2. Add corresponding notification for the `Other` option via `ui.pipe.cli.install.template` preference

**Comment by sidoruka** [comment]
@rodichenko please take care of (1) and backport to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka part 1 is implemented, backported to `release/0.15`

**Comment by sidoruka** [comment]
part (2) done and backported to `release/0.15` via 3aa767d and 
81080b7
