### ISSUE TITLE
EndDate isn't set when terminate node of a paused run

### ISSUE THREAD

**Issue by SilinPavel** [epam/cloud-pipeline#743]
**Describe the bug**
When user terminate node of a paused run `endDate` for that run isn't set.

**To Reproduce**
1. Run new pipeline
2. Wait until it will be paused
3. Click `TERMINATE` button on a Run View page
4. Request information about this run with swagger or other tool, observe that `endDate` is not set

**Expected behavior**
`endDate` set to value when node was terminated

**Additional context**
This bug leads to wrong running time for this kind of runs. In this case running time will be calculated as `current time` - `startDate`

**Comment by sidoruka** [comment]
@SilinPavel is it `0.16` only issue or `0.15` shall be also fixed? If so - backport to `release/0.15` branch please

**Comment by SilinPavel** [comment]
@sidoruka it is also related to 0.15

**Comment by mzueva** [comment]
@sidoruka cherry pick to `release/0.15` ad72c4f0
