### ISSUE TITLE
AWS: Nodeup retry process may stuck when first attempt to create a spot instance failed

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#744]
**Describe the bug**
We observer the following behaviour when running AWS spot instances:

1. First nodeup attempt creates SpotRequest, waits for its fulfilment, finds created instance and waits for instance running state and connection on 8888 port
2. Connection on 8888 port is not available in exepected amount of attempts and current 
 nodeup attempt is failed, instance is terminated.
3. Second nodeup attempt starts, it finds existing SpotRequest by run id, checks its status (fullfilled) and starts to wait for the same instance (associated with SpotRequest) to be up. This will never happen since instance is already in terminating state.

**Expected behaviour**
We shall check that instance associated with SpotRequest is in appropriate status, if not - create a new SpotRequest and start nodeup process from scratch.

**Environment:**
 - Cloud Provider: AWS
 - Version  0.15.0.2994

**Comment by sidoruka** [comment]
Cancel spot request when terminating a node

Please backport to `release/0.15`
