### ISSUE TITLE
Wrong pipeline info layout in the Library dashboard

### ISSUE THREAD

**Issue by NewOlya** [epam/cloud-pipeline#747]
**Describe the bug**
The pipeline description displays incorrectly when both "Attributes" and "Issues" controls are displayed at the Library dashboard 

**To Reproduce**
1. Go to the "Library" 
2. Create a new pipeline
3. Click on created pipeline
3. Click on "Displays" icon
4. Mark both "Attributes" and "Issues" controls 
4. See the wrong layout of the "New pipeline initial commit" header

**Expected behavior**
The system shall cut the string and display the "..." symbols

**Screenshot**
![Pipeline bug](https://user-images.githubusercontent.com/32195393/66923438-79db7500-f031-11e9-89da-ac3374b4eb23.png)

**Comment by NewOlya** [comment]
There is another place with the same problem.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to the "Cluster nodes" dashboard
2. Find the "Pipeline" column

**Screenshot**
![layout bug](https://user-images.githubusercontent.com/32195393/70620101-6c083180-1c27-11ea-93e4-dc4c1a6fd84f.png)

**Comment by rodichenko** [comment]
@NewOlya can you re-check this issue please?

**Comment by NShaforostov** [comment]
@rodichenko verified:
- the original issue is fixed
- the additional problem from the comment is fixed too
