### ISSUE TITLE
Extend vm-monitor's supported events

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#757]
**Background**
At the moment, Cloud Pipeline can notify the platform's admins only about the "lost" compute nodes. 
There is also a number of the events, that shall be sent to the admins ASAP:
* If one of the Cloud Pipeline's services changes it's state (i.e. goes down or up)
* If one of the certificates is going to expire in N days (shall be configurable)

**Approach**

*Readiness*
* VM-Monitor shall check the `AVAILABLE` count the Kube deployments and compare to `DESIRED`
* If `AVAILABLE` is less than `DESIRED`, a notification shall be fired
* The list of the deployments shall be configurable, with the following defaults:
  * cp-api-db 
  * cp-api-srv
  * cp-notifier
  * cp-git
  * cp-git-sync
  * cp-edge
  * cp-docker-registry
  * cp-docker-comp
  * cp-clair
  * cp-search-elk
  * cp-search-srv
  * cp-heapster-elk
  * cp-heapster
  * cp-share-srv
  * cp-dav

*PKI expiration*
* VM-Monitor shall check all the PKI assets, available for the platform
* A list of the directories shall be configured as the list of `cp-config-global` configmap parameters (e.g. `CP_SHARE_SRV_CERT_DIR`)
* The following defaults shall be scanned:
  * `CP_SHARE_SRV_CERT_DIR`
  * `CP_EDGE_CERT_DIR`
  * `CP_DOCKER_CERT_DIR`
  * `CP_IDP_CERT_DIR`
  * `CP_GITLAB_CERT_DIR`
  * `CP_API_SRV_CERT_DIR`
  * `CP_COMMON_CERT_DIR`
* VM-Monitor shall traverse the specified directories and verify the `*.pem` files' expiration date (mask shall be configurable)
* If the expiration date is less than `now() - days_to_notify` - a notification shall be fired (notification shall include the path of the PKI file and it's CN + SAN)
* `days_to_notify` shall be configurable

**Comment by sidoruka** [comment]
This shall be made available in `release/0.15` as well

**Comment by mzueva** [comment]
@Wedds 
Please, implement a second part of this task:
Add a new scheduled task to `VMMonitor` service. This task shall list all folders provided in application properties, find files matching *.pem extension and validate/notify according to the description above.

**Comment by NShaforostov** [comment]
Docs were updated via #860
