### ISSUE TITLE
Update k8s deployment specs for Elasticsearch

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#758]
**Background**
Related to search issues described in #596. Current Elasticsearch deployment seems to be unstable due to memory management problems (JVM heap is not cleaned properly).

**Approach**
We shall updated k8s deployment specs for Elasticsearch to use official docker image with updated JVM and ES versions.

**Comment by sidoruka** [comment]
Please move to `release/0.15` as well
