### ISSUE TITLE
Unified error message for storage tags operations

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#76]
Currently, different cloud providers has different error messages on `datastorage/{id}/tags` API methods. This is a problem because some CP CLI integration tests require the error messages to be unified.

For example, on updating tags of a non-existing storage item different messages are returned for each Cloud Provider:
- `AWS` - *Path 'non_existing_path' doesn't exist.*
- `AZURE` - *Azure item 'non_existing_path' does not exist.*
- `GCP` - *Google Storage path 'non_existing_path' for bucket 'bucket_name' not found.*

Probably, the problem exists for other datastorage endpoints not only the tagging related.

**Comment by mzueva** [comment]
Integration test passed
