### ISSUE TITLE
Cloud Pipeline shall allow users to generate spendings reports

### ISSUE THREAD

**Issue by NewOlya** [epam/cloud-pipeline#761]
### Background
It would be convenient to implement the feature of global spendings control and management that could include the following capabilities:
- generate and view spending reports (tables and charts)
   - for different time periods (e.g. month/quarter/year, etc.)
   - for different spending sources (e.g. storages, launched compute instances, launched tools, etc.)
   - for different levels (e.g. whole platform, by specific user(s), by specific group(s))
   - with differences depending on the access level (admin/user)
- download spending reports to the local workstation - in the table view (`*.csv` format)
- configure spending quotas
   - for different time periods (e.g. day/month/quarter/year)
   - for different levels (e.g. whole platform, specific user, specific group)
- configure platform actions when these quotas are exceeded (e.g. notify, stop runs, block user)
- configure automatic notifications sending about current spending and approaching to the quotas

### Approach
For these features, the new page shall be implemented, that would be available from the new item of the main Cloud Pipeline menu (e.g. named "**Reports and quotas**"). This page should contain 2 tabs (as it's implemented at the "Runs" page):
- "**Spending reports**" tab, where users can view/generate and download different spending reports according to their access level (_more details will be described in the following comments to this issue_)
- "**Quotas**" tab (invisible for general users), where admins can configure spending quotas, platform actions on quotas exceeding and sending notifications about current spending (_more details are described in the_ #762)

The "Spending reports" tab should be displayed by default.

**Comment by NewOlya** [comment]
For the beginning, the general description of report pages and what they should contain:

#### Types and permissions
Users can view (generate) reports according to their permissions:
- admins - all report types (over the whole platform / specific billing center(s) / specific user group(s) / specific user(s))
- users with special permissions on billing center(s) - reports on available billing center(s) and on actions of users that are related to that billing center(s)
- other users - only reports on their actions

#### Report toolbar
Report toolbar shall contain the following controls:
1. The control that allows to select a current time period for the report (let's call it a "period selector"). Possible values should be:
   - **Month** (by default) - the current month to date. Data should be aggregated by days
   - **Quarter** - the current quarter of the year to date. Data should be aggregated by days
   - **Year** - the current year to date. Data should be aggregated by months
   - **All** - all time period of the platform usage (since the beginning of spending logs). Data should be aggregated by months
   - additional **Calendar** sub-control that allows to select another "identical" time period (not just the current one) according to the specified by the period selector:
     - if **Month** is selected - by the "Calendar" sub-control the user can select any one month (without days) of any year from the beginning of spending logs till now
     - if **Quarter** is selected - by the "Calendar" sub-control the user can select any one quarter (without months/days) of any year from the beginning of spending logs till now
     - if **Year** is selected - by the "Calendar" sub-control the user can select any one year (without quarters/months/days) from the beginning of spending logs till now
     - if **All** is selected - the "Calendar" sub-control is disabled
2. The control that allows to select the specific billing center(s)/user group(s) or user(s). By default, all available centers/groups/users shall be selected. This control should be invisible to general users.
3. The control to download a data of displayed report in `*.csv` format to the local workstation.

#### General report table
Each report shall contain the summary general table with the following data:
- current and previous periods:
   - if the selected time period is **Month** then
     - the current period is the period from the first current month day to the current day
     - the previous period is the period from the first day of the previous month to the same day as the current, but of the previous month
     - e.g. today is 26.12.2019, so the current period is _1-26 December, 2019_, the previous period is _1-26 November, 2019_
     - e.g. today is 31.03.2019, so the current period is _1-31 March, 2019_, the previous period is _1-28 February, 2019_ (because on "non-existent" days, spendings also don't exist)
     - if any month other than the current one is selected by the "Calendar" sub-control, then:
       - the "current" period is the period from the first day to the last day of the selected month
       - the "previous" period is the period from the first day to the last day of the month previous to the selected
   - if the selected time period is **Quarter** then
     - the current period is the period from the first current quarter day to the current day
     - the previous period is the same period as the current one, but of the previous year
     - e.g. today is 26.08.2019, so the current period is _Q3, 1 July-26 August, 2019_, the previous period is _Q3, 1 July-26 August, 2018_
     - if any quarter other than the current one is selected by the "Calendar" sub-control, then:
       - the "current" period is the period from the first day to the last day of the selected quarter
       - the "previous" period is the period from the first day to the last day of the same quarter, but of the year previous to the selected
   - if the selected time period is **Year** then
     - the current period is the period from the first current year day to the current day
     - the previous period is the same period as the current one, but of the previous year
     - e.g. today is 26.08.2019, so the current period is _1 January - 26 August, 2019_, the previous period is _1 January - 26 August, 2018_
     - if any year other than the current one is selected by the "Calendar" sub-control, then:
       - the "current" period is the period from the first day to the last day of the selected year
       - the "previous" period is the period from the first day to the last day of the year previous to the selected
   - if the selected time period is **All** then
     - the current period is the period from the first day of the platform usage (since the beginning of spending logs) to the current day
     - the previous period is unavailable
- summary current spendings according to selected configurations in the toolbar (from the period beginning to the current date)
- summary spendings for the same previous time period
- the difference between the current period and the previous one in percentage with a certain mark to determine whether spendings grow or reduce
- current spending quota according to selected configurations in the toolbar (_if it's available_)
- spending quota for the same previous time period (_if it's available_)

The summary spendings value shall be highlighted if it has exceeded the quota.
The report shall be automatically updated after the user changes any values in the controls described above.

#### Charts & tables
_See following comments_

**Comment by NewOlya** [comment]
## User journey

### The main spending reports dashboard
The user shall have the ability to open the spending reports dashboard from the main menu on the left side of any Cloud Pipeline page.
On the main spending reports dashboard, the user can see:
- **Report toolbar** and **General report table** (_see previous comment_)
- 3 kinds of charts:
   - The summary spendings line chart
   - The spendings bar chart with the resource division
   - The spendings bar chart with the billing centers' division

The default time period is a month.
Sample layout:
![image](https://user-images.githubusercontent.com/45459424/71442803-87d80100-2718-11ea-94f5-f2a2c5a75ddb.png)

**The summary spendings chart**
- On this chart, the user can see two lines: summary spendings with accumulation over the previous and the current time periods.
   - if data for the previous period is completely absent, this line should not be drawn
- There should be a slice line on the current date: on its intersection with the "current" chart line, the amount of money which was spent from the beginning of the period to the current date shall be displayed and on its intersection with the "previous" chart line - the amount of money which was spent for the same previous time period.
   - if any time period other than the current one is selected by the **Calendar** sub-control, a slice line should not be drawn
- The user shall have the ability to hover any point of the "current"/"previous" line of the chart - the summary spendings at the corresponding datetime shall appear
   - the aggregation value of timeline division for "Month"/"Quarter" time periods should be 1 day
   - the aggregation value of timeline division for "Year"/"All" time periods should be 1 month
- The user can see the Quota line to compare how the current spendings meet the planned budget.
- For different users, the summary spendings chart shall be displayed:
   - for admins - over the whole system
   - for users with special permissions on billing center(s) - summary spendings over billing center(s) available for these users
   - for other users - summary spendings of themselves

Example of summary spendings chart if the previous period is less than the current (for "month" time period):
![image](https://user-images.githubusercontent.com/45459424/71421288-fbcbc800-268a-11ea-81a2-da84fd7e26c6.png)

Example of summary spendings chart if the selected time period is "quarter":
![image](https://user-images.githubusercontent.com/45459424/71421549-95e04000-268c-11ea-921c-97bf46544b44.png)

Example of summary spendings chart if the selected time period is "year":
![image](https://user-images.githubusercontent.com/45459424/71422039-f15ffd00-268f-11ea-87f5-56c5d5ce7b38.png)

Example of summary spendings chart if the time period is "year" and selected other year than the current by the "Calendar" sub-control:
![image](https://user-images.githubusercontent.com/45459424/71443400-cb803a00-271b-11ea-80bf-06a8aea0edf1.png)

**The spendings bar chart with the resource division**
- On this chart, the user can view the division of summary spendings in a selected time period over the resource groups.
- This bar chart has 2 groups of data: **Storages** and **Compute Instances**.
As far as Cloud Pipeline has 2 types of Storages - Object and File, the user can see both of them in the chart. The same with Compute Instances. The user can see 2 kinds: CPU and GPU separately. As spendings for both these groups are strongly different, there should be the own vertical axis for each one - separately for Storages and separately for Compute Instances.
- For each resource, the summary spendings for the same previous period should be presented as well.
- For different users, this bar chart shall be displayed similarly as **The summary spendings chart** (see above).

For viewing the detailed information about some resource spendings (e.g. only for "Storages" or "CPU instances"), the user shall have the ability to click the corresponding bar header or just bar itself to load detailed subreports (see below).

**The spendings bar chart with the billing centers' division**
- On this chart, the user can view the division of summary spendings in a selected time period over the billing centers.
- The system shall display only top `N` most costly billing centers. This count should be configured via the system preferences.
- For each displayed center, the summary spendings for the same previous period should be presented as well.
- For different users, this chart shall display:
   - for admins - top `N` most costly billing centers from the whole system
   - for users with special permissions on billing centers - top `N` most costly billing centers from billing centers available for these users. If the user has permissions only on a single billing center is available, this chart should not be displayed
   - for other users - this chart should not be displayed

**Download report**
If the user clicks the "Download report" button, the report in `*.csv` format shall be automatically downloaded to the local user workstation. The report shall have the following structure:
![image](https://user-images.githubusercontent.com/45459424/70708039-a555a580-1cea-11ea-917a-dced31a7a8ad.png)
Where:
- **`t_1`**, **`t_2`**, … - columns for specifying time points according to the selected time period (for the month/quarter time period - time point should be 1 day, for the year/"all" time period - time point should be 1 month)
- **`t_current`** - the column for specifying the current time point
- **`t_end`** - the column for specifying the end time point of the selected time period
- **`storages`** - the column for specifying the summary spendings on storages usage (for both - Object and FS)
- **`object_storages`** - the column for specifying the summary spendings on Object storages
- **`file_storages`** - the column for specifying the summary spendings on File storages
- **`instances`** - the column for specifying the summary spendings on compute instances usage (for both - CPU and GPU)
- **`cpu_instances`** - the column for specifying the summary spendings on CPU instances usage
- **`gpu_instances`** - the column for specifying the summary spendings on GPU instances usage
- **`<billing_center_1>`**, **`<billing_center_2>`**, ... - columns for specifying summary spendings for each Billing center. Column header should be the same as the specific Billing center name
- **`time_previous`** - row for specifying time points of the previous time period
- **`time_current`** - row for specifying time points of the current time period
- **`summary_previous`** - row for specifying summary spendings in each time point (with accumulation) and for each resource (total value by resource) and for each Billing center (total value) - all for the previous time period
- **`summary_current`** - row for specifying summary spendings in each time point (with accumulation) and for each resource (total value by resource) and for each Billing center (total value) - all for the current time period
- **`current_quota`** - row for specifying the established spending quota in the current time point for the whole selected time period

For viewing the detailed information about a specific billing center, the user shall have the ability to click the corresponding bar header or just bar itself to load detailed subreports (see below).

---

### The storages report
This report will be opened if the user clicked "Storages" resource header from the **The spendings bar chart with the resource division**.
The report will be generated for the selected time period:
- for admins - for all existing storages (Object and FS) from the whole system
- for users with special permissions on billing center(s) - for all existing storages (Object and FS) owned by users from this billing center(s)
- for any other user - for all existing storages (Object and FS) owned by this user

On this report, the user can see:
- **Report toolbar** and **General report table** (_see previous comment_)
- 2 kinds of charts:
   - The summary Storages spendings line chart
   - The spendings bar chart with top `N` most costly storages
- The detailed spendings table with full list of storages according to the generated report (see above)

![image](https://user-images.githubusercontent.com/45459424/71443437-f4a0ca80-271b-11ea-862f-8e7a436af143.png)

**The summary Storages spendings line chart**
- On this chart, the user can see two lines: summary spendings with accumulation over the previous and the current time periods for storages according to the generated report (see above).
- Other chart features are identical to **The summary spendings chart** from the main spending reports dashboard except for Quota line

**The Storages spendings bar chart**
- On this chart, the user can view top `N` most costly storages according to the generated report (see above). This count should be configured via the system preferences.
- For each displayed storage, the summary spendings for the same previous period should be presented as well.

**The Storages spendings table**
- The full list of storages according to the generated report shall be displayed in the table view.
- The user can view the following extra info about each storage:
   - owner
   - Cloud Provider and Region 
   - cost
   - created date
- The table shall be sorted by the cost column (by descending)
- Table pagination should be implemented

**Download report**
If the user clicks the "Download report" button, the report in `*.csv` format shall be automatically downloaded to the local user workstation. The report shall have the following structure:
![image](https://user-images.githubusercontent.com/45459424/71422287-b3fc6f00-2691-11ea-89f6-0670d95f859f.png)
Where:
- **`t_1`**, **`t_2`**, … - columns for specifying time points according to the selected time period (for the month/quarter time period - time point should be 1 day, for the year/"all" time period - time point should be 1 month)
- **`t_current`** - the column for specifying the current time point
- **`t_end`** - the column for specifying the end time point of the selected time period
- **`<storage_1>`**, **`<storage_2>`**, ... - columns for specifying summary spendings on each storage usage. The column header should be the same as the specific storage name (path)
- **`time_previous`** - row for specifying time points of the previous time period
- **`time_current`** - row for specifying time points of the current time period
- **`summary_previous`** - row for specifying summary spendings in each time point (with accumulation) of storages usage and for each storage separately (total value) - all for the previous time period
- **`summary_current`** - row for specifying summary spendings in each time point (with accumulation) of storages usage and for each storage separately (total value) - all for the current time period
- **`owner`** - row for specifying the owner of each storage
- **`cloud_provider`** - row for specifying the Cloud Provider of each storage
- **`cloud_region`** - row for specifying the Cloud Region of each storage
- **`created_date`** - row for specifying the created date of each storage

### The Object storages report

This report will be opened if the user clicked "Object storages" resource header or "Object storage" bar itself from the **The spendings bar chart with the resource division**.
This report is similar to "The storages report" but shall be generated only for Object storages.

![image](https://user-images.githubusercontent.com/45459424/71443447-097d5e00-271c-11ea-8d87-26b1750a7d3e.png)

### The File storages report
This report will be opened if the user clicked "File storages" resource header or "File storage" bar itself from the **The spendings bar chart with the resource division**.
This report is similar to "The storages report" but shall be generated only for FS mounts.

![image](https://user-images.githubusercontent.com/45459424/71443461-1bf79780-271c-11ea-8ea6-f7b69ad5feaa.png)

---

### The Compute Instances report
This report will be opened if the user clicked "Compute instances" resource header from the **The spendings bar chart with the resource division**.

The report will be generated for the selected time period:
- for admins - for all launched compute instances (CPU and GPU) from the whole system
- for users with special permissions on billing center(s) - for all launched compute instances (CPU and GPU) by users from this billing center(s)
- for any other user - for all launched compute instances (CPU and GPU) by this user

On this report, the user can see:
- **Report toolbar** and **General report table** (_see previous comment_)
- 4 kinds of charts:
   - The summary Compute instances spendings line chart
   - The spendings bar chart with top `N` most costly instance types
   - The spendings bar chart with top `N` most costly tools
   - The spendings bar chart with top `N` most costly pipelines
- The detailed spendings tables:
   - with the full list of launched instance types from the generated report (see above)
   - with the full list of launched tools from the generated report (see above)
   - with the full list of launched pipelines from the generated report (see above)
- Additional control that allows to change displaying of spendings bar charts with the following possible values:
   - **cost** (_default_) - on bar charts top `N` most costly objects (instance types, tools, pipelines) appear
   - **usage** - on bar charts top `N` most involved objects (instance types, tools, pipelines) appear
   - **runs** - on bar charts top `N` objects (instance types, tools, pipelines) with the largest runs count appear

![image](https://user-images.githubusercontent.com/45459424/71443481-3b8ec000-271c-11ea-8d3b-9b6970c6b29d.png)

**The summary Compute instances spendings line chart**
- On this chart, the user can see two lines: summary spendings with accumulation over the previous and the current time periods for launched compute instances from the generated report (see above).
- Other chart features are identical to **The summary spendings chart** from the main spending reports dashboard except for Quota line

**The Instance types spendings bar chart**
- On this chart, the user can view top `N` most costly launched instance types from the generated report (see above). This count should be configured via the system preferences.
- For each displayed instance type, the summary spendings for the same previous period should be presented as well.

**The Instance types spendings table**
- The full list of launched instance types from the generated report shall be displayed in the table view.
- The user can view the following extra info about each launched instance type:
   - usage (hours)
   - runs (count)
   - summary cost
- The table shall be sorted by the column according to the selected additional control (**cost**/**usage**/**runs** - see above) - by descending
- Table pagination should be implemented

**The Tools spendings bar chart**
This chart is similar to **The Instance types spendings bar chart** but for tools.

**The Tools spendings table**
This table is similar to **The Instance types spendings table** but for tools. This table shall have the additional column - "Owner" - for tool owner.

**The Pipelines spendings bar chart**
This chart is similar to **The Instance types spendings bar chart** but for pipelines.

**The Pipelines spendings table**
This table is similar to **The Instance types spendings table** but for pipelines. This table shall have the additional column - "Owner" - for pipeline owner.

**Download report**
If the user clicks the "Download report" button, the report in `*.csv` format shall be automatically downloaded to the local user workstation. The report shall have the following structure:
![image](https://user-images.githubusercontent.com/45459424/70708999-ea7ad700-1cec-11ea-8753-2c1016fb3071.png)
Where:
- **`t_1`**, **`t_2`**, … - columns for specifying time points according to the selected time period (for the month/quarter time period - time point should be 1 day, for the year/"all" time period - time point should be 1 month)
- **`t_current`** - the column for specifying the current time point
- **`t_end`** - the column for specifying the end time point of the selected time period
- **`<instance_1>`**, **`<instance_2>`**, ... - columns for specifying summary spendings on each launched instance type. The column header should be the same as the specific instance type name
- **`<tool_1>`**, **`<tool_2>`**, ... - columns for specifying summary spendings on each launched tool. The column header should be the same as the specific tool name
- **`<pipeline_1>`**, **`<pipeline_2>`**, ... - columns for specifying summary spendings on each launched pipeline. The column header should be the same as the specific pipeline name
- **`time_previous`** - row for specifying time points of the previous time period
- **`time_current`** - row for specifying time points of the current time period
- **`summary_previous`** - row for specifying summary spendings in each time point (with accumulation) on launched instances and separately for each instance type (total value), tool (total value), pipeline (total value) - all for the previous time period
- **`summary_current`** - row for specifying summary spendings in each time point (with accumulation) on launched instances and separately for each instance type (total value), tool (total value), pipeline (total value) - all for the current time period
- **`owner`** - row for specifying the owner of each tool and pipeline
- **`usage`** - row for specifying the usage of each instance type (total runs hours), tool (total runs hours) and pipeline (total runs hours) - for the selected current time period
- **`runs_count`** - row for specifying the count of runs of each instance type, tool, and pipeline - for the selected current time period

### The CPU report
This report will be opened if the user clicked "CPU" resource header or "CPU" bar itself from the **The spendings bar chart with the resource division**.
This report is similar to **The Compute Instances report** but shall be generated only for CPU instances.

![image](https://user-images.githubusercontent.com/45459424/71443504-58c38e80-271c-11ea-9327-ba721869ee52.png)

### The GPU report
This report will be opened if the user clicked "GPU" resource header or "GPU" bar itself from the **The spendings bar chart with the resource division**.
This report is similar to **The Compute Instances report** but shall be generated only for GPU instances.

![image](https://user-images.githubusercontent.com/45459424/71443530-78f34d80-271c-11ea-9b08-d40f3646db78.png)

---

### The Billing centers/groups report
This report will be opened if the user selected any center(s)/group(s) from the **Report toolbar** or click the "Billing center" bar on **The spendings bar chart with the billing centers' division**.

The report will be generated for the selected time period and selected billing center(s)/group(s)

On this report, the user can see:
- **Report toolbar** and **General report table** (_see previous comment_)
- 3 kinds of charts:
   - The summary Billing center(s)/group(s) spendings line chart
   - The spendings bar chart with the resource division
   - The spendings bar chart with the user division
- The detailed spendings table with the full user list of selected billing center(s)/group(s)

![image](https://user-images.githubusercontent.com/45459424/71443548-90323b00-271c-11ea-9cef-9241101d203a.png)

**The summary Billing center(s)/group(s) spendings line chart**
- On this chart, the user can see two lines: summary spendings with accumulation over the previous and the current time periods for selected billing center(s)/group(s).
- Other chart features are identical to **The summary spendings chart** from the main spending reports dashboard

**The spendings bar chart with the resource division**
This chart shall be identical to the same one from the main spending reports dashboard but only for the selected billing center(s)/group(s).

**The spendings bar chart with the user division**
- On this chart, the user can view top `N` most spending users from the selected billing center(s)/group(s). This count should be configured via the system preferences.
- For each displayed user, the summary spendings for the same previous period should be presented as well.

**The detailed spendings table**
- The full user list from the selected billing center(s)/group(s) shall be displayed in the table view.
- The following extra info about each user from the selected billing center(s)/group(s) shall be displayed:
   - total runs duration launched by that user (hours)
   - total runs count launched by that user
   - total spendings
   - billing center
   or
   - group(s)
- The table shall be sorted by the total spendings column - by descending
- Table pagination should be implemented

**Download report**
If the user clicks the "Download report" button, the report in `*.csv` format shall be automatically downloaded to the local user workstation. The report shall have the following structure:
![image](https://user-images.githubusercontent.com/45459424/71422949-cfb64400-2696-11ea-9be1-213e1424596a.png)
Where:
- **`t_1`**, **`t_2`**, … - columns for specifying time points according to the selected time period (for the month/quarter time period - time point should be 1 day, for the year/"all" time period - time point should be 1 month)
- **`t_current`** - the column for specifying the current time point
- **`t_end`** - the column for specifying the end time point of the selected time period
- **`storages`** - the column for specifying the summary spendings on storages usage (for both - Object and FS) - for selected Billing center(s)/group(s)
- **`object_storages`** - the column for specifying the summary spendings on Object storages - for selected Billing center(s)/group(s)
- **`file_storages`** - the column for specifying the summary spendings on File storages - for selected Billing center(s)/group(s)
- **`instances`** - the column for specifying the summary spendings on compute instances usage (for both - CPU and GPU) - for selected Billing center(s)/group(s)
- **`cpu_instances`** - the column for specifying the summary spendings on CPU instances usage - for selected Billing center(s)/group(s)
- **`gpu_instances`** - the column for specifying the summary spendings on GPU instances usage - for selected Billing center(s)/group(s)
- **`<user_1>`**, **`<user_2>`**, ... - columns for specifying summary spendings of each user from the selected Billing center(s)/group(s). The column header should be the same as the specific user name
- **`time_previous`** - row for specifying time points of the previous time period
- **`time_current`** - row for specifying time points of the current time period
- **`summary_previous`** - row for specifying summary spendings in each time point (with accumulation) and for each resource (total value by resource) and for each user of selected Billing center(s)/group(s) (total value) - all for the previous time period
- **`summary_current`** - row for specifying summary spendings in each time point (with accumulation) and for each resource (total value by resource) and for each user of selected Billing center(s)/group(s) (total value) - all for the current time period
- **`current_quota`** - row for specifying the established spending quota in the current time point for the whole selected time period and selected Billing center(s)/group(s)
- **`runs_duration`** - row for specifying the total runs hours for each user of selected Billing center(s)/group(s) (total value) - for the selected current time period
- **`runs_count`** - row for specifying the count of runs for each user of selected Billing center(s)/group(s) (total value) - for the selected current time period
- **`billing_center`** - row for specifying the Billing center to which the user belongs
or
- **`groups`** - row for specifying groups to which the user belongs

### The User report
This report will be opened if the user selected specific user(s) from the **Report toolbar** or click the "User" bar on **The spendings bar chart with the user division**.

The report will be generated for the selected time period and selected user.
The view of this report is similar to the spending reports main dashboard except for **The spendings bar chart with the billing centers' division**:

![image](https://user-images.githubusercontent.com/45459424/71443562-a6d89200-271c-11ea-804c-bdcbb81b7079.png)

**Download report**
If the user clicks the "Download report" button, the report in `*.csv` format shall be automatically downloaded to the local user workstation. The report shall have the following structure:
![image](https://user-images.githubusercontent.com/45459424/70713808-d4bedf00-1cf7-11ea-925c-3f75ccbbc4cd.png)
Where:
- **`t_1`**, **`t_2`**, … - columns for specifying time points according to the selected time period (for the month/quarter time period - time point should be 1 day, for the year/"all" time period - time point should be 1 month)
- **`t_current`** - the column for specifying the current time point
- **`t_end`** - the column for specifying the end time point of the selected time period
- **`storages`** - the column for specifying the summary spendings on storages usage (for both - Object and FS) - for the selected user(s)
- **`object_storages`** - the column for specifying the summary spendings on Object storages - for the selected user(s)
- **`file_storages`** - the column for specifying the summary spendings on File storages - for the selected user(s)
- **`instances`** - the column for specifying the summary spendings on compute instances usage (for both - CPU and GPU) - for the selected user(s)
- **`cpu_instances`** - the column for specifying the summary spendings on CPU instances usage - for the selected user(s)
- **`gpu_instances`** - the column for specifying the summary spendings on GPU instances usage - for the selected user(s)
- **`time_previous`** - row for specifying time points of the previous time period
- **`time_current`** - row for specifying time points of the current time period
- **`summary_previous`** - row for specifying summary spendings in each time point (with accumulation) and for each resource (total value by resource) - all for the previous time period and selected user(s)
- **`summary_current`** - row for specifying summary spendings in each time point (with accumulation) and for each resource (total value by resource) - all for the current time period and selected user(s)
- **`current_quota`** - row for specifying the established spending quota in the current time point for the whole selected time period and selected user(s)

**Comment by Wedds** [comment]
# API DESCRIPTION
## Request parameters
Required are marked **bold**
-  **from [date]** - include expenses from this date (including)
-  **to [date]** - include expenses up to this date (including)
-  interval [day("1d"); month ("1M"); year("1y"); total(don't specify or use null)] - expenses shall be grouped into this time interval, e.g. interval=day means that expenses shall be returned for each day in the requested period; total shall return sum over the whole period    
-  filter [Map<String,List<String>>] optional - expenses shall be filtered by this key-values (key = field name, value = field value)
- grouping [BillingGrouping] optional - expenses shall be grouped by this rule; if this value is not specified, request shall return raw data without 
	All the grouping rules described in `com.epam.pipeline.entity.billing.BillingGrouping` enum. Currently supported grouping:
        
  >RESOURCE_TYPE - STORAGE/COMPUTE
	RUN_COMPUTE_TYPE - CPU/GPU
	 **RUN_INSTANCE_TYPE** - compute instance type (m5.16xlarge,t2.2xlarge, ...)         
	 **PIPELINE** - name of the pipeline or id if name cant't be find
	 **TOOL** - tool name or full docker image name
	 STORAGE - storage path or or id if name cant't be find
	 STORAGE_TYPE - OBJECT_STORAGE/FILE_STORAGE
	 USER - username
	 BILLING_CENTER - billing center of compute resource

    _**Field and histogram groupings are not supported at the same time!**_
- loadDetails [boolean] optional - load entity details, e.g. storage provider, owner, etc. This flag is supposed to be used with grouping for retrieving additional info for spending tables.
    _Grouping rules marked **bold** load usage details as well. Usage details are used for grouping, connected with computing resource consumption, so details contain usage in minutes and count of runs, that interacted with specified resource_ 

## Response structure  
The response contains a list of `BillingChartInfo` objects with the following structure: 

- periodStart [date] - start of the period, described by this point
- periodEnd [date] - end of the period, described by this point
- cost [long] - spendings during [periodStart - periodEnd] period in hundreths of cents
- accumulatedCost [long]  (for interval requests only) - spendings, accumulated at the end of this billing chart point from the start of the whole billing period ([from - periodEnd] interval)
- groupingInfo [Map<String, String>] (for grouping requests only) - map, containing grouping results. Always contains requested grouping as key and value. If no results were specified shows predefined empty value (e.g. _unknown_)

## Examples:

### Total cost for all resources for specified period
Request:  
```
{
  "from": "2019-02-07",
  "to": "2020-02-07"  
}
```

Response:
```
{
  "payload": [
    {
      "periodStart": "2019-02-07 00:00:00.000",
      "periodEnd": "2020-02-07 23:59:59.999",
      "cost": 19530277
    }
  ],
  "status": "OK"
}
```
### Histogram of spendings for all resources for specified period
Request:  
```
{
  "from": "2019-12-07",
  "to": "2020-02-07",
  "interval":"1M"
}
```

Response:
```
{
  "payload": [
    {
      "periodStart": "2019-12-01 00:00:00.000",
      "periodEnd": "2019-12-31 23:59:59.999",
      "cost": 2577500,
      "accumulatedCost": 2577500
    },
    {
      "periodStart": "2020-01-01 00:00:00.000",
      "periodEnd": "2020-01-31 23:59:59.999",
      "cost": 9704100,
      "accumulatedCost": 12281600
    },
    {
      "periodStart": "2020-02-01 00:00:00.000",
      "periodEnd": "2020-02-29 23:59:59.999",
      "cost": 132077,
      "accumulatedCost": 12413677
    }
  ],
  "status": "OK"
}
```

### Histogram of spendings with filters (resource type) for a specified period
Request:  
```
{
  "from": "2019-12-07",
  "to": "2020-02-07",
  "filters":{"resource_type":["COMPUTE"]},
  "interval":"1M"
}
```

Response:
```
{
  "payload": [
    {
      "periodStart": "2019-12-01 00:00:00.000",
      "periodEnd": "2019-12-31 23:59:59.999",
      "cost": 2577500,
      "accumulatedCost": 2577500
    },
    {
      "periodStart": "2020-01-01 00:00:00.000",
      "periodEnd": "2020-01-31 23:59:59.999",
      "cost": 9704100,
      "accumulatedCost": 12281600
    },
    {
      "periodStart": "2020-02-01 00:00:00.000",
      "periodEnd": "2020-02-29 23:59:59.999",
      "cost": 97600,
      "accumulatedCost": 12379200
    }
  ],
  "status": "OK"
}
```

### Total spendings for grouping without details
Request:  
```
{
  "from": "2019-12-07",
  "to": "2020-02-07",
  "grouping":"RUN_INSTANCE_TYPE"
}
```

Response:
```
{
  "payload": [
    {
      "groupingInfo": {
        "RUN_INSTANCE_TYPE": "m5.large"
      },
      "periodStart": "2019-12-07 00:00:00.000",
      "periodEnd": "2020-02-07 23:59:59.999",
      "cost": 863600
    },
    {
      "groupingInfo": {
        "RUN_INSTANCE_TYPE": "r5.2xlarge"
      },
      "periodStart": "2019-12-07 00:00:00.000",
      "periodEnd": "2020-02-07 23:59:59.999",
      "cost": 92100
    }    
  ],
  "status": "OK"
}
```

### Total spendings for grouping, detailed 
Request:  
```
{
  "from": "2019-12-07",
  "to": "2020-02-07",
  "grouping":"RUN_INSTANCE_TYPE",
  "loadDetails":true
}

```

Response:
```
{
  "payload": [
    {
      "groupingInfo": {
        "usage": "50925",
        "RUN_INSTANCE_TYPE": "m5.large",
        "runs": "10"
      },
      "periodStart": "2019-12-07 00:00:00.000",
      "periodEnd": "2020-02-07 23:59:59.999",
      "cost": 863600
    },
    {
      "groupingInfo": {
        "usage": "1522",
        "RUN_INSTANCE_TYPE": "r5.2xlarge",
        "runs": "10"
      },
      "periodStart": "2019-12-07 00:00:00.000",
      "periodEnd": "2020-02-07 23:59:59.999",
      "cost": 92100
    }
  ],
  "status": "OK"
}
```

### Total spendings for grouping, detailed, partially specified results
Request:  
```
{
  "from": "2019-12-07",
  "to": "2020-02-07",
  "grouping":"STORAGE",
  "loadDetails":true
}
```

Response:
```
{
  "payload": [
    {
      "groupingInfo": {  // Storage is not found in DB, so return structured, but not specified info
        "STORAGE": "20037",
        ""provider": "unknown"
      },
      "periodStart": "2019-12-07 00:00:00.000",
      "periodEnd": "2020-02-07 23:59:59.999",
      "cost": 6217900
    },
    {
      "groupingInfo": {
        "STORAGE": "test-fonda",
        "provider": "S3"
      },
      "periodStart": "2019-12-07 00:00:00.000",
      "periodEnd": "2020-02-07 23:59:59.999",
      "cost": 15646
    }
  ],
  "status": "OK"
}
```

### Total spendings for grouping, the result is paginated
Request:  
```
{
  "from": "2020-01-12",
  "to": "2020-02-12",
  "grouping": "RUN_INSTANCE_TYPE",
  "pageSize": 3,
  "pageNum": 2
}
```

Response:
```
{
  "payload": [
    {
      "groupingInfo": {
        "totalPages": "5",
        "RUN_INSTANCE_TYPE": "p2.xlarge",
        "page": "2"
      },
      "periodStart": "2020-01-12 00:00:00.000",
      "periodEnd": "2020-02-12 23:59:59.999",
      "cost": 17000
    },
    {
      "groupingInfo": {
        "totalPages": "5",
        "RUN_INSTANCE_TYPE": "c5.xlarge",
        "page": "2"
      },
      "periodStart": "2020-01-12 00:00:00.000",
      "periodEnd": "2020-02-12 23:59:59.999",
      "cost": 6800
    },
    {
      "groupingInfo": {
        "totalPages": "5",
        "RUN_INSTANCE_TYPE": "m5.2xlarge",
        "page": "2"
      },
      "periodStart": "2020-01-12 00:00:00.000",
      "periodEnd": "2020-02-12 23:59:59.999",
      "cost": 5000
    }
  ],
  "status": "OK"
}
```

### Total spendings for grouping, top 3 highest result
Request:  
```
{
  "from": "2020-01-12",
  "to": "2020-02-12",
  "grouping": "RUN_INSTANCE_TYPE",
  "pageSize": 3
}
```

Response:
```
{
  "payload": [
    {
      "groupingInfo": {
        "totalPages": "5",
        "RUN_INSTANCE_TYPE": "m5.4xlarge",
        "page": "0"
      },
      "periodStart": "2020-01-12 00:00:00.000",
      "periodEnd": "2020-02-12 23:59:59.999",
      "cost": 30000
    },
    {
      "groupingInfo": {
        "totalPages": "5",
        "RUN_INSTANCE_TYPE": "m5.large",
        "page": "0"
      },
      "periodStart": "2020-01-12 00:00:00.000",
      "periodEnd": "2020-02-12 23:59:59.999",
      "cost": 20000
    },
    {
      "groupingInfo": {
        "totalPages": "5",
        "RUN_INSTANCE_TYPE": "c5.large",
        "page": "0"
      },
      "periodStart": "2020-01-12 00:00:00.000",
      "periodEnd": "2020-02-12 23:59:59.999",
      "cost": 10000
    }
  ],
  "status": "OK"
}
```

### Total spendings for grouping, empty response case
Request:  
```
{
  "from": "2019-01-07",
  "to": "2019-02-07",
  "grouping":"RUN_INSTANCE_TYPE",
  "loadDetails":true
}
```

Response:
```
{
  "payload": [
    {
      "groupingInfo": {
        "usage": "unknown",
        "RUN_INSTANCE_TYPE": "unknown",
        "runs": "unknown"
      }
    }
  ],
  "status": "OK"
}
```
