### ISSUE TITLE
Azure: Storage creation is failing

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#765]
**Describe the bug**
When we create a storage on Azure stand the following error occurs: 
`Input byte[] should at least have 2 bytes for base64 bytes`

**Steps to reproduce the behavior:**
1. Open library
2. Hover mouse pointer over "+ Create v" button
3. Select "Storages" > "Create new object storage"
4. In pop-up window input valid value into the field "Storage path"
5. Click "Create" button

**Expected behavior**
The new storage appeared in the library tree.

**Screenshots**

![image](https://user-images.githubusercontent.com/23356251/67302199-37b2a780-f4f9-11e9-967a-9e9662c37a47.png)

**Environment:**
 - Cloud Provider: **AZURE**
 - Version **0.16.0.3119**
 - Browser: **chrome**

**Comment by mzueva** [comment]
I fixed Azure deployment and it shall work for now. Despite this I observe two bugs:

1. It is possible to create/update Azure region with missing storage account key #767 
2. When a new Azure storage is created validation of it existence doesn't work #768

**Comment by kamyshova** [comment]
@mzueva Thanks, fixed.
