### ISSUE TITLE
Tool version scan is not available for the AWS dev environment

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#78]
- Environment: AWS
   - Version: 0.15.0.242.a673934dc5e23d0979096cc93cc883953de7655f

Tool scan button and results of scanned tool (component in VULNERABILITIES REPORT tool version tab) are absent.

**Comment by sidoruka** [comment]
Shall be fine since 0.15.0.282.b7fd3ea0ff7986bd7c6df2341f128f7d014a3c56
@kamyshova please feel free to close this issue once the tests have passed

**Comment by kamyshova** [comment]
@sidoruka That's fine. Thank you.
