### ISSUE TITLE
When advanced search filter for searching pipeline runs is used CP failed with error

### ISSUE THREAD

**Issue by SilinPavel** [epam/cloud-pipeline#780]
**Describe the bug**
When advanced search filter for searching pipeline runs is used CP failed with error:
```
Your operation has been aborted due to incorrect grammar of a query.
```
It was found out that cause of this error is wrong SQL query : 
```
Caused by: org.postgresql.util.PSQLException: The column name TAGS was not found in this ResultSet.
```
So we should change SQL query to be able to load `tags` for runs

**To Reproduce**
1. Go to '/pipeline/#/runs/active'
2. Click on 'advanced filter'
3. type 'pod.id=<some real pod id>'

**Expected behavior**
run with related pod id is shown 

**Screenshots**
![image](https://user-images.githubusercontent.com/11179595/67841593-7eac2880-fb09-11e9-852c-3a429c5d5191.png)

**Comment by NShaforostov** [comment]
Verified
