### ISSUE TITLE
Failed to load pipeline configuration from file

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#79]
- Environment: AWS
 - Version: 0.15.0.253.3afb73f09183b910bdc94d489594cbf4849f81a2

The following error appears on CONFIGURATION pipeline tab:

![image](https://user-images.githubusercontent.com/23356251/55708336-55ea0780-59ee-11e9-8bae-512bd91f23dd.png)

And accordingly on the launch pipeline form page:

![image](https://user-images.githubusercontent.com/23356251/55708793-79618200-59ef-11e9-8c22-e3a2449b4414.png)

Steps:
1. Create pipeline from template (SHELL, PYTHON, LUIGY, WDL)
2. Open created pipeline, select version
3.  1) Select CONFIGURATION tab
     2) Click RUN button

Expected:
* Docker image, Node type, Disk (Gb) fields* are filled, the message "Failed to load pipeline configuration from file..." does not exist.

Actual:
* Above mentioned fields are empty, the message "Failed to load pipeline configuration from file..." appears on the launch pipeline form page.

**Comment by mzueva** [comment]
@sidoruka @kamyshova It seems that some problem exists with template: value of field `instance_size` is double quoted in `config.json`: `"instance_size" : ""m5.large""`

**Comment by sidoruka** [comment]
Fixed in 487c7fa
@kamyshova please recheck

**Comment by kamyshova** [comment]
@sidoruka @mzueva That's fine. Thank you.
