### ISSUE TITLE
Cannot transfer directories via `pipe storage cp` in Windows

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#790]
**Describe the bug**
When the user runs `pipe storage cp C:\path\to\dir s3://bucket/path/` - command completes without any message and a zero exit code, but nothing is transferred

**To Reproduce**
1. Run `pipe storage cp C:\path\to\dir s3://bucket/path/`
2. Command completes without any message and a zero exit code, but nothing is transferred

**Expected behavior**
`C:\path\to\dir` is copied to `s3://bucket/path/`

**Environment:**
 - Cloud Provider: AWS
 - Version: `0.15.0.3303.e2264d1cdd77b1aaf7542b9fc9e5def04045514a`
 - OS: Window 7

**Additional context**
* The same behavior is observed for the absolute and relative directory paths.
* File copy is working correctly

**Comment by sidoruka** [comment]
Please cherry-pick the fixes to `release/0.15`

**Comment by mzueva** [comment]
Backported to `release/0.15` via b16812e916afdf4d3cec1a3dca8955d72b011e32
