### ISSUE TITLE
`pipe` shall be able to perform objects restore in a batch mode

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#792]
**Background**
At the moment, Cloud Pipeline's CLI exposes `restore` command which is capable of restoring a single object at a time.
When a user deletes the whole folder from the object storage it is tedious to restore it file-by-file.
It would be great to allow `recursive` restore for a folder.

**Approach**
* `restore` command shall get the top-level deleted files from the `source` directory and restore them to the latest version
* In addition - expose additional `--recursive` option to the `restore` command, which shall restore the whole directory hierarchy
* To handle cases when the user would like to skip certain object while restoring - introduce `--include` and `--exclude` options, which shall behave in the same manner as in the `storage cp` command.
* This feature shall be supported for AWS only. For other cloud providers, a clear message shall be displayed, when a directory restore is requested.

**Comment by sidoruka** [comment]
Once implemented and tested - cherry-pick to `release/0.15`

**Comment by NShaforostov** [comment]
Verified.
Docs were updated via [be7ad17](https://github.com/epam/cloud-pipeline/pull/789/commits/be7ad1772be461c2962ba843bf2376cd255c0e4c).
