### ISSUE TITLE
Double downloading from the DOCUMENTS pipeline tab

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#793]
**Describe the bug**
Attempt to download any document from the **DOCUMENTS** pipeline tab leads to a double downloading of the corresponding file. This bug is relevant only for non-Markdown documents (not `*.md` files)

**To Reproduce**
1. Open any pipeline, select the **DOCUMENTS** tab
2. Upload any document with not `md` extension (e.g. `txt`, `docx` or others)
3. Click the **Download** button next to the uploaded document
4. The browser tries to download the document twice

**Expected behavior**
The document is downloaded once

**Screenshots**
![image](https://user-images.githubusercontent.com/45459424/68303269-8e50e180-00b4-11ea-89ff-bcd771bf15b0.png)

**Environment:**
 - Cloud Provider: N/A
 - Version 0.16.0.3326.baa436998d5541afca887e14746c1db3bc8bcd39
 - Browser: chrome, Mozilla Firefox, MS Edge

**Comment by AleksandrGorodetskii** [comment]
#### This issue is fixed by #836 pull request.

**Comment by rodichenko** [comment]
@NShaforostov fixed via 301c3b37c2dff4820a5cfa86d00c7066c92d27f5, can you re-check please?

**Comment by NShaforostov** [comment]
Verified, works fine.
