### ISSUE TITLE
Luigi template pipeline run fails

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#797]
Luigi template pipeline run fails at work with the following error:

`luigitest.py: error: unrecognized arguments: --resumed-run false`

**Steps to reproduce the behavior:**
1. Open library
2. Hover over "+ Create v", select "Pipeline" item -> click on "LUIGI"
3. In an appeared pop-up window specify a valid pipeline name
4. Click CREATE button
5. Click on the created pipeline
6. Click RUN button
7. Click Launch button
8. Click Launch button in an appeared pop-up window

**Expected behavior**
- Pipeline run is being completed correctly, all tasks from the main code file are displaying in a log
- Run is being completed with SUCCESS status

**Screenshots**

![image](https://user-images.githubusercontent.com/23356251/68405776-bc582380-0191-11ea-89bb-7bd73b7865f6.png)

**Environment:**
 - Cloud Provider: **AWS**, **AZURE**
 - Version: **0.16.0.3329**
 - Browser: **chrome**

**Comment by sidoruka** [comment]
Introduced by 34c5cc3a4211c368ade4a4670229b525e09c7698

Let's treat this a low-priority

**Comment by kamyshova** [comment]
Fixed
