### ISSUE TITLE
GUI shall verify the image version, when running a pipeline

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#798]
**Background**
At the moment, Cloud Pipeline verifies if the `group/tool` exists, but does not check the version. In such cases pipeline will be started, but will hang in `ImagePullBackOff`.

**Approach**
If a pipeline is started (clicked `RUN`) we shall notify a user, if an invalid image version is used

**Comment by sidoruka** [comment]
@rodichenko please port to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka fixed, backported to `release/0.15` via c1818c88bed87038d418aca40a2c430e8346d4af.
If the image's version is not found, the following warning will be shown:
![version_not_found_warning](https://user-images.githubusercontent.com/5070496/68467230-e27bd300-0226-11ea-9705-5c1777d4cde2.png)
