### ISSUE TITLE
Luigi pipeline GRAPH tab is absent for the AWS dev environment

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#80]
As you can see in the screenshot of the GRAPH tab for luigi pipeline is not visible

![image](https://user-images.githubusercontent.com/23356251/55709071-2c31e000-59f0-11e9-870b-bb92193e5cf8.png)

**Comment by sidoruka** [comment]
Caused by the same issue as #79 so far fixed in 487c7fa
@kamyshova please recheck

**Comment by kamyshova** [comment]
@sidoruka That's fine. Thank you.
