### ISSUE TITLE
API: override bucket file's pre-signed url response headers

### ISSUE THREAD

**Issue by rodichenko** [epam/cloud-pipeline#808]
**Background**
**Part 1**
At the moment, generated pre-signed urls don't contain `content-disposition` **response** header. If user clicks `Download file` button at GUI, some files (e.g. images) are displayed in-place instead of being downloaded. It would be nice if pre-signed urls contain overridden `content-disposition=attachment; filename=...` header.
**Part 2**
At the moment, GUI sends separate requests for each file to generate download pre-signed url; it would be nice if we have `datastorage/{id}/download?...` (or other) API method which accepts the same parameters as `datastorage/{id}/generateUrl?...` and redirects response to generated pre-signed url (with or without overridden `content-disposition` header)

**Approach**
- `datastorage/{id}/generateUrl` method should accept optional `contentDisposition` attribute (values: `inline` or `attachment`);
- For AWS buckets: if this attribute is provided, override `content-disposition` response header of pre-signed url ([docs.aws.amazon.com](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.html#getResponseHeaders--)): 
  - `Content-Disposition: inline`
  - `Content-Disposition: attachment; filename=<file name>`

**Comment by sidoruka** [comment]
Cherrypick to `release/0.15`

**Comment by sidoruka** [comment]
- Reverted `release/0.15`
- Chrome complains that `Multiple files download` is going to happen, while a single file is being downloaded
