### ISSUE TITLE
Allow to share SSH access for non-interactive jobs

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#812]
**Background**
At the moment, Cloud Pipeline does not allow share the SSH access for the tools, which do not have the endpoints configured. 

It would be nice to provide such type of access, as there is a set of tools, that do not expose any HTTP endpoints but are used for collaboration via the command line.

**Approach**
* "Share" link shall be available for non-interactive runs
* Sharing dialog for such runs shall not display "Enable SSH sharing" checkbox. This option shall be set by default

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka implemented, backported to release/0.15 via d6e7805e6231d14d5d54113fe7917d8bb6457437

**Comment by sidoruka** [comment]
@rodichenko please verify that the overall logic is consistent with the previous version.

As I see the "Sharing" link is displayed for any state of the job (even when it is queued). This was not a case previously.

![image](https://user-images.githubusercontent.com/20998291/69654074-40ad1080-1085-11ea-9197-1cb1af5c83f0.png)

**Comment by rodichenko** [comment]
@sidoruka logic is fixed (+`run initialized` status check), backported to `release/0.15` via 5cf719dfc8727f525e0a6292edfbd9008445bac9

**Comment by sidoruka** [comment]
@mzueva, at the moment the SSH-only shared jobs are not visible via the `Services`. Is it possible to expose such runs there?

**Comment by NShaforostov** [comment]
I've tried to verify this feature:
- It works fine with sharing the run to the _**user(s)**_.
- But when sharing the run to the _**group(s) of users**_ - shared runs aren't displayed in the **SERVICES** section of the main Dashboard, so the SSH-session can be opened by the user from the "shared" group only manually, using the direct link.
Is this correct behavior? Or probably we should display shared runs in the **SERVICES** section for all users from the group for which the run is shared?

**Comment by NShaforostov** [comment]
Docs were updated via #991
