### ISSUE TITLE
Incorrect pipeline files editing

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#813]
**Describe the bug**
When we edit a pipeline code, save changes and commit the edit popup doesn't close. Moreover, when we try to close popup the following warning appears:
`All changes will be lost. Continue?`

**Steps to reproduce the behavior:**
1. Open library
2. Click on "+ Create v", in an appeared list click on "Pipeline" item
3. In an appeared window specify a valid pipeline name, click `Create` button
4. Open created pipeline, select a version
5. On the pipeline page select `CODE` tab
6. Click on config.json file and edit it.
7. Click `SAVE` button.
8. Insert a commit message to commit popup.
8. Click `Commit` button.

**Expected behavior**
The edit popup was closed and changes were applied. 

**Screenshots**
If we try to close edit window by clicking on `CLOSE` button (after commit):
![image](https://user-images.githubusercontent.com/23356251/69649798-a649ce80-107e-11ea-9d1e-8e5ac6abba55.png)

**Environment:**
 - Cloud Provider:  **AWS, AZURE**
 - Version: **0.16.0.3498**
 - Browser: **chrome**

**Comment by rodichenko** [comment]
@kamyshova @sidoruka fixed, backported to `release/0.15` via 5d2ff21c2bb92de8758ad27a6bd4b7e5f4a56c67

**Comment by kamyshova** [comment]
@rodichenko Verified. Fixed. Thank you!
