### ISSUE TITLE
Strange usage charts behavior when "Live update" filter is on 

### ISSUE THREAD

**Issue by NewOlya** [epam/cloud-pipeline#814]
### Background
We have the Monitor cluster nodes feature, that presents plots for CPU Usage, Memory Usage and Network Usage.  There is the "Live update" filter in it, so user could track any kind of usage in real-time (every 5 seconds data updates). So the system saves data once in some period of time and presents it rounding off values. Because of that, the values at the same point in different periods of time can differ.
### To Reproduce

1. Go to the "Cluster nodes" dashboard
2. Click any node
3. Go to the "Monitor" tab
4. Check if the "Live update" filter checkbox is marked
5. Remember the value at some point of the chart line
6. Wait for about 5 seconds

### Expected behavior:
The displayed data on the plot is not changing

### Screenshots
![Monitor1](https://user-images.githubusercontent.com/32195393/70801556-419dac00-1dc0-11ea-8d6d-85ad1cbedcc5.png)
![Monitor2](https://user-images.githubusercontent.com/32195393/70801559-44989c80-1dc0-11ea-856e-3c21f4793b05.png)

**Comment by NewOlya** [comment]
For the beginning, we need to implement the following set of features:

### Approach

**General requirements**
1. The user shall be able to see the chart based on the table data
2. The report chart shall display a stacked line chart where each line plots:
    - Cost over time
3. The user can select the type of the chart:
    - Line Chart
3. The chart shall have the legend
4. The chart shall have a slice line on the current day
    - The system shall display the value from y-axis on the intersection of the slice line and every chart line 
    - The value format shall be $N
5. User shall be able to specify the date period for the report
    - User can select time period from predefined values:
      - 1 month
      - 3 months
      - 6 months
      - 1 year
      - 2 years
      - All 
   - The default report time period shall be a month
7. The chart shall be dynamically regenerated if some configurations were changed
8. The system shall display y-axis value in the point where the user focuses on the chart line
9. If there are more than _10_ objects in the report the system shall display only top 6 objects with the biggest value in the chart

**Filters**
1. The Limit line shall be displayed on the generated chart:
   -  If the selected report type is:
      - User
      - Group 
      - Tag 
    - If only 1 instance was selected
    - If the limit was specified in the configurations
    - The system shall specify the value of the limit near the Limit line 
    - The Limit line shall be displayed by default
    - The system shall display the previous period "Limit" line if the limit was set

**Comment by sidoruka** [comment]
@SilinPavel, I presume this is a server-side issue. Could you please take a look? If it's a GUI issue - feel free to reassign to @rodichenko

**Comment by rodichenko** [comment]
There was a GUI problem with charts range: with `Live update` mode, charts range (`from` - `to` duration) was decreasing by 5 seconds per each request (e.g. first request - 1 hour, second one - 59 minutes 55 seconds, third one - 59 minutes 50 seconds etc.). That problem is now fixed. @NewOlya can you re-check this issue please?

**Comment by NewOlya** [comment]
Verified
