### ISSUE TITLE
FSBrowser doesn't clean the temp files, when download is canceled

### ISSUE THREAD

**Issue by NewOlya** [epam/cloud-pipeline#818]
**Describe the bug**
There is the Download feature in the FS browser. If the user clicks on the "Download" button the system will display the Operations window with the "Cross" button to cancel this operation. If the user clicks the "Cross" button for the downloaded folder, the system won't download the document to the user's local machine, but the archived (gzipped) folder will appear in the node's filesystem.

**To Reproduce**
1. Launch a run
2. Wait until the **BROWSE** hyperlink appears
3. Click the **BROWSE** hyperlink
4. Start to download some folder
5. Click the **cross** button next to the folder name in the "Operations" window 
6. See this archived folder appearing in the browser

**Expected behavior**
The folder's downloading shall be stopped. The archived folder shall not be downloaded to the node's filesystem.

**Screenshots**
1) ![image](https://user-images.githubusercontent.com/45459424/71003625-31543c80-20f2-11ea-86c6-70cec47c8c52.png)
2) ![image](https://user-images.githubusercontent.com/45459424/71003916-6eb8ca00-20f2-11ea-874a-868325577751.png)
3) ![image](https://user-images.githubusercontent.com/45459424/71004049-9445d380-20f2-11ea-9f99-452f03b40684.png)

**Environment:**
 - Cloud Provider: AWS
 - Version 0.16.0.3560.cc49b19835b388979bfa8c1e32e8e7d626e5aa4d
 - Browser: Chrome

**Additional context**
Associated task: #223

**Comment by sidoruka** [comment]
After all:
* The temporary archive shall be created in the `temp` directory, not in the same as the source directory (`temp` location shall be configurable via the `fsbrowser` options and default to `/tmp`)
* If the download request is canceled - temporary tarball shall be deleted from the node's filesystem

**Comment by NShaforostov** [comment]
Verified. Works fine!
