### ISSUE TITLE
Autoscaling cluster can be autopaused

### ISSUE THREAD

**Issue by SilinPavel** [epam/cloud-pipeline#819]
**Describe the bug**
Currently master node of autoscale cluster can be auto paused.

**To Reproduce**
1. Run on-demand autoscale cluster with 0 default child node
2. Configure IDLE ACTION as PAUSE
3. do not load master node
4. See that master node is paused after some time

**Expected behavior**
master node of autoscaled cluster isn't paused

**Comment by NShaforostov** [comment]
Verified
