### ISSUE TITLE
`pipe storage mount` shall allow to specify the fuse log file

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#820]
**Background**
At the moment, `pipe` CLI `mount` command does not provide any runtime logs. If some file operation fails it is quite hard to find out the reasons.

It would be great to write all the fuse operations to some location.

**Approach**

Expose the `-l`/`--log-file` option for the `storage mount` command. If it is specified - fuse's `stdout/err` shall be written to that file.
If an option is not set - keep an existing behavior.

**Comment by sidoruka** [comment]
Cherrypick please to `release/0.15`

**Comment by sidoruka** [comment]
@NShaforostov, pending docs

**Comment by NShaforostov** [comment]
Verified.
Docs were updated via #860
