### ISSUE TITLE
Support fallocate and ftruncate for the pipe-fuse

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#821]
**Background**
At the moment, any `ftruncate` or `fallocate` operation fail on the directories, mounted by `pipe storage mount`.

But this is a quite common use case, especially when dealing with data transfer via `rsync`.

The approach is described in the PR https://github.com/epam/cloud-pipeline/pull/661#issuecomment-538399907

**Comment by sidoruka** [comment]
Cherrypick please to `release/0.15`

**Comment by NShaforostov** [comment]
Verified

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.15` via 054b68610d15d00f9b07b0e254af2cb6dd783799.
