### ISSUE TITLE
Use load_formula to optimize resources usage for autoscaled clusters

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#825]
**Background**

Originally the current issue was described as a [comment](https://github.com/epam/cloud-pipeline/issues/298#issuecomment-502126594).

By default GE scheduler tries to submit jobs to a host with the minimal load within the cluster. It works fine for fixed size cluster because all the nodes are similarly occupied. Nevertheless, it doesn't work well with the autoscaled cluster. If there are several machines in the cluster GE will try to occupy each one of them preventing GE autoscaler from scaling down even if there are no many submitted jobs. The described situation leads to a significant resources redundancy.

**Approach**

To optimize the average cluster workload and reduce the redundant expenses GE scheduler job submission strategy can be altered. 

Several helpful links are the description of a `load_formula` [parameter](http://gridscheduler.sourceforge.net/htmlman/htmlman5/sched_conf.html) and examples of its [usage approaches](http://talby.rcs.manchester.ac.uk/~ri/_notes_sge/least_used_vs_fill_up.html).

Please consider the differences between persistent and additional cluster workers. Probably additional weight should be added to `load_formula` to fill up persistent workers before the additional ones.

**Comment by sidoruka** [comment]
Implemented via a bunch of changes:
6c6d194b6658de52ba5eeef0086abdb78dcd786f
55d506feab57f89da0af5fac558fc24016e43821
e6890434d88e2e088e45fbd02afa07b3234c9619
df3080740cfc03736bf51dc2dac4afa68d902344

SGE will be now configured with two complex attributes for each of the nodes:
* `worker_type`: wight of a static or autoscaled worker
  * Static workers get a value of `0`, configurable with `CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_STATIC`
  * Autoscaled workers get a value of `1000` , configurable with `CP_CAP_GE_CONSUMABLE_RESOURCE_DEFAULT_VALUE_WORKER_TYPE_ADD`
* `slots`: number of CPUs within a node

These new complex attributes can be used to define a `load_formula` of the SGE scheduler. Configurable via `CP_CAP_SGE_DEFAULT_LOAD_FORMULA`.

Default is still set to `np_load_avg`, which causes an even spread of the workload to all the nodes. To make SGE "fill up" the nodes and give more priority to the static workers - it shall be set to `slots+worker_type`.
