### ISSUE TITLE
Inconvenient label wrap in the "Cluster nodes" dashboard

### ISSUE THREAD

**Issue by NewOlya** [epam/cloud-pipeline#834]
**Background**
We have the list of labels on the cluster node.  So, when we go to the "Cluster nodes" dashboard we can see the "Labels" column for each node. If there are a lot of labels there the system might wrap the label. It is inconvenient for the user to understand which label it is.

**To Reproduce**

1. Go to the "Cluster nodes" dashboard
2. Find the node with a lot of labels

or
1. Go to the "Cluster nodes" dashboard
2. Click on the node with a lot of labels

**Approach**
It would be more convenient if the label name is displayed as a whole element, without wrapping it to the new string.

**Screenshot**
1:
![label1](https://user-images.githubusercontent.com/32195393/70622050-1bdf9e00-1c2c-11ea-9aaa-ddc18a188120.png)
2:
![label2](https://user-images.githubusercontent.com/32195393/70622043-16825380-1c2c-11ea-8f90-823445229c53.png)

**Comment by rodichenko** [comment]
@NewOlya fixed via 737b9bbfd202f215ce7d4f104ad9e286120d2b0e, can you re-check please?

**Comment by NewOlya** [comment]
Verified
