### ISSUE TITLE
Allow to disable root access to the instances

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#842]
**Background**

At the moment, each user who connects to the SSH session of the running job gets the `root` privileges, by default. Which can be dropped further, by switching to the "real" username.

While this is a convenient way to work, especially when certain packages shall be installed, it may introduce security concerns, e.g.:
* General users may install vulnerable packages
* Certain system files/configs/process can be dropped accidentally, which will lead to the job failure
* Ownership of the files is set to `root:root`, which makes it hard to process in certain cases

**Approach**

* Use the `real` user as a default login
* Make sure, that all required filesystem locations can be accessed by the `real` user
* Introduce a `System Parameter` (e.g. `CP_CAP_SUDO_ENABLE`), which will control whether the user `real` user can switch to `root` or not (allowed by default)

**Comment by NShaforostov** [comment]
Verified. Works well

**Comment by tcibinan** [comment]
Cherry-picked to `release/0.16` via 6fd8d4fb83d5e48eae9c3ab8a080182bb7868833 and 5fa2cb759f5fcee2d1c70fdf8ef8173fa3d7f945.
