### ISSUE TITLE
Packages are duplicated in the tool's version details

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#843]
Certain tools packages are duplicated in the `PACKAGES` details page of the tools version.
![image](https://user-images.githubusercontent.com/20998291/70994358-1a581f00-20df-11ea-843c-5b3e6bd97c8d.png)

**Comment by sidoruka** [comment]
@SilinPavel could you please review the bug and propose a solution?
Once fixed - port to `release/0.15`

**Comment by SilinPavel** [comment]
@sidoruka I can confirm that the bug exists, it is most likely because "traces" of those packages exist in several layers of the tool and `scan service` reports about it twice. 
So the easiest way to fix it would be to store distinct packages in DB for each tools while scanning

**Comment by NShaforostov** [comment]
Verified
