### ISSUE TITLE
Expose SSH link for the active runs in the Dashboard view

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#844]
At the moment, SSH link is only available in the job details page. It would be helpful if the SSH connection can be established right from the Active Runs Dashboard.

* It shall be shown only after all checks have passed (same as the job details page)
* It shall be shown for all the jobs: interactive and non-interactive
* SSH URL shall be fetched when a user clicks the respective button
* Keep in mind, that currently there can be up to 3 buttons already: `OPEN`, `PAUSE`, `STOP`. So the layout shall not be broken, once we add a new one

**Comment by sidoruka** [comment]
Cherry-pick to `release/0.15` once done

**Comment by rodichenko** [comment]
@sidoruka implemented, backported to `release/0.15` via 42654e1444322f12d3a611ac689ff6737d6ae84d

**Comment by NShaforostov** [comment]
Verified.
Docs were updated via #860
