### ISSUE TITLE
Allow to use custom domain names as a "friendly URL" for the interactive services

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#848]
**Background**
At the moment, Cloud Pipeline allows setting the interactive services endpoints in two flavours:
* Default: `https://<edge-host>/pipeline-<run-id>-<port>`
* Friendly: `https://<edge-host>/<friendly-url>` (if a [Friendly URL](https://cloud-pipeline.com/manual/10_Manage_Tools/10.5._Launch_a_Tool/#launch-a-tool-with-friendly-url) is set for a specific run)

For certain use cases, we'll need even more: allow to specify a custom host. So the endpoint url would look like: `https://<custom-host>` or `https://<custom-host>/<friendly-url>`

**Approach**
* *The overall approach is similar to the tool's `endpoints` handling*
* Extend the `Friendly URL` control in the GUI, it shall now accept three types of inputs:
  * `<friendly-url>` - a current behavior
  * `<custom-domain>` - shall be a valid domain name
  * `<custom-domain>/<friendly-url>` - a mixture of the above options. Can contain a single `/` char. Both parts shall be validated as previously
* These new options shall be described in the tooltip info for the `Friendly URL` control
* `friendly url` of the run shall now be stored as a json object, e.g. if a `Friendly URL` is set to `my.host.com/my_path` in the GUI:
```
{
  "domain": "my.host.com",
  "path": "my_path"
}
```
* For backward compatibility, if the `friendly url` is set to a non-json value (e.g. previously configured values) - it shall be treated as a `<friendly-url>` (a current behavior) and parsed/visualized accordingly
* Support the custom domains, when configuring endpoints routing in the `EDGE` service (vhosts)

**Comment by sidoruka** [comment]
Shall be cherry-picked to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.15` via 827abbed1d9d6e765efc43be7b095f8689397e60

**Comment by NShaforostov** [comment]
Verified for AWS stand.
Docs were updated via #991.
