### ISSUE TITLE
Log user creation and first/last login date and time

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#851]
**Background**
At the moment, Cloud Pipeline does not keep the date and time of the users' creation/login. But it's required for traceability

**Approach**
* Log the date/time of the user creation
* Log the date/time of the user's first login
* Expose this information via the corresponding API methods

**Comment by sidoruka** [comment]
Cherry-pick to `release/0.15` once done

**Comment by NShaforostov** [comment]
Verified jointly with #852 
Works well
