### ISSUE TITLE
Allow to export users/groups as a CSV

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#852]
**Background**

Once #851 is implemented, it would be convenient to export the users' list to process in the external tool (e.g. Excel). At the moment, we don't have such a capability.

**Approach**

API
* Expose API method to perform such an export (shall return a CSV)
* API shall allow to export:
  * User's attributes (ID, Name, Email, Creation/Login DT, etc.)
  * User's metadata
  * List of groups (AD/Roles)
* Which sections to export - shall be configurable via the API parameters

GUI

* GUI shall expose `Export to CSV` button in the `USERS MANAGEMENT` settings for the administrators
* This button shall allow exporting with the default settings (attributes/metadata) or customize the export
* If a custom export is chosen - admin shall be able to select which section to include into the report

**Comment by sidoruka** [comment]
Cherry-pick to `release/0.15` once done and tested

**Comment by rodichenko** [comment]
@sidoruka backported to `release/0.15` via a8744fd7f14101b15232649787c3044d2fbd0b20

**Comment by NewOlya** [comment]
I had a problem with reviewing this task, please take a look:

1. Excel displays dates (registrationDate, firstLoginDate) in inconvenient format:
![Excel date representation 852](https://user-images.githubusercontent.com/32195393/71578003-593a9b80-2b07-11ea-9571-262e0f3dba74.png)
After clicking 2 times on the cell, the date format becomes  standard (19-12-2019  12:46:49)

**Comment by NShaforostov** [comment]
It seems that User's metadata isn't being exported.
The rest works fine.
Docs were updated via #860

**Comment by NShaforostov** [comment]
The problem described in https://github.com/epam/cloud-pipeline/issues/852#issuecomment-569635696 was fixed by 92921612794aa62e9b361fef4d0842146625fbfd.

**Comment by NShaforostov** [comment]
@SilinPavel cherry-pick the changes to `release/0.15`, please

**Comment by SilinPavel** [comment]
@NShaforostov @sidoruka cherry-picked to 0.15
