### ISSUE TITLE
SLURM support for the static clusters

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#865]
**Background**
At the moment, Cloud Pipeline allows creating the clusters, that are managed by the 3rd party schedulers:
* GridEngine
* Spark

This feature is mostly used for backward compatibility with the existing code-base (which is a super common usage scenario).

To extend this compatibility - we need to implement [SLURM scheduler](https://slurm.schedmd.com/documentation.html) support as well

**Approach**
* Overall approach shall be the same as for the GridEngine implementation
* Only static cluster shall be implemented for now. Autoscaling feature shall be added further

**Comment by sidoruka** [comment]
@rodichenko you can proceed with the GUI part (use the same PR/branch please)

**Comment by sidoruka** [comment]
@NShaforostov, ready for the tests and docs

**Comment by NShaforostov** [comment]
I've tested this feature. Generally, it works.
But the following issues were identified:
1) After performing the simple script via the `sbatch` command over several nodes - the first node in the allocation (where the script was run) gets the `drained` state and remains with it. Also, such `sbatch` ends with the error.
   More details:
   - I used the following script (from [here](https://slurm.schedmd.com/quickstart.html))
   ![image](https://user-images.githubusercontent.com/45459424/73361292-b9169480-42b5-11ea-8c7d-e398afa72ef6.png)
   - The batch command was: `sbatch -N3 -o test.stdout test.script`
   - The nodes state during the job performing:
   ![image](https://user-images.githubusercontent.com/45459424/73361450-06930180-42b6-11ea-807d-6940e40619f6.png)
   - The nodes state after the job finish:
   ![image](https://user-images.githubusercontent.com/45459424/73361634-5f629a00-42b6-11ea-8378-93394c03c98b.png)
   - The output that contains the error:
   ![image](https://user-images.githubusercontent.com/45459424/73362030-2545c800-42b7-11ea-9e1a-3ce3bbc4cd51.png)
2) I tried to perform the script specified above on nodes without the master-node. In the result, the first node in the allocation (where the script was run) also got the `drained` state and remained with it. But in that case, the output contained also other errors:
   - The batch command was: `sbatch -N2 -w "pipeline-[21358-21359]" -o test.stdout test.script` (pipeline-21357 - master-node)
   - The output:
   ![image](https://user-images.githubusercontent.com/45459424/73364121-0d704300-42bb-11ea-9b1c-a9e645121b34.png)

Such behavior was observed for both - `Debian` and `Centos` images

**Comment by NShaforostov** [comment]
Docs were updated via #926

**Comment by sidoruka** [comment]
@SilinPavel please go ahead and fix the observed issues

**Comment by NShaforostov** [comment]
Verified, works fine.
Issues described [above](https://github.com/epam/cloud-pipeline/issues/865#issuecomment-579775009) were fixed by db4481bdc22b11a8848d7b54f6a10dcb9096a8bf.
