### ISSUE TITLE
Autoscaling: Delete cloud instance if nodeup process is not successful

### ISSUE THREAD

**Issue by mzueva** [epam/cloud-pipeline#87]
AWS implementation of autoscaling scripts terminates node if an error occurs in nodeup process after instance creation (see `increment_or_fail` function). Azure and GCP implementations are missing this logic.

**Comment by sidoruka** [comment]
@mzueva @SilinPavel please keep in mind node initialization duration for `Azure` which may not fall into the default timeout. E.g. we can end up with:
* Create a node
* Fail with timeout
* Delete node
* Create node
* ...
