### ISSUE TITLE
Parameter values changes cannot be saved for a tool

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#871]
**Describe the bug**
If a user changes the parameter value within a tool's settings form - `SAVE` button is still grayed out. One shall modify some other option (e.g. disk size) to save the overall changes.

**To Reproduce**
1. Go to any existing tool's settings form
2. Expand `Execution Environment` and change any parameter's value
3. `SAVE` button is disabled and a user cannot save the changes

**Expected behavior**
`SAVE` button can be clicked to save the modifications

**Environment:**
 - Cloud Provider: `N/A`
 - Version: `0.15.0.3680.be1bd955f0dc98ba617ba78860fe7342bc01e234` and up
 - Browser: Chrome

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka fixed, backporter to `release/0.15` via ef6232695ca6d7df7213cb55533130a3a6890394

**Comment by NShaforostov** [comment]
Verified
