### ISSUE TITLE
FSBrowser: "Upload" button is available even for non-existent paths

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#877]
**Describe the bug**
If in FSBrowser incorrect path (non-existent or from `storage.fsbrowser.black.list`) is entered to the address bar, the "Upload" button is anyway available.

**To Reproduce**
1. Open FSBrowser
2. Click the "breadcrumbs" control in the left upper corner
3. Specify any non-existent path
4. Press "Enter" key
5. See the error `[Errno 2] No such file or directory`
6. Check that the "Upload" button is enabled

**Expected behavior**
The "Upload" button is disabled

**Screenshots**
![image](https://user-images.githubusercontent.com/45459424/71283243-aa60c780-2370-11ea-9679-aedc7cd2eb51.png)

**Environment:**
 - Cloud Provider: N/A
 - Version 0.16.0.3843
 - Browser: N/A

**Comment by rodichenko** [comment]
@NShaforostov fixed, can you re-check please?

**Comment by NShaforostov** [comment]
Verified
