### ISSUE TITLE
Minor style enhancements at the "Cluster state" page

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#889]
**Background**

At the **Cluster state** page the table with cluster nodes is shown. Some notes about this table:
- in my view, the **Addresses** column of this table is too tiny to display simultaneously IP-address and the node name in one line
- the **Created** column is too tiny to display simultaneously date and time in one line. Time value is always divided into two lines (I checked it in different browsers and display resolutions)

![image](https://user-images.githubusercontent.com/45459424/71355897-8af4b500-2591-11ea-997b-cf45bcd53864.png)

**Approach**
1. Maybe it would be better to make a line break in cells of the **Addresses** column (IP-address in the first line and the node name in the second one) and adjust the column width to the "average" Azure node name length (_because Azure's nodes have the "longest" names_)?
2. Maybe it would be better to make a line break in cells of the **Created** column: date value will be in the first line and time value - in the second one.

**Comment by rodichenko** [comment]
@NShaforostov styles fixed (cd2f7375db23169de5335b6c8c055188d09019ea)

**Comment by NShaforostov** [comment]
@rodichenko, verified.
Now, it looks great, thanks!
