### ISSUE TITLE
Label "Estimated price per hour" is not visible on pipeline configuration tab

### ISSUE THREAD

**Issue by kamyshova** [epam/cloud-pipeline#91]
Label "Estimated price per hour" with the value doesn't exist on pipeline configuration tab

- Cloud environment: AWS & AZURE
- Version: 0.15.0.296.72d146bf70c408efd75911d31183caabb612c96a
- Steps to reproduce:
1) Create pipeline
2) Select the pipeline version
3) Select "CONFIGURATION" tab

![image](https://user-images.githubusercontent.com/23356251/55796429-ac307680-5ad2-11e9-86ee-f77a1bb6dd2c.png)

Expected: label "Estimated price per hour" with the value is visible
Actual: no label "Estimated price per hour"

**Comment by sidoruka** [comment]
Fixed in 2101c80
@kamyshova please verify and reopen this issue if the problem still exists

**Comment by maryvictol** [comment]
@rodichenko 
Issue is reproduced on AWS, Version: 0.16.0.5945: Label "Estimated price per hour" is shown on pipeline configuration tab **after refresh only**.

**Comment by rodichenko** [comment]
@maryvictol fixed (89b7ce7b8451302b8b0e2027202c0253a3d3be63), could you please verify this issue?

**Comment by maryvictol** [comment]
Verified on AWS, Azure Version: 0.16.0.6091
