### ISSUE TITLE
Azure nodes are launched with too big disks

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#912]
**Describe the bug**

Currently if user requests an instance in Azure deployment it starts with disk size which is significantly bigger then the requested disk size.

**To Reproduce**

1. Launch `ubuntu:latest` using `Standard_D2s_v3` with `50G` disk size.
2. Ssh to the run container.
3. Perform the following command `df -hT / | tail -n -1 | awk '{ print $3 }' | cut -d 'G' -f 1 && echo $instance_disk`
4. Notice that two printed numbers `77` and `50` differ significantly.

**Expected behavior**

Actual disk size of the instance should be almost the same as the requested one depending on the image size.

**Environment:**
 - Cloud Provider: Azure
 - Version 0.16.0.4063.c97d883e2ba68a864813377b604fce717ba9bf5a

**Comment by SilinPavel** [comment]
@mzueva  @tcibinan As was discovered, there was preference `cluster.instance.hdd_extra_multi` with non-standard value (100 instead of 3), so f.e. for ubuntu image with size ~ 100 mb cloud-pipeline would increase disk size on (100 *3 * 100) = 30GB.
I think we can close this one.
