### ISSUE TITLE
Add dockers group name validation at a creation time

### ISSUE THREAD

**Issue by sidoruka** [epam/cloud-pipeline#914]
**Background**
At the moment, Cloud Pipeline does not perform the validation of the docker tool group name, while it is being created. This allows creating the group, which contains invalid characters and a group becomes unusable

**Approach**
Add the validation, using the same logic as we use when committing an image

**Comment by sidoruka** [comment]
Backport to `release/0.15`

**Comment by rodichenko** [comment]
@sidoruka implemented, backported to `release/0.15` via eefb06cbe5e32badde9b52d09c261a8bf2f161a5
