### ISSUE TITLE
`pipe`: the `run` command works not fully correct with `--instance-count` option

### ISSUE THREAD

**Issue by NShaforostov** [epam/cloud-pipeline#928]
**Describe the bug**
The `pipe run` command with the option `--instance-count 0` launch a cluster with a 1 child node.

**To Reproduce**
1. Perform the CLI `pipe run` command with the `-ic 0` option, e.g.: `pipe run -y -id <disk_size> -it <instance_type> -di <docker_image> -cmd <command_template> -ic 0`
2. Open Active Runs via GUI or perform the CLI `pipe view-runs` command
3. See that new run was launched on a cluster with a 1 child

**Expected behavior**
A single node (not cluster) was launched.

**Screenshots**
![image](https://user-images.githubusercontent.com/45459424/73379435-44eae980-42d3-11ea-9b21-8c0ba1cf9ebe.png)

**Environment:**
 - Cloud Provider: N/A
 - Version 0.16.0.4125

**Comment by mzueva** [comment]
@ekazachkova I'd also suggest that `--ic 0` shall not be added to generated  `pipe run` command for single node runs

**Comment by NShaforostov** [comment]
Verified
