### ISSUE TITLE
Support for SSH access to run pods has to be removed

### ISSUE THREAD

**Issue by tcibinan** [epam/cloud-pipeline#994]
**Background**

Currently, there is a support for SSH access right to a run's pod via the following endpoint `ssh/container/{run_d}`. Nevertheless it hasn't been working for a long time now and it is not going to be fixed as long as it introduces a number of security issues.

**Approach**

The feature is not relevant and it can be removed from the edge service easily.

**Comment by sidoruka** [comment]
@tcibinan please go ahead and remove it, when you have time
